//
//  InputUnit.swift
//  MolecularRendererApp
//
//  Created by Philip Turner on 4/12/24.
//

import Foundation
import HDL
import MM4
import Numerics

struct InputUnit {
  var operandA: [Rod]
  var operandB: [Rod]
  var sum: [Rod]
  var operandDriveWall: DriveWall
  var sumDriveWall: DriveWall
  
  var holePatterns: [HolePattern] = []
  var rods: [Rod] {
    var output: [Rod] = []
    output.append(contentsOf: operandA)
    output.append(contentsOf: operandB)
    output.append(contentsOf: sum)
    return output
  }
  
  init() {
    var holeOffsets: [SIMD3<Float>] = []
    
    // Create the operand rods.
    var operandBoundsSet: [SIMD2<Float>] = []
    operandBoundsSet.append(SIMD2(2, 6))
    operandBoundsSet.append(3.25 + SIMD2(8, 12))
    
    let operandLattice = Self.createLattice(boundsSet: operandBoundsSet)
    var operandRod = Rod(lattice: operandLattice)
    operandRod.rigidBody.rotate(angle: -.pi / 2, axis: [0, 1, 0])
    do {
      var center = operandRod.rigidBody.centerOfMass
      center = SIMD3(center.z, center.y, center.x)
      operandRod.rigidBody.centerOfMass = center
    }
    
    do {
      var offset = SIMD3<Float>(0.5, 0.5, 0)
      var source = operandRod
      let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
      source.rigidBody.centerOfMass += SIMD3(offset) * latticeConstant
      source.rigidBody.centerOfMass += SIMD3(0.91, 0.85, 0)
      operandA = Self.createLayers(source: source)
      
      offset += SIMD3(1.5, 1.5, 0)
      holeOffsets.append(offset)
    }
    
    do {
      var offset = SIMD3<Float>(0.5 + 6, 0.5, 0)
      var source = operandRod
      let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
      source.rigidBody.centerOfMass += SIMD3(offset) * latticeConstant
      source.rigidBody.centerOfMass += SIMD3(0.91, 0.85, 0)
      operandB = Self.createLayers(source: source)
      
      offset += SIMD3(1.5, 1.5, 0)
      holeOffsets.append(offset)
    }
    
    // Create the sum rods.
    var sumBoundsSet: [SIMD2<Float>] = []
    sumBoundsSet.append(SIMD2(2, 6))
    sumBoundsSet.append(SIMD2(8, 12))
    
    let sumLattice = Self.createLattice(boundsSet: sumBoundsSet)
    var sumRod = Rod(lattice: sumLattice)
    sumRod.rigidBody.rotate(angle: -.pi / 2, axis: [0, 1, 0])
    do {
      var center = sumRod.rigidBody.centerOfMass
      center = SIMD3(center.z, center.y, center.x)
      sumRod.rigidBody.centerOfMass = center
    }
    
    do {
      var offset = SIMD3<Float>(0.5 + 6 * 2, 0.5, 0)
      
      // Correct for the extra spacing at the barrier between drive walls.
      offset.x += 2
      var source = sumRod
      let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
      source.rigidBody.centerOfMass += SIMD3(offset) * latticeConstant
      source.rigidBody.centerOfMass += SIMD3(0.91, 0.85, 0)
      sum = Self.createLayers(source: source)
      
      offset += SIMD3(1.5, 1.5, 0)
      holeOffsets.append(offset)
    }
    
    // Create the hole patterns.
    for offset in holeOffsets {
      // Emulate the presence of other layers in the logic unit.
      for layerID in -1...2 {
        let y = 6 * Float(layerID)
        holePatterns.append(
          Self.createHolePattern(offset: SIMD3(0, y, 0) + offset))
      }
    }
    
    // Create the ramp patterns.
    var rampPatterns: [RampPattern] = []
    for offset in holeOffsets {
      // Emulate the presence of other layers in the logic unit.
      for layerID in -1...2 {
        let y = -3.25 + 6 * Float(layerID)
        rampPatterns.append(
          Self.createRampPattern(offset: SIMD3(0, y, 0) + offset))
      }
    }
    
    // Create the operand drive wall.
    let operandPattern: RampPattern = { h, k, l in
      Origin { 13.5 * h }
      Plane { h }
      Replace { .empty }
    }
    operandDriveWall = Self.createDriveWall(
      patterns: rampPatterns + [operandPattern],
      serializedString: Self.operandDriveWallString)
    
    // Create the sum drive wall.
    let sumPattern: RampPattern = { h, k, l in
      Origin { 14.5 * h }
      Plane { -h }
      Replace { .empty }
    }
    sumDriveWall = Self.createDriveWall(
      patterns: rampPatterns + [sumPattern],
      serializedString: Self.sumDriveWallString)
  }
}

// MARK: - Rods

extension InputUnit {
  // Create a lattice for a logic rod.
  static func createLattice(boundsSet: [SIMD2<Float>]) -> Lattice<Hexagonal> {
    Lattice<Hexagonal> { h, k, l in
      let h2k = h + 2 * k
      Bounds { 21 * h + 2 * h2k + 2 * l }
      Material { .elemental(.carbon) }
      
      Volume {
        let pattern = Self.createDriveWallInterface()
        pattern(h, h2k, l)
      }
      
      for bounds in boundsSet {
        let pattern = Self.createKnobPattern(bounds: bounds)
        Volume {
          pattern(h, h2k, l)
        }
      }
    }
  }
  
  // Create an interface to the drive wall.
  static func createDriveWallInterface() -> KnobPattern {
    return { h, h2k, l in
      Concave {
        Concave {
          Origin { 1 * h2k }
          Plane { h2k }
          Origin { 1 * h }
          Plane { h2k - 3 * h } // k - h
        }
        Convex {
          Origin { 1.5 * h2k }
          Plane { h2k }
          Origin { 0.5 * h }
          Plane { -h }
        }
      }
      Replace { .empty }
    }
  }
  
  // Accepts bounds in multiples of the cubic diamond lattice constant.
  static func createKnobPattern(bounds: SIMD2<Float>) -> KnobPattern {
    let cubicConstant = Constant(.square) { .elemental(.carbon) }
    let hexagonalConstant = Constant(.hexagon) { .elemental(.carbon) }
    let shrunkBounds = bounds + SIMD2(0.125, -0.125)
    let scaledBounds = shrunkBounds * cubicConstant / hexagonalConstant
    
    return { h, h2k, l in
      Concave {
        Concave {
          Origin { scaledBounds[0].rounded(.down) * h }
          Plane { h }
        }
        Concave {
          Origin { 1.5 * h2k }
          Plane { h2k }
        }
        Concave {
          Origin { scaledBounds[1].rounded(.up) * h }
          Plane { -h }
        }
      }
      Replace { .empty }
    }
  }
  
  // Spawns the logic rods for all Y layers, from a single source rod.
  static func createLayers(source: Rod) -> [Rod] {
    let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
    let spacing = 6 * latticeConstant
    
    var output: [Rod] = []
    for layerID in 0..<2 {
      var rod = source
      rod.rigidBody.centerOfMass.y += spacing * Double(layerID)
      output.append(rod)
    }
    return output
  }
}

// MARK: - Housing

extension InputUnit {
  static func createHolePattern(offset: SIMD3<Float>) -> HolePattern {
    { h, k, l in
      Origin { offset[0] * h + offset[1] * k + offset[2] * l }
      
      Concave {
        Concave {
          Plane { h }
          Plane { k }
        }
        Concave {
          Origin { 4 * h + 4.25 * k }
          Plane { -h }
          Plane { -k }
        }
      }
      
      Replace { .empty }
    }
  }

  static func createRampPattern(offset: SIMD3<Float>) -> RampPattern {
    { h, k, l in
      Origin { offset[0] * h + offset[1] * k + offset[2] * l }
      
      Concave {
        Concave {
          Plane { h }
          Plane { k }
        }
        Concave {
          Origin { 4 * h }
          Plane { -h }
        }
        Concave {
          Plane { -k + l }
          Origin { 2 * l }
          Plane { l }
        }
      }
      
      Replace { .empty }
    }
  }
  
  static func createDriveWall(
    patterns: [RampPattern], serializedString: String? = nil
  ) -> DriveWall {
    var driveWallDesc = DriveWallDescriptor()
    driveWallDesc.dimensions = SIMD3(22, 17, 14)
    driveWallDesc.patterns = patterns
    driveWallDesc.patterns.append { h, k, l in
      Origin { 1 * l }
      Plane { -l }
      Replace { .empty }
    }
    driveWallDesc.patterns.append { h, k, l in
      Origin { 5.5 * l }
      Plane { l }
      Replace { .empty }
    }
    driveWallDesc.surfaceAtoms = serializedString
    
    let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
    var driveWall = DriveWall(descriptor: driveWallDesc)
    driveWall.rigidBody.centerOfMass.z -= (5.5 + 1) * latticeConstant
    return driveWall
  }
}

extension InputUnit {
  static let operandDriveWallString: String? = """
    7g4AAAAAAAAZgBmAhoEBALaAt4BugQYAtoABgCOCBgABgLWAJIIGAFuAW4DIgQYAkYEagIaBAQDz
    gHeAJ4EBAAWC2IB4gQYA9YC7f+KBAQACggyARIIGAMiBYIDMgQYAEICQgY+BAQB1gPeAKoEBAK2A
    KYJ1gQYAuX/zgOSBAQAGgAWCSYIGAFeAyYHRgQYAjoFNgXaBBgB1gWeBC4EBAOWA7IEngQEABYJD
    gnaBBgAYgBeA/YIBAHaAu39iggEAvH91gGOCAQC1gAGAlYMGAAGAtICVgwYAXIBcgDmDBgCOgQmA
    uoIGAHaBnX/TggEA8IC3f1iDAQADggqAsYMGAAiAjoG8ggYAnX90gdaCAQC2f++AWIMBAAmABYKw
    gwYA+IIfgIWBAQAjgreAD4EBACGCo38kggEANoNkgMeBBgBqhCCAgoEBAI+DvYAKgQEAcYPcgHSB
    BgDRg8l/64EBAJKDEYApggYApIRkgMiBBgD5glCBdYEGANqCb4EMgQEAI4IlggyBAQBnhFCBdYEG
    AEiEb4EMgQEAkIMmggyBAQBxg0SCdYEGALeCGYDFggEAVIPLf2qCAQB7glyAgYIGACSCoX+TgwEA
    roPGgECDAQAyg6yAooMBAMyC1oC0gwYALIQogM2CAQDwg2mAhoIGALuD54DVggYAdIOKgXaDAQAz
    g8uBNIMGADiEX4HTggYAl4TDgTCDBgBHhCOCj4MGAGiAaoI2gQEAC4D6gpWBAQCdfySCK4IBAFWA
    NoPTgQYAdIHUggqBAQDigFiDKYEBAI6BuoJ2gQYAZoDWgziBAQCrgJWDdoEGAAuAZ4SVgQEAm3+Q
    gy+CAQAFgHKDTIIGAFWAo4TTgQYABYKwg3aBBgB0gUGECoEBAI6BJ4R2gQYACID5gr6CBgCff9qC
    3oIBAJ9/I4KSgwEACIBmhL6CBgCff0eE3oIBAJ9/kIOTgwEACIBxg7GDBgDcgtmCDIEBACOCkoMM
    gQEA+oK7gnWBBgBJhNmCDIEBAJCDk4MMgQEAaIS7gnWBBgDcgkaEDIEBAPqCKIR1gQYAcYOxg3WB
    BgBJhEaEDIEBAGiEKIR1gQYAc4C+f9WDAQC/f3KA1oMBABeAF4BshAEAXIBcgKeEBgB1gZ1/QIQB
    AI6BCYAnhAYA8IC3f8WEAQCdf3aBQIQBAAmAj4EnhAYAt3/wgMWEAQC0gAGAAoUGAHOAvn9DhQEA
    AYC1gAKFBgC+f3OAQ4UBABeAF4DbhQEAXIBcgBWGBgAEgguAHoUGAI6BCYCUhQYAdYGdf66FAQAJ
    gAWCHoUGAAmAj4GUhQYAnX91ga+FAQC8ghuAMIQBAHmCXoDwgwYAJoKifwCFAQA6g7eAAYUBANCC
    TYEphAYAOoNngUmEAQA6gyKCBIUBAAqE4oHUgwEAfIJggFyFBgDRgtiAH4UGAL+CHYCchQEA0YJD
    gh+FBgDSgk6BloUGADyDbIGzhQEAn3/cgkaEAQCffyOC/4QBAAiA+oIohAYAn39JhEaEAQCff5CD
    AIUBAAiAaIQohAYAn3/cgrOFAQAIgPqClYUGAAiAcYMehQYAn39JhLOFAQAIgGiElYUGADODgYLr
    gwYAcYM+gi6EAQB0g/aC4oQBADSDOIOhhAYAoYR/gumDBgAOhJeCioQBAEqE3IJFhAYAooQ3g6GE
    BgDRgrqCloUGADqD1YK3hQEADoROg0GFAQAzg+6DWIUGAHKDq4ObhQEANIOlhA6GBgBJhJOD/IQG
    AKKE7oNYhQYADoQFhPeFAQBJhEmEs4UGAKKEpYQPhgYA1YUhgICBAQD9hL2AC4EBAN+E3IB0gQYA
    P4XJf+6BAQAAhRGAK4IGAD+HJYB7gQEAaoa+gAqBAQBMht2AdIEGAGyGEIAnggYAq4bJf+mBAQAQ
    hmWAxoEGANSFUIF1gQYA/YQmggyBAQDfhESCdYEGALWFcIEMgQEAQYdQgXWBBgBqhiaCDIEBAEyG
    RIJ1gQYAIodwgQyBAQDBhMx/bIIBAJmFKYDPggEAXIVqgIeCBgAlheaA2IIGAAqFxYBCgwEALIbL
    f2iCAQABhyKAyoIBAJSG5IDYggYAyIZogIWCBgB5hsOAQYMBAKSFXoHVggYA04SBgXaDAQC0hSOC
    joMGABWHXYHVggYAQYaBgXaDAQAEhsOBMIMGAC6HGYKLgwYAuYfdgHOBBgDXh8CACYEBANqHCIAc
    ggYAGIjEf9mBAQB8h2WAw4EGALCIHoCEgQEARIm5gA6BAQAmidmAd4EGAESJon8jggEAJ4kLgESC
    BgDqiGGAzIEGALmHRIJ1gQYAkohtgQyBAQDXhyaCDIEBAK+IToF2gQYA/olsgQyBAQBFiSaCDIEB
    ACaJRIJ1gQYAmofAf1mCAQDbh7uA2oIGAJKIoH/YggEAnYd6gCGDAQCwiAqAuoIGAASKnH/TggEA
    fYm2f1qDAQBCiQGAlYMGAIaIw4CMgwYAIIgogTODBgCLh6+BL4MGAJWIFoKfgwYA/YSTgwyBAQC3
    hdmCDIEBANWFu4J1gQYAaoaTgwyBAQAkh9mCDIEBAEKHu4J1gQYA34Sxg3WBBgC3hUaEDIEBANWF
    KIR1gQYATIaxg3WBBgAkh0aEDIEBAEKHKIR1gQYAkYjZggyBAQDXh5ODDIEBAK+Iu4J1gQYA/onZ
    ggyBAQBFiZODDIEBALmHsYN1gQYAkYhGhAyBAQAmibGDdYEGAK+IKIR1gQYA/olGhAyBAQB1heGB
    04MBAPCG14HQgwEAQoiDgM2DAQD+iMF/1YMBAKWIGoBqhAEABIqdf0CEAQB9ibZ/xoQBAOqIXYCm
    hAYALIh7gTqEAQBKiPaAwoQBAJiIlYEghAYASoh2gD+FAQAAicF/RIUBAEOJAYAChQYAkIi3gAGF
    BgCfiCGA2YUBAAOKnn+whQEA54hkgBGGBgAviCuC94QBADCIb4G1hQEAmIhKgtiEBgCZiE+B1IUG
    AN2EO4IuhAEAe4WXgomEAQDehPOC5YQBALeF24JFhAYADoZ/gumDBgBLhjqCLIQBAOqGlYKIhAEA
    S4bzguWEAQAPhjeDoYQGACaH2YJEhAYAe4VOg0GFAQDphk6DQIUBALeFk4P8hAYA3oSqg5yFAQB7
    hQWE+IUBALeFSoSzhQYAD4bug1iFBgAlh5KD/IQGAEuGqoOchQEA6YYFhPiFAQAPhqWED4YGACWH
    SYSzhQYAgId8gumDBgDChz6CLIQBAL2H9ILjhAEAfYc2g6CEBgCUiMyCVoQGAC2I44KuhQEAlogB
    g4+FBgB9h+6DV4UGALuHqYOZhQEAUYgKhPOFAQB8h6WED4YGAJSIg4MNhQYAkohLhLKFBgBmgEOF
    OIEBAKuAAoV2gQYAC4DUhZWBAQCbf/2EL4IBAAWA34RMggYA4oDFhCmBAQAFgh6FdoEGAHSBr4UK
    gQEAjoGUhXaBBgCrgG+GdoEGAAuAQoeVgQEAZoCxhjiBAQCbf2qGL4IBAAWATIZMggYAVYAQhtOB
    BgDigDKGKYEBAAWCi4Z2gQYAjoEBh3aBBgAIgNOFvoIGAAiA34SxgwYAn3/9hJODAQCff7SF3oIB
    AAiAQYe+ggYAn39qhpODAQAIgEyGsYMGAJ9/IofeggEAI4L/hAyBAQDcgrOFDIEBAPqClYV1gQYA
    kIMAhQyBAQBxgx6FdYEGAEmEs4UMgQEAaISVhXWBBgAjgmyGDIEBAPqCA4d1gQYAkINthgyBAQBx
    g4uGdYEGAGiEA4d1gQYAVoQxh9aCBgCQgyGHkIMGAKuA3Yd2gQYAZoAeiDiBAQAFgLmHTIIGAFWA
    fYfTgQYAm3/Yhy+CAQB0gRyHCoEBAOKAn4cpgQEABYL4h3aBBgALgK+IlYEBAGaAi4k4gQEAq4BK
    iXaBBgBVgOuI04EGAJt/RYkvggEABYAniUyCBgB0gYmICoEBAOKADIkpgQEAjoFviHaBBgAFgmWJ
    doEGAAiAuYexgwYAn3+PiN6CAQCff9eHk4MBAAiAroi+ggYAn3/8id6CAQCff0WJk4MBAAiAJomx
    gwYA3IIhhwyBAQAjgtqHDIEBAEmEIYcMgQEAkIPahwyBAQBxg/mHdYEGANyCjogMgQEAI4JHiQyB
    AQD6gnCIdYEGAEmEjogMgQEAkINIiQyBAQBohHCIdYEGAHGDZol1gQYA1oLnh6CDBgCgg+eH1oIG
    ADyDBYk9gwYAgIPIiIGDAQDWglqJpIMGACGEaYjUggYApoNdidqCBgBBhIaIPYMBAJ9//YQAhQEA
    n3+3hUaEAQAIgNWFKIQGAJ9/aoYAhQEAn38kh0aEAQAIgEKHKIQGAAiA34QehQYACIDVhZWFBgCf
    f7eFs4UBAAiATIYehQYACIBCh5WFBgCffySHs4UBANaCMYdWhAYAy4TChseDBgCuhCyH54MBAMeD
    wobLhAYA54Msh66EAQBGg8eGToUGANqCMofAhQYAw4S/hjqFBgDHg8GGNoYGAKWEKIdYhQEA5YMr
    hxmGAQCff5GIRoQBAJ9/14cAhQEACICviCiEBgCff/6JRoQBAJ9/RYkAhQEACIC5hx6FBgCff5GI
    s4UBAAiAJokehQYACICviJWFBgCff/6Js4UBANCDZYfQgwEA1IJpiCGEBgA9g4aIQYQBADuDSIkA
    hQEA1IKyh9iEBgA9g9CH9oQBADqDkIi2hQEA0YJmiR6FBgDQgq6I1IUGAP2EAIUMgQEA34QehXWB
    BgC3hbOFDIEBANWFlYV1gQYAaoYAhQyBAQBMhh6FdYEGACSHs4UMgQEAQoeVhXWBBgD9hG2GDIEB
    AN+Ei4Z1gQYA1YUDh3WBBgBqhm2GDIEBAEyGi4Z1gQYAQocDh3WBBgDBhTOH24IGAE6Fx4ZGgwYA
    MIc0h96CBgC7hseGR4MGALmHHoV1gQYA14cAhQyBAQCRiLOFDIEBAEWJAIUMgQEAJokehXWBBgCv
    iJWFdYEGAP6Js4UMgQEAuYeLhnWBBgDXh22GDIEBAEWJbYYMgQEAJomLhnWBBgCviAOHdYEGACaI
    woZEgwYA/YTahwyBAQDfhPmHdYEGALeFIYcMgQEAaobahwyBAQBMhvmHdYEGACSHIYcMgQEA/YRI
    iQyBAQC3hY6IDIEBANWFcIh1gQYA34RmiXWBBgBqhkiJDIEBACSHjogMgQEAQodwiHWBBgBMhmaJ
    dYEGANiEsofUggYA9oTQhz2DAQC2hY+IOoMBAESGs4fWggYAY4bThz+DAQAnh5qIPoMBANSFrojQ
    ggYAJIVsidOCBgAIhUuJPYMBAEeHtojVggYAS4YkidGCBgBkhjuJPYMBAOyGvokfgwEAuYf5h3WB
    BgCRiCGHDIEBANeH2ocMgQEA/okhhwyBAQBFidqHDIEBACaJ+Yd1gQYAkYiOiAyBAQDXh0iJDIEB
    ALmHZol1gQYAr4hwiHWBBgD+iY2IDYEBAESJSIkNgQEAJolmiXeBBgDEh8KH24IGACyIGog+gwYA
    6IdYiIKDAQCPiMKHpoMGAMeHNonWggYAG4imiTeDBgCOiDmJooMGABmGLIfngwEAOoW/hsOEBgBY
    hSiHpYQBADiGw4bHgwYAxoYoh6SEAQCnhr+Gw4QGADqFvoYvhgYAEoYoh1iFAQBZhSiHEYYBADCG
    v4Y6hQYAp4a9hi+GBgDGhieHEIYBAKWHwYbGgwYAh4crh+ODAQAjiMeGr4QGAIyINIc7hAYAo4fC
    hjKFBgCDhyuHUIUBADqIzYYDhgYAlogzh6OFBgAriJiIRYQBACyI0YcHhQEALYgEij6EAQAviESJ
    AIUBAJOItogjhAYAL4iRiLOFAQCWiLOHJYUGAJmIJokehQYAmYiviJWFBgCygACAc4YGAG6Axn+6
    hgEAAICygHOGBgDGf26AuoYBAHeAd4BphwEAuIC4gCSHBgDrgLF/OYYBAASCC4CLhgYAcYGifyGH
    AQCOgQuAAYcGALF/64A5hgEACIAFgouGBgChf3GBIocBAAuAjoEBhwYACoIbgL2HAQCOgdeAzIcG
    AMuBXoB5hwYAcYG3gDaIAQDWgI6BzIcGABuADIK8hwEAXoDLgXmHBgC0gHCBNYgBAASCTYHMhwYA
    TIEDgs+HBgAkgqF/boYBAHyCX4DIhgYAOYO3gG6GAQDQgteAi4YGAL+CHIAHhwEA04JCgoiGBgA8
    gyOCaYYBANCCToEBhwYAOoNrgSCHAQDAgtGAvIcBAH2CEIF5hwYAJIJpgTaIAQCefyKCbYYBAKF/
    3YIihwEACoD7ggGHBgCef4+DbYYBAAiAcoOLhgYAoX9KhCKHAQAKgGiEAYcGAByAeIO8hwEAXoA4
    g3mHBgDWgPqCzocGALWA3II3iAEAL4LdgtGHBgBlgR2CO4gBAPeBoIIeiAEAX4ClhHqHBgDXgGiE
    zocGALaASoQ4iAEATIFwg9CHBgAugkuE0YcGAGaBioM8iAEA9YEOhB6IAQA6g46DbYYBANWCuoL8
    hgYAP4PYghmHAQDRgq+DioYGAHSDZIRPhgEA04InhP2GBgA9g0KEHocBAIWCfYJ0hwYAyYI8grSH
    AQB0gh6DEIgBAM2CsIO0hwEAhILrg3WHBgBzgouEEYgBAC2Iv4BqhgEA8IjWf72GAQBribN/PYYB
    ADmJCIB1hgYAl4jcgEyGBgAAiqF/IYcBAAaJd4BohwEAR4m3gCSHBgAyiHGBI4cBAJmIBYKMhgYA
    nIiOgQKHBgABireANogBAGaJjoHNhwYA7ojMgXqHBgCsiAyCvYcBAEWJcIE2iAEA3oRhhFOGAQBL
    hmGEU4YBAC+IIoJuhgEAMojcgiSHAQCbiPqCAocGACuIh4N1hgEAuodjhFOGAQAsiFCEF4cBAJiI
    cIOMhgYAlYhuhPeGBgCsiHiDvYcBAO6IOIN6hwYAZon6gs6HBgBFidyCN4gBAOuIpIR1hwYAZIlo
    hMyHBgBCiUqENIgBAAiA34SLhgYAnn/8hG2GAQChf7iFIocBAAqA1YUBhwYAnn9qhm2GAQAIgEyG
    i4YGAKF/JYchhwEACoBDhwGHBgAcgOWEvYcBANaA1YXOhwYAtYC3hTeIAQBOgd+E0IcGAEKC2IXR
    hwYAa4H8hDqIAQAkgriFO4gBAByAUoa8hwEAXoAThnmHBgDWgEKHzYcGALWAJIc2iAEATIFLhtCH
    BgAogiaH14cGAGWBZIY9iAEA7IHrhiOIAQA0g1uFxoYGAHGDGYUKhwEADoS8hK6GAQBJhACFaoYG
    AKGEXIXGhgYADIRzhWWHAQBJhLeFIYcGAEiDwYa1hgYA4oIchxaHBgDEhL6GpoYGAKeEKYfBhgEA
    GIQYh1eHAQB/gmCFfocGAMSCI4XBhwEAaoPQhcOHAQAugxGGfYcGALeCTYbRhwYA14JrhjqIAQCf
    hBSGfIcGAEWEaobchwYA4oPDhoqHBgCbg/OG1YcBAAyEJIYiiAEAg4SqhiKIAQAIgLmHi4YGAJ5/
    14dthgEAoX+SiCGHAQCef0SJbYYBAAiAJ4mLhgYACoCwiAGHBgChfwCKIYcBABuAwIe8hwEAXoCA
    h3mHBgC1gJGINogBAEyBuIfQhwYAZIHRhzyIAQDrgVWIIYgBABuALYm8hwEAXoDtiHmHBgDWgK+I
    zocGALWA/4k3iAEAJ4KTiNiHBgBMgSWJ0IcGAGSBPok8iAEA64HEiSOIAQDVgrKHQoYGAECDzodc
    hgEAJYNgh1SHAQAig1SI5oYBANCCJIlKhgYAPIM9iWOGAQDagpKII4cGAB6D0ohkhwEAIoPCieaG
    AQB/gjeIfYcGAMWC+4e/hwEAbIJnhxiIAQDEgmqJwocBAH+CpYl9hwYAaILTiBqIAQC3hQGFa4YG
    AHuFvYSvhgEA3oQYhQqHAQB7hXaFZ4cBALeFuYUjhwYAD4ZdhceGBgAkhwCFaoYGAOiGvISuhgEA
    S4YZhQuHAQDrhnOFaIcBACeHt4UkhwYAF4Yph7+GAQCIhRmHQYcBADGGvYalhgYA3YTRhb+HAQBH
    htaFxYcBALiFe4bXhwYAUoXMhn+HBgAPhQqHwocBAIKFQoYpiAEA/oXEhgyIAQAMhhiGfocGACqH
    dIbRhwYAy4Yqh3WHAQDohr+GWYcGAOCGPoYUiAEAfYdbhcaGBgC8hxaFB4cBAFKId4VlhwEAlIjw
    hHmGBgCSiLeFIYcGAF2HvIbmhgYAd4coh8qGAQD2hxCHP4YBAJOIOYcGhwYAwofShcyHAQCpiN6E
    vIcBAGaJ1IXQhwYAR4m2hTmIAQCFhxCGgocGADqI2oZmhwYA+4cfh6eHAQCDiHyGKogBAGaHuoYT
    iAEAq4iThsKHBgAjiQKHyIcGAC2I2IdwhgEAV4hOiHGHAQCWiLaHjoYGAC+ITYlkhgEAS4jJiPKG
    AQAyiAGKI4cBAJuIZ4lLhgYAl4iNiCyHBgDqiHuHdocGAKqIt4e+hwEAPIkghzSIAQD8idmHOIgB
    AEuJkog6iAEAsogvicaHAQDyiO6IgYcGAGqJsIjRhwYARon/iTeIAQAUih6AiIEBALCKuIAOgQEA
    k4rYgHeBBgCviqN/IoIBAJCKC4BDggYAVYpggMuBBgCHix+AhYEBAB6MvYAKgQEAAYzcgHSBBgAi
    jBGAKYIGAMWLZIDHgQYAHIpOgXaBBgCyiiaCDIEBAJSKRIJ1gQYAiYtQgXWBBgBqi2+BDIEBAB+M
    JoIMgQEAAYxEgnWBBgAcigiAuoIGAAmLXICAggYAs4qhf5ODAQCSigqAsYMGAEWLGIDEggEA5IvM
    f2uCAQBLjOeA1YIGAFuL1oC0gwYAPozGgECDAQDCi6yAooMBAASMioF2gwEAw4vLgTSDBgD6jCCA
    goEBAG6N3IB0gQYAYYzJf+uBAQCPjRGAK4IGADSNZIDIgQYAZY4hgICBAQCMjb2AC4EBAM+NyX/u
    gQEAoI5lgMaBBgD2jFCBdYEGANiMb4EMgQEAbo1EgnWBBgBjjlCBdYEGAESOcIEMgQEAjI0mggyB
    AQC7jCiAzYIBAFCNzH9sggEAf4xpgIaCBgC1jeaA2IIGAJqNxYBCgwEAKI4pgM+CAQC8jst/aIIB
    AOyNaoCHggYACI/DgEGDAQDHjF+B04IGAGONgYF2gwEA1owjgo+DBgAmjcOBMIMGADSOXoHVggYA
    lI7DgTCDBgBDjiOCjoMGAB2Ku4J1gQYAsoqTgwyBAQBsi9mCDIEBAIqLu4J1gQYAH4yTgwyBAQCU
    irGDdYEGAB2KKIR1gQYAAYyxg3WBBgBsi0aEDIEBAIqLKIR1gQYA2YzZggyBAQD3jLuCdYEGAEaO
    2YIMgQEAjI2TgwyBAQBkjruCdYEGAG6NsYN1gQYA2YxGhAyBAQD3jCiEdYEGAEaORYQNgQEAZI4n
    hHeBBgAJi12A8IMGAB2KCYAnhAYAtYqifwGFAQBLixuAMIQBAMmLt4ABhQEAYItNgSmEBgDKi2eB
    SYQBAMqLIoIEhQEAlIoLgB6FBgAMi1+AXIUGAB2KCYCVhQYAYIvYgB+FBgBOix2AnIUBAGGLQ4If
    hQYAYotOgZWFBgDMi2yBs4UBAJmM4oHUgwEABY7hgdODAQDDi4GC64MGAAGMPoIuhAEAA4z2guKE
    AQDDiziDoYQGAGGLuoKWhQYAyovVgreFAQDDi+6DWIUGAAGMq4ObhQEAw4ulhA6GBgAwjX+C6YMG
    AGyNO4IuhAEAnYyXgoqEAQDZjNyCRYQGAG2N84LlhAEAMY03g6GEBgCejn+C6YMGAAqOl4KJhAEA
    R47bgkWEBgCfjjeDoYQGAJ2MToNBhQEACo5Og0GFAQDZjJOD/IQGADGN7oNYhQYAnYwFhPeFAQBt
    jaqDnIUBANmMSYSzhQYAMY2lhA+GBgBGjpOD/IQGAJ6O7oNYhQYACo4FhPiFAQBGjkqEs4UGAJ6O
    pYQPhgYAzo8lgHuBAQD5jr6ACoEBANuO3YB0gQYAOo/Jf+mBAQD7jhCAJ4IGAAyQZYDDgQYAP5Ee
    gISBAQBnkMCACYEBAEmQ3YBzgQYAp5DEf9mBAQBpkAiAHIIGANCPUIF1gQYAsY9wgQyBAQD6jiaC
    DIEBANuORIJ1gQYAPpFOgXeBBgBmkCWCDYEBAEiQQ4J3gQYAIZFsgQ2BAQCRjyKAyoIBAFiPaICF
    ggYAI4/kgNiCBgAqkMB/WYIBAD+RCoC6ggYAapC7gNqCBgAhkaB/2IIBAC2QeoAhgwEAF5HCgI2D
    BgCkj12B1YIGANCOgYF2gwEAGpCvgTCDBgC9jxmCi4MGALCQJ4EzgwYAJJEWgqCDBgC1kdiAeYEG
    ANORuIAPgQEAtZEMgESCBgDTkaN/I4IBAHmRYIDMgQYAjZK2gCOCBgDPknSA4oEBAGySjoF5gQYA
    9pEFgneBBgCNknGBEIEBACeTDIKKgQEAN5OOgUSCBgCgk3GBJIIBAOSSzIHMgQYAbJIMgPyCBgD1
    kQqAcoMGAI2So3/eggEAN5PXgPyCBgCgk7aA3oIBACeTHIB5gwEA5JJfgDmDBgA5kwWCu4IGADmT
    TYFygwYAs4/Ygg2BAQD5jpKDDYEBANGPuoJ3gQYAHpHdgg2BAQAAkfuCd4EGANuOsYN3gQYAsY9K
    hA2BAQCSj2iEd4EGAGuQkIMNgQEAiZByg3eBBgAekUmEDIEBAP+QaIR1gQYA2JEigg2BAQBskvuC
    eIEGAIyS3YIPgQEAJ5N4g4qBAQCik92CJIIBAOSSOIPMgQYAOZP7gkWCBgDXkY+DDIEBAPWRcoN2
    gQYAbJJohHiBBgCMkkqED4EBAKKTSoQkggEA5JKlhMyBBgA5k2iERYIGAKOTIoLYggEAo5PdgpKD
    AQA6k/uCsYMGADuTcoO7ggYApZOPg9mCAQCkk0mEk4MBADuTaISxgwYA1JCBgM6DAQBFkQ+AY4QB
    AICP14HQgwEAvJB5gTyEAQAnkZWBIIQGAN2Q5oDDhAEAKJGsgAGFBgDnkGeAQIUBAD2RFoDWhQEA
    vpArgveEAQAnkUqC2IQGAL+QaoG3hQEAKpFNgdWFBgDYkaB/kIMBAHCSC4BnhAYAhJFVgKKEBgCT
    kqJ/SIQBAKOTuYBKhAEAKZMegOaEAQA6k9mAaIQGAOaSYICmhAYAo5NrgY+DAQCjkyWCSoQBADqT
    Q4JohAYA4ZGbf/yEAQD9kQWA3oQGAG2SC4DUhQYAgJFegA+GBgCNkqJ/t4UBAKKTt4C2hQEAOJPY
    gNSFBgDkkmCAEIYGADuTT4HfhAYApZNtgf2EAQCkkyWCtoUBADuTQ4LUhQYA2446giyEAQAPkHyC
    6YMGAHmPlYKIhAEA247zguWEAQC1j9mCRIQGAA2QNoOghAYAUZA+giyEAQBNkPSC44QBACSRzIJW
    hAYAeI9Og0CFAQC8kOOCroUBACWRAYOPhQYAtI+Sg/yEBgAMkO6DV4UGANuOqoOchQEAeI8FhPiF
    AQC0j0mEs4UGAAyQpYQPhgYAI5GDgw2FBgBKkKmDmYUBAOGQCoTzhQEAIpFLhLKFBgA6k3KDJ4QG
    AKOTkINFhAEAo5NKhACFAQA6k7qC34QGAKOT2IL9hAEAo5OSg7aFAQA6k2iEHoUGADmTsIPVhQYA
    sooAhQyBAQCUih6FdYEGAB2KlYV1gQYAH4wAhQyBAQABjB6FdYEGAGyLs4UMgQEAiouVhXWBBgCy
    im2GDIEBAJSKi4Z1gQYAHYoDh3WBBgAejG2GDYEBAACMi4Z3gQYAiYsCh3eBBgAfjCGHkIMGAG6N
    HoV3gQYA2YyzhQ2BAQD3jJWFd4EGAIyNAIUNgQEA/o79hA2BAQBDjreFDYEBACWO1YV3gQYAkI1q
    hg2BAQCujUyGd4EGALiMQ4d3gQYA1owlhw2BAQD9jmqGDIEBAEOOJIcMgQEAJY5Ch3WBBgDmjDGH
    1oIGAFCOM4fbggYA3o3HhkaDBgCxitqHDYEBAJOK+Id3gQYAa4sghw2BAQBBjLqHd4EGAGmLkogN
    gQEAI4zYhw2BAQAcim+Id4EGAPyJ/4kNgQEAtopFiQ2BAQDUiieJd4EGAEuLsIh3gQYAaYv+iQyB
    AQAijEWJDIEBAECMJol1gQYAL4znh9aCBgBmi+eHoIMGADWMXYnaggYAzIsFiT2DBgAPjMiIgYMB
    AGaLWomkgwYAro25h3WBBgCQjdeHDIEBANaMkYgMgQEA/Y7XhwyBAQBDjpGIDIEBALiMr4h1gQYA
    kI1FiQyBAQDWjP6JDIEBAK6NJol1gQYAJY6viHWBBgD9jkWJDIEBAEOO/okMgQEAaI2yh9SCBgCG
    jdCHPYMBAEWOj4g6gwEAsYxpiNSCBgC0jWyJ04IGANGMhog9gwEAl41LiT2DAQBkjq6I0IIGAGaL
    MYdWhAYA1ovHhk6FBgBqizOHwIUGAFuNwobHgwYAPo0sh+eDAQB2jCyHroQBAFaMwobLhAYAx47D
    hseDBgCpjiyH54MBAOiNKIelhAEAyo2/hsOEBgBSjb+GOoUGAFeMwYY2hgYAdYwrhxmGAQA0jSiH
    WIUBAMCOv4Y6hQYAyo2+hi+GBgDojSiHEYYBAKKOKIdYhQEAY4tpiCGEBgDNi4aIQYQBAMqLSIkA
    hQEAY4uyh9iEBgDNi9CH9oQBAMmLkIi2hQEAYYtmiR6FBgBgi66I1IUGAGCMZYfQgwEAHI/fhHeB
    BgCwj7eFDIEBAJKP1YV1gQYAapD9hAyBAQCIkN+EdYEGAB6Rt4UMgQEA/5DVhXWBBgAbj0yGdYEG
    ALCPJIcMgQEAko9Ch3WBBgBqkGqGDIEBAIiQTIZ1gQYAHpEkhwyBAQD/kEKHdYEGAL+PNIfeggYA
    S4/HhkeDBgC1kMKGRIMGANeR/IQMgQEA9ZHfhHaBBgBsktWFeIEGACeT5YSKgQEAjJK4hQ+BAQA5
    k9WFRYIGAKKTuIUkggEA15FqhgyBAQD1kUyGdoEGAGySQ4d4gQYAJ5NThoqBAQCMkiWHD4EBAOSS
    E4bMgQYAOZNDh0WCBgCikyWHJIIBADuT34S7ggYApZP8hNmCAQA7k9WFsYMGAKSTt4WTgwEAO5NM
    hruCBgClk2qG2YIBADuTQoexgwYApJMkh5ODAQAbj7mHdYEGALCPkYgMgQEAiJC5h3WBBgBqkNeH
    DIEBAB6RkYgMgQEAko+viHWBBgAbjyaJdYEGALCP/okMgQEA/5CviHWBBgBqkEWJDIEBAIiQJol1
    gQYAHpH+iQyBAQDUjrSH1oIGAPOO04c/gwEAto+aiD6DAQBTkMKH24IGAB6RwoemgwYAeJBYiIKD
    AQC7kBqIPoMGANePtojVggYA2o4kidGCBgDzjjuJPYMBAHyPvokfgwEAVpA2idaCBgCqkKaJN4MG
    AB6ROYmigwYA9ZG5h3aBBgDXkdeHDIEBACeTwIeKgQEAjJKSiA+BAQDkkoCHzIEGAKKTkogkggEA
    bJKwiHiBBgDXkUSJDIEBAPWRJ4l2gQYAJ5MtiYqBAQCMkgCKD4EBAOSS7YjMgQYAOZOwiEWCBgCi
    kwCKJIIBADuTuYe7ggYApZPXh9mCAQCkk5GIk4MBADuTJ4m7ggYAO5OviLGDBgClk0SJ2YIBAKST
    /omTgwEANJDBhsaDBgAWkCuH44MBADePv4bDhAYAVY8oh6SEAQAbkTSHO4QGALOQx4avhAYAMpDC
    hjKFBgA3j72GL4YGABKQK4dQhQEAVY8nhxCGAQAlkTOHo4UGAMqQzYYDhgYAO5PfhCiEBgCkk/2E
    RoQBAKSTt4UAhQEAO5NMhiiEBgCkk2qGRoQBAKSTJIcAhQEAO5PVhR6FBgA5k9+ElYUGAKOT/YSz
    hQEAO5NChx6FBgA7k0yGlYUGAKWTaoazhQEAu5CYiEWEAQC7kNGHB4UBACORtogjhAYAvZAEij6E
    AQC/kESJAIUBACWRs4clhQYAv5CRiLOFAQApkSaJHoUGACmRr4iVhQYAO5O5hyiEBgCkk9eHRoQB
    AKSTkYgAhQEAO5MmiSiEBgCkk0WJRoQBAKST/okAhQEAO5O5h5WFBgCkk9eHs4UBADuTr4gehQYA
    O5MmiZWFBgCkk0WJs4UBALOKoX9uhgEAk4oLgIuGBgALi1+AyIYGAB2KCoABhwYAYIvXgIuGBgDJ
    i7eAboYBAE+LHIAHhwEAY4tCgoiGBgDMiyOCaYYBAGCLTYEBhwYAyotqgSCHAQCZihuAvIcBAFqK
    XoB5hwYAHorWgMyHBgBPi9GAvIcBAAyLEIF5hwYAlIpNgcyHBgDciQSCz4cGALSKaYE2iAEAyouO
    g22GAQBli7qC/IYGAM+L2IIZhwEAYYuvg4qGBgAEjGSET4YBAGOLJ4T9hgYAzItChB6HAQAUi32C
    dIcGAL6K3YLRhwYA9YkdgjuIAQCGiqCCHogBAAOLHoMPiAEAWYs8grSHAQDciXCD0IcGABOL64N1
    hwYAvYpLhNGHBgD2iYqDPIgBAIWKDoQeiAEAAouLhBGIAQBdi7CDtIcBAG2NYYRThgEALJHWgEuG
    BgDCkLWAaYYBACmRBYKLhgYAwZBxgSGHAQAqkY6BAYcGADmRDIK7hwEA+JELgEuGBgDYkaF/aIYB
    AESSwX9nhwEAiZIAgCWHBgCQkXeAYocBANSRuIAhhwYAKpMagEmGAQDHkrZ/6oYBAECTtYAlhwYA
    h5N1gOeGAQA6k02BS4YGAKaTZ4FkhgEAhJP1gGaHAQA7kyiCLYcGAImT64H1hgEAh5KzgNmHBgBC
    knCAFogBACaTGIDChwEA5ZJagH+HBgDzkY2BzocGAH2RzIF5hwYAZZIEgtOHBgDQkW6BNogBACCT
    joHKhwEA3pLJgYOHBgDEku2AJogBAL+QI4JthgEAwJDcgiKHAQApkfqCAYcGANuOYYRThgEAu5CI
    g3SGAQAokXCDjIYGAEqQY4RThgEAupBQhBWHAQAjkW6E9YYGADmReYO7hwEAO5O6gkuGBgCmk9SC
    ZYYBAHmTaoJyhwEAiJNYg/eGAQA5kyaES4YGAKWTQYRlhgEAOpOVgy6HBgB4k9aDc4cBAHyROIN5
    hwYA8pH5gs6HBgDPkduCN4gBAByT+oLOhwEA3ZI2g4SHBgCCkiKCPogBAGSScoPUhwYAeJGkhHOH
    BgDukWaEy4cGAMqRR4QziAEAGpNnhM+HAQDckqOEhYcGAICSj4M+iAEAw4tbhcaGBgABjBmFCocB
    ANeLwYa1hgYAcoschxeHBgDcid6E0IcGAA+LYIV+hwYA0YrYhdGHBgD5ifqEOogBALOKuIU7iAEA
    U4sjhcGHAQD6i9CFw4cBANyJSobQhwYAt4omh9eHBgD1iWSGPIgBAHqK6oYhiAEARotNhtGHBgC+
    ixGGfYcGACqM84bVhwEAZotrhjqIAQDZjACFaoYGAJ2MvISuhgEAMY1chcaGBgBtjRiFCocBAJyM
    c4VlhwEA2Iy3hSGHBgAKjr2Er4YBAEaOAYVrhgYAno5dhceGBgAKjnaFZ4cBAEaOuYUjhwYAU42+
    hqaGBgCnjBiHV4cBADeNKYfBhgEAwI69hqWGBgAYjhmHQYcBAKeOKYe/hgEAbY3Rhb+HAQDVjGqG
    3IcGAC6NFIZ8hwYAcYzDhoqHBgCbjCSGIogBABONqoYiiAEAnI4Yhn6HBgBIjnuG14cGAOKNzIZ/
    hwYAno0Kh8KHAQARjkKGKYgBAI2OxIYMiAEAZYuzh0OGBgDQi9CHXYYBALSLYYdUhwEArotViO+G
    AQBgiySJSoYGAMyLPYljhgEAZIuTiCqHBgCli9KIbocBALGLwYnohgEAG4r4h8+HBgAHizSIgIcG
    APuKZIcaiAEAS4v7h8eHAQCPim+I0YcGAN2JJ4nQhwYADYukiX+HBgCtio2IO4gBAPeJQYk8iAEA
    e4rGiSWIAQBNi2aJxYcBAHiPvISuhgEAtI8AhWqGBgANkFuFxoYGANuOGYULhwEAe49zhWiHAQC3
    j7eFJIcGACOR8IR5hgYAS5AWhQeHAQDikHeFZYcBACGRt4UhhwYA7Y+8huaGBgCGkBCHP4YBAAeQ
    J4fKhgEAI5E5hwaHBgDXjtaFxYcBADWR34S6hwEAUpDShcyHAQAUkBCGgocGALqPdIbRhwYAeI+/
    hlmHBgBajyqHdYcBAG+PPoYUiAEA9o+6hhOIAQA6kZOGwYcGAIqQH4enhwEAyZDahmaHBgARkXuG
    KYgBADqT1YWLhgYApJO3hW6GAQA5kwKFL4cGAIaTxIT3hgEAeZNBhXSHAQA8k0CHiIYGAKSTIYdp
    hgEAOJNMhgGHBgCik2mGIocBAGKS3oTThwYA9ZHVhc+HBgDXkbiFOYgBACaT2IXChwEAfJL6hD+I
    AQBrkkyGzYcGALKRAYfIhwYA45IQhnqHBgAykzqHtIcBAIuSaYY3iAEAJZG2h46GBgC9kNiHcIYB
    AOeQTohzhwEAvpBNiWSGAQAqkWeJS4YGANyQyoj1hgEAKJGNiC2HBgDCkAGKI4cBADmRt4e+hwEA
    RJEuiciHAQCkk5GIbIYBAD6TuYf7hgYAqJPXhxmHAQA7k6+IioYGAKWT/4lthgEAOpMnif+GBgCj
    k0SJH4cBAHmRe4d2hwYAmJLbh9CHBgDHkRuHNYgBAF+SnocciAEA4JGTiD2IAQDuknuHdIcGAN2S
    GogQiAEAhJHtiIOHBgD9kbGI04cGAHGSKInOhwYA15EAijiIAQAvk7GIuYcBAOeS6oh3hwYAk5JH
    iTaIAQALgByKlYEBAGaA+Io4gQEAq4C3inaBBgBVgFiK04EGAJt/soovggEABYCUikyCBgB0gfaJ
    CoEBAI6B3Il2gQYA4oB6iimBAQAFgtOKdoEGAAuAiYuVgQEAq4AljHaBBgCbfx+ML4IBAAWAAYxM
    ggYAVYDFi9OBBgB0gWSLCoEBAI6BSYt2gQYA4oDniymBAQAFgkCMdoEGAAiAG4q+ggYACICUirGD
    BgCff7KKk4MBAAiAiIu+ggYAn39pi96CAQCffx+Mk4MBAAiAAYyxgwYA3IL7iQyBAQD6gt2JdYEG
    ACOCtIoMgQEASYT7iQyBAQBohN2JdYEGAJCDtYoMgQEAcYPTinWBBgDcgmmLDIEBAPqCSot1gQYA
    I4IhjAyBAQBJhGmLDIEBAGiESot1gQYAkIMijAyBAQBxg0CMdYEGADSDWoo0gwYAdYMXinODAQA0
    hOmJ2IIGAJaEUIoxgwYARoSyio+DBgALgPeMlYEBAGaAZow4gQEAq4CSjXaBBgAFgG6NTIIGAFWA
    Mo3TgQYAjoG2jHaBBgB0gdGMCoEBAOKAVI0pgQEABYKtjXaBBgBmgNONOIEBAAuAZI6VgQEAm3+N
    jS+CAQBVgKCO04EGAHSBPo4KgQEA4oDCjimBAQCOgSSOdoEGAAiA9oy+ggYAn3/XjN6CAQAIgG6N
    sYMGAAiAY46+ggYAn39Ejt6CAQCff4yNk4MBAPqCuIx1gQYA3ILWjAyBAQAjgo+NDIEBAGiEuIx1
    gQYASYTWjAyBAQCQg4+NDIEBAHGDro11gQYA3IJDjgyBAQAjgvyODIEBAPqCJY51gQYASYRCjg2B
    AQCPg/2ODYEBAGeEJI53gQYACIAdiiiEBgCff7KKAIUBAJ9/bItGhAEACICKiyiEBgCffx+MAIUB
    AAiAlIoehQYACIAdipWFBgAIgAGMHoUGAAiAiouVhQYAn39si7OFAQAzgxCL64MGAHGDzoouhAEA
    1ILXiSOEBgA+g/KJRIQBADqDsYoDhQEACYRyitWDAQChhA+L6YMGAHSDhovihAEANIPIi6GEBgAO
    hCeLioQBAEqEa4tFhAYAooTHi6GEBgDRgtKKH4UGANGC3YmVhQYAO4P7ibOFAQDRgkmLloUGADqD
    ZYu3hQEAcoM7jJuFAQAOhN6LQYUBAEmEIoz8hAYAn3/ZjEaEAQAIgPeMKIQGAJ9/Ro5GhAEAn3+M
    jQCFAQAIgGSOKIQGAAiAbo0ehQYACID3jJWFBgCff9mMs4UBAJ9/Ro6zhQEACIBkjpWFBgAzg36M
    WIUGADSDNY0OhgYAooR+jFiFBgAOhJWM94UBAEmE2YyzhQYAooQ0jQ+GBgC3hfuJDIEBANWF3Yl1
    gQYA/YS1igyBAQDfhNOKdYEGACSH+4kMgQEAQofdiXWBBgBqhrWKDIEBAEyG04p1gQYAt4VpiwyB
    AQDVhUqLdYEGAP2EIowMgQEA34RAjHWBBgAkh2iLDYEBAEKHSot3gQYAaYYijA2BAQBLhkCMd4EG
    AKOF64nUggYA04QPineDAQC0hbKKjoMGACiH/4nZggYABIZQijCDBgBAhg6KdYMBADCHqoqNgwYA
    kYj6iQ2BAQC5h9OKd4EGANeHtYoNgQEAr4jciXeBBgBJibKKDYEBAGeJlIp3gQYA24cfjA2BAQD5
    hwGMd4EGAI6IbIsNgQEAcIiKi3eBBgBIiR+MDIEBAGaJAYx1gQYAk4dEijSDBgCUiKWKoIMGANSF
    t4x3gQYA/ISPjQ2BAQDehK2Nd4EGALaF1YwNgQEAA4f4jHeBBgCMhm+Nd4EGALSFR44NgQEAloVl
    jneBBgBuho2NDYEBAAOHZI51gQYAIYfajA2BAQD5h26NdYEGAI6I2YwMgQEAcIj3jHWBBgBmiW6N
    dYEGANqHjI0MgQEAIYdGjgyBAQBIiYyNDIEBAI6IRo4MgQEAcIhkjnWBBgDdhMuKLoQBAHWFcIrT
    gwEADoYOi+mDBgBMhsmKK4QBAPOGZ4rRgwEA3oSCi+WEAQB7hSeLiYQBALeFa4tFhAYAS4aCi+WE
    AQDphiWLiYQBACWHaotEhAYAD4bGi6GEBgC3hSKM/IQGAHuF3otBhQEA3oQ5jJyFAQAkhyKM/IQG
    AOmG3YtAhQEAS4Y6jJyFAQCAhw2L6oMGAMKHz4ouhAEAl4gjiiGEBgC9h4SL44QBAH2HxoughAYA
    lIhbi1aEBgAxiPyJtoUBAC+Iu4r3hAEAmIjaitiEBgCbiN2J1IUGAC2IcouuhQEAu4c5jJmFAQCU
    iBKMDYUGAJaIkYuPhQYAt4XZjLOFBgB7hZWM+IUBAA+GfoxYhQYAJYfZjLOFBgDphpSM+IUBAA+G
    NY0PhgYAfYd9jFeFBgBRiJqM84UBAHyHNY0PhgYAkojajLKFBgBmgECPOIEBAKuA/452gQYAC4DR
    j5WBAQCbf/qOL4IBAAWA3I5MggYAVYANkNOBBgAFghqPdoEGAHSBq48KgQEAjoGRj3aBBgBmgK2Q
    OIEBAKuAbJB2gQYAC4A+kZWBAQCbf2eQL4IBAAWASZBMggYA4oAvkCmBAQAEgoeQd4EGAHSBGJEM
    gQEAjoH+kHeBBgAIgNCPvoIGAJ9/sY/eggEAn3/6jpODAQAIgNuOsYMGAAiAPZG+ggYACIBJkLGD
    BgCff2eQk4MBAJ9/HpHeggEA3IKvjw2BAQD6gpKPd4EGAHGDG493gQYARoS0jw2BAQAohNKPd4EG
    ACKCaZAOgQEAlINnkA2BAQDZgiKRDYEBALuCP5F3gQYAsYNJkHeBBgBGhCGRDIEBACiEP5F1gQYA
    VoTBj9aCBgCQg7GPkIMGANaCd5CggwYAgINXkYGDAQCgg3eQ1oIGACGE+ZDUggYAQYQWkT2DAQCq
    gNqRdoEGABaAr5KLgQEAZYAZkjeBAQAFgLaRTIIGAFWAepHUgQYAm3/VkS+CAQDjgJyRKoEBAESC
    tpF3gQYATYGtknaBBgAmgtWRDYEBAGuBj5IMgQEA14Ajk3iBBgC2gEGTD4EBAAqAI5NGggYAXoDo
    ks6BBgChf0GTJoIBAESCI5N1gQYAJYJBkwyBAQBsgfyTDIEBAAmArJK8ggYACIC2kbGDBgCff4+S
    2oIBAJ9/1JGTgwEACIAjk7GDBgCef/yT2YIBAJ9/QpOTgwEAk4PUkQyBAQDZgo6SDIEBALuCrJJ1
    gQYAsYO2kXWBBgBGhI6SDIEBACiErJJ1gQYAk4NBkwyBAQDZgvuTDIEBALGDI5N1gQYARoT7kwyB
    AQA8g5SRPYMGANaC6pGkgwYAdYOnknODAQCmg+2R2oIGADSEeZLYggYANIPqkjSDBgCWhOCSMYMG
    AEaEQpOPgwYAn3+zj0aEAQCff/qOAIUBAAiA0o8ohAYAn39nkACFAQCffyGRRoQBAAiAP5EohAYA
    CIDbjh6FBgCff7OPs4UBAAiA0o+VhQYACIBJkB6FBgAIgD+RlYUGAJ9/IZGzhQEA1oLBj1aEBgDL
    hFKPx4MGANCD9I/QgwEAroS7j+eDAQDHg1KPy4QGAOeDu4+uhAEA1IL5kCGEBgA9gxaRQYQBAEaD
    V49OhQYA2oLCj8CFBgDDhE6POoUGAMeDUY82hgYApYS4j1iFAQDlg7qPGYYBANSCQpDYhAYAPYNg
    kPaEAQA6gx+RtoUBANCCPpHUhQYAn3+OkkaEAQAIgKySKIQGAJ9/1JEAhQEAn3/7k0aEAQCff0GT
    AIUBAAiAtpEehQYACICskpWFBgCff46Ss4UBAAiAI5MehQYAn3/7k7OFAQA7g9iRAIUBANSCZ5Ij
    hAYAM4Ogk+uDBgBxg12TLoQBAD6DgpJEhAEAOoNBkwOFAQAJhAGT1YMBAKGEnpPpgwYADoS3k4qE
    AQDRgvaRHoUGANGCbZKVhQYA0YJikx+FBgA7g4uSs4UBAAGF+o4NgQEAH4XcjneBBgC0hbOPDIEB
    AJWF0o91gQYAbYb6jgyBAQCLhtuOdYEGAAOH0o91gQYAAIVnkAyBAQAehUmQdYEGALOFIZEMgQEA
    lYU/kXWBBgBthmeQDIEBAIuGSZB1gQYAA4c/kXWBBgDBhcKP24IGAE6FV49GgwYAMIfEj96CBgC7
    hlePR4MGANiEQpDUggYA1IU9kdCCBgD2hGCQPYMBALaFH5E6gwEARIZDkNaCBgBHh0aR1YIGAGOG
    Y5A/gwEAJ4cpkT6DAQDah/qODIEBACGHs48MgQEA+YfbjnWBBgBIifqODIEBAI6Is48MgQEAZonb
    jnWBBgBwiNKPdYEGANqHZ5AMgQEA+YdJkHWBBgAhhyGRDIEBAEiJZ5AMgQEAZolJkHWBBgCOiCGR
    DIEBAHCIP5F1gQYAJohSj0SDBgDEh1KQ24IGACyIqpA+gwYA6IfnkIKDAQCPiFKQpoMGAB6FtpF1
    gQYAAIXUkQyBAQCzhY6SDIEBAJWFrJJ1gQYAi4a2kXWBBgBthtSRDIEBAAOHrJJ1gQYAHoUjk3WB
    BgAAhUGTDIEBALOF+5MMgQEAi4Yjk3WBBgBthkGTDIEBACSF+5HTggYAo4V7ktSCBgAIhduRPYMB
    ANOEnpJ3gwEAS4a0kdGCBgAoh46S2YIGAGSGy5E9gwEAQIadknWDAQDshk2SH4MBALSFQZOOgwYA
    BIbgkjCDBgAwhzqTjYMGAPmHtpF1gQYA2ofUkQyBAQAhh46SDIEBAGaJtpF1gQYASInUkQyBAQCO
    iI6SDIEBAHCIrJJ1gQYA+Ycjk3WBBgDah0GTDIEBACGH+5MMgQEAZokjk3WBBgBIiUGTDIEBAI6I
    +5MMgQEAx4fFkdaCBgAbiDWSN4MGAI6IyJGigwYAk4fTkjSDBgCUiDSToIMGABmGu4/ngwEAOoVO
    j8OEBgBYhbiPpYQBADiGUo/HgwYAp4ZOj8OEBgDGhriPpIQBADqFTo8vhgYAEoa4j1iFAQBZhbiP
    EYYBADCGTo86hQYAp4ZNjy+GBgDGhraPEIYBAKWHUI/GgwYAh4e6j+ODAQAjiFePr4QGAIyIxI87
    hAYALIhhkAeFAQAriCiRRYQBAJOIRpEjhAYAo4dRjzKFBgA6iFyPA4YGAIOHu49QhQEAlojDj6OF
    BgAviCCRs4UBAJaIQ5AlhQYAmYg+kZWFBgB1hQCT04MBAN2EWpMuhAEAe4W2k4mEAQDzhvaS0YMB
    AA6GnZPpgwYATIZZkyuEAQDphrWTiYQBAC2IlJI+hAEAL4jUkQCFAQCXiLOSIYQGAICHnZPqgwYA
    wodeky6EAQCZiLWRHoUGAJuIbZLUhQYAL4hKk/eEAQAxiIuStoUBAC2IApSuhQEAmIhpk9iEBgAI
    gJSKi4YGAJ5/sopthgEACoAdigGHBgCefx+MbYYBAAiAAYyLhgYAoX9tiyKHAQAKgIqLAYcGAF6A
    Wop5hwYA1oAcis6HBgAbgJqKvIcBACeCAYrYhwYATIGTitCHBgBlga2KPIgBANaAiovOhwYAHIAI
    jLyHAQBegMiLeYcGALWAbIs3iAEALoJvi9GHBgBMgQCM0IcGAPaBMYseiAEAZoEZjDyIAQDSgtKK
    iYYGADuDs4pphgEA2oIAiiSHBgAfgz6KZYcBADqDHYxthgEA0YI/jIqGBgDVgkuL+4YGAD+DaYsZ
    hwEAhIIQi3SHBgDMgtiKt4cBAGmCQ4oZiAEAzYI/jLSHAQBygq+LEIgBAAiAbo2LhgYAoX/ajCKH
    AQAKgPiMAYcGAJ5/jI1thgEAoX9HjiKHAQAKgGWOAYcGANeA94zOhwYAHIB1jb2HAQBfgDWNeocG
    ALaA2ow4iAEALoLbjNGHBgBOgW6N0IcGAPWBnoweiAEAXoCijnmHBgDWgGSOzocGALWARo43iAEA
    QoJnjtGHBgBrgYyNOogBACSCSI47iAEAdIPzjE+GAQDTgreM/YYGAD2D0owehwEADoRMja6GAQBJ
    hJCNaoYGADSD643GhgYAcYOojQqHAQChhOuNxoYGAAyEA45lhwEASYRGjiGHBgCEgnuMdYcGAHOC
    G40RiAEAf4LwjX6HBgDEgrONwYcBAGqDX47DhwEALoOhjn2HBgCfhKOOfIcGAAyEtI4iiAEAL4iy
    im6GAQCZiJSKjIYGAJyIHooChwYAK4gXjHWGAQAyiGyLI4cBAJiIAIyMhgYAm4iKiwKHBgDviFuK
    eocGAGaJHYrOhwYArIibir2HAQBmiYqLzocGAO6IyIt6hwYArIgIjL2HAQBFiWyLN4gBAN6E8IxT
    hgEAt4WQjWuGBgB7hUyNr4YBAEuG8YxThgEAJIeQjWqGBgDohkyNr4YBAN6Ep40KhwEAe4UFjmeH
    AQC3hUmOI4cGAA+G7I3HhgYAS4apjQuHAQDrhgOOaIcBACeHRo4khwYA3YRgjr+HAQCChdGOKYgB
    AEeGZY7FhwEADIaojn6HBgDghs6OFIgBALqH84xThgEALIjgjBiHAQCUiICNeYYGAJWI/oz3hgYA
    fYfrjcaGBgC8h6aNB4cBAFKIBo5lhwEAkohGjiGHBgBkifeMzIcGAOuIM411hwYAqYhujbyHAQBC
    idqMNIgBAMKHYo7MhwEAhYefjoKHBgCDiAuPKogBAGaJZI7QhwYAR4lFjjmIAQCef/mObYYBAAiA
    3I6LhgYAoX+1jyGHAQAKgNKPAYcGAAiASZCLhgYAnn9nkG2GAQChfyKRIYcBAAqAP5EBhwYAHIDi
    jryHAQBegA+QeYcGANaA0Y/NhwYAtYC0jzaIAQBMgdqO0IcGACiCto/XhwYAZYHzjj2IAQDsgXqP
    I4gBABuAT5C8hwEA1oA/kc6HBgC1gCGRNogBAEyBR5DQhwYAJ4IikdiHBgBkgWCQPIgBAOuB5ZAh
    iAEASINQj7WGBgDigqyPFocGACWD8I9UhwEAxIROj6aGBgCnhLiPwYYBABiEqI9XhwEA1YJCkEKG
    BgBAg16QXIYBACKD5JDmhgEA2oIikSOHBgAeg2KRZIcBALeC3Y7RhwYA14L6jjqIAQBsgvaPGIgB
    AOKDUo+KhwYARYT5jtyHBgCbg4KP1YcBAIOEOY8iiAEAxYKLkL+HAQB/gseQfYcGAGiCY5EaiAEA
    CIC2kYuGBgCef9SRbYYBAKF/j5IhhwEACoCtkgGHBgAIgCSTi4YGAJ5/QZNthgEAoX/8kyKHAQAb
    gL2RvIcBAF6AfZF5hwYA1oCsks6HBgC1gI6SN4gBAEyBtZHQhwYAJ4KRktiHBgBkgc6RPIgBAOuB
    VJIjiAEAG4Aqk7yHAQBegOqSeYcGALWA+5M3iAEATIEik9CHBgBlgTyTPIgBAPaBwZMeiAEA0IK0
    kUqGBgA8g82RY4YBACKDUpLmhgEA2oKPkiSHBgDSgmKTiYYGADuDQ5NphgEAH4POkmWHAQDEgvqR
    wocBAH+CNJJ9hwYAzIJok7eHAQCEgqCTdIcGAGmC05IZiAEAF4a5j7+GAQCIhamPQYcBADGGTY+l
    hgYAUoVbj3+HBgC4hQuP14cGAA+Fmo/ChwEA/oVUjwyIAQDohk+PWYcGACqHA4/RhwYAy4a5j3WH
    AQBdh0yP5oYGAHeHt4/KhgEA9oegjz+GAQCTiMiPBocGAC2IZ5BwhgEAS4hZkfKGAQBXiN6QcYcB
    AJaIRpCOhgYAl4gckSyHBgA6iGmPZocGAPuHro+nhwEAZodJjxOIAQCriCOPwocGAOqICpB2hwYA
    I4mSj8iHBgA8ia+PNIgBAKqIR5C+hwEAaok/kdGHBgD8iWiQOIgBAEuJIZE6iAEAL4jdkWSGAQAy
    iJCSI4cBAJuI95FLhgYAnIitkgKHBgAviEGTboYBADKI+5MjhwEAmYgkk4yGBgDyiH2RgYcGALKI
    vpHGhwEAZomsks6HBgBGiY+SN4gBAO+I6pJ6hwYArIgqk72HAQBFifuTN4gBAN2JHYp3gQYAtYqy
    igyBAQDTipSKdYEGAEqLHYp1gQYAIoyyigyBAQBAjJSKdYEGAPuJbIsMgQEA3YmKi3WBBgC1ih+M
    DIEBANOKAYx1gQYAaYtsiwyBAQBKi4qLdYEGACKMH4wMgQEAQIwBjHWBBgDDi1qKNIMGAASMF4pz
    gwEAuIwdinWBBgCQjbKKDIEBAK6NlIp1gQYAJY4dinWBBgD9jrKKDIEBALiMiot1gQYA1oxsiwyB
    AQCQjR+MDIEBAK6NAYx1gQYAQ45siwyBAQAljoqLdYEGAP2OH4wMgQEAw4zpidiCBgAljVCKMYMG
    AGKND4p3gwEA1oyyio+DBgAyjuuJ1IIGAJOOUIowgwYAQ46yio6DBgD7idmMDIEBAN2J94x1gQYA
    04pujXWBBgBpi9mMDIEBAEqL94x1gQYAQIxujXWBBgD7iUaODIEBALWKjI0MgQEA3YlkjnWBBgBp
    i0aODIEBACKMjI0MgQEASotkjnWBBgC4jPeMdYEGANaM2YwMgQEAro1ujXWBBgBDjtmMDIEBACWO
    94x1gQYAkI2MjQyBAQDWjEaODIEBALiMZI51gQYA/Y6MjQyBAQBDjkaODIEBACWOZI51gQYAw4sQ
    i+uDBgAAjM6KLoQBAGSL14kjhAYAzYvyiUSEAQDKi7GKA4UBAAOMhovihAEAw4vIi6GEBgBhi9KK
    H4UGAGGL3YmVhQYAyov7ibOFAQBhi0mLloUGAMqLZYu3hQEAAYw7jJuFAQCZjHKK1YMBADCND4vp
    gwYAbI3Lii6EAQAFjnCK04MBAJ6ODovpgwYAnYwni4qEAQDZjGuLRYQGAG2NgovlhAEAMY3Hi6GE
    BgAKjieLiYQBAEeOa4tFhAYAno7Gi6GEBgDZjCKM/IQGAJ2M3otBhQEAbY05jJyFAQAKjt6LQYUB
    AEaOIoz8hAYAw4t+jFiFBgDDizWNDoYGADGNfoxYhQYA2YzZjLOFBgCdjJWM94UBADGNNI0PhgYA
    no5+jFiFBgAKjpWM+IUBAEaO2YyzhQYAno41jQ+GBgCSjx2KdYEGABuPlIp1gQYA/5AdinWBBgBq
    kLKKDIEBAIiQlIp1gQYAsI9siwyBAQCSj4qLdYEGABuPAYx1gQYAHpFsiwyBAQD/kIqLdYEGAGqQ
    H4wMgQEAiJABjHWBBgC4j/+J2YIGAM+ODop1gwEAI5BEijSDBgC/j6qKjYMGACSRpYqggwYAbJId
    iniBBgDXkbGKDIEBAPWRlIp2gQYAJ5OaioqBAQDkklqKzIEGADmTHYpFggYAbJKKi3iBBgDXkR+M
    DIEBAPWRAYx2gQYAjJJtiw+BAQAnkwiMioEBADmTiotFggYAopNtiySCAQDkksiLzIEGADuTlIq7
    ggYAO5MdirGDBgClk7GK2YIBADuTAYy7ggYAO5OKi7GDBgCkk2yLk4MBAKWTH4zZggEAsI/ZjAyB
    AQCSj/eMdYEGABuPbo11gQYAHpHZjAyBAQD/kPeMdYEGAIiQbo11gQYAsI9GjgyBAQCSj2SOdYEG
    AGqQjI0MgQEAHpFGjgyBAQD/kGSOdYEGAGyS+Ix4gQYA9ZFujXaBBgCMktqMD4EBACeTdY2KgQEA
    OZP4jEWCBgCik9qMJIIBAOSSNY3MgQYA15GMjQyBAQBskmWOeIEGAIySR44PgQEAopNHjiSCAQDk
    kqKOzIEGADmTZY5FggYAO5NujbuCBgA7k/eMsYMGAKST2YyTgwEApZOMjdmCAQCkk0aOk4MBADuT
    ZI6xgwYAgo9nitGDAQDbjsmKK4QBABCQDYvqgwYAUpDPii6EAQAmkSOKIYQGAHmPJYuJhAEA246C
    i+WEAQC1j2qLRIQGAA2QxoughAYATZCEi+OEAQAkkVuLVoQGAMGQ/Im2hQEAvpC7iveEAQAnkdqK
    2IQGACqR3YnUhQYAeI/di0CFAQC0jyKM/IQGANuOOoychQEAI5ESjA2FBgAlkZGLj4UGALyQcouu
    hQEASpA5jJmFAQA7k5SKKIQGAKSTsopGhAEApJNsiwCFAQA7kwGMKIQGAKSTH4xGhAEAO5Mdih6F
    BgA7k5SKlYUGAKSTsoqzhQEAO5OKix6FBgA7kwGMlYUGAKSTH4yzhQEADJB9jFeFBgB4j5SM+IUB
    ALSP2YyzhQYADJA1jQ+GBgAikdqMsoUGAOGQmozzhQEApJPZjACFAQA7k26NKIQGAKSTjI1GhAEA
    pJNGjgCFAQA7k/eMHoUGADuTbo2VhQYAO5Nkjh6FBgCkk4yNs4UBAPuJs48MgQEAtYr6jgyBAQDT
    ituOdYEGAN2J0o91gQYAaYuzjwyBAQAijPqODIEBAECM2451gQYASovSj3WBBgC1imeQDIEBANOK
    SZB1gQYA+4khkQyBAQDdiT+RdYEGACKMZ5AMgQEAQIxJkHWBBgBpiyGRDIEBAEqLP5F1gQYAH4yx
    j5CDBgAvjHeQ1oIGAGaLd5CggwYAD4xXkYGDAQCQjfqODIEBANaMs48MgQEAro3bjnWBBgC4jNKP
    dYEGAP2O+o4MgQEAQ46zjwyBAQAljtKPdYEGAJCNZ5AMgQEAro1JkHWBBgC4jD+RdYEGANaMIZEM
    gQEA/Y5nkAyBAQBDjiGRDIEBACWOP5F1gQYA5ozBj9aCBgBQjsKP24IGAN6NV49GgwYAaI1CkNSC
    BgCxjPmQ1IIGANGMFpE9gwEAZI49kdCCBgCGjWCQPYMBAEWOH5E6gwEA04q2kXWBBgD7iY6SDIEB
    AN2JrJJ1gQYAtYrUkQyBAQBAjLaRdYEGAGmLjpIMgQEASousknWBBgAijNSRDIEBANOKI5N1gQYA
    +4n7kwyBAQC1ikGTDIEBAECMI5N1gQYAaYv7kwyBAQAijEGTDIEBADWM7ZHaggYAZovqkaSDBgDM
    i5SRPYMGAASMp5JzgwEAw4vqkjSDBgCujbaRdYEGALiMrJJ1gQYAkI3UkQyBAQDWjI6SDIEBAP2O
    1JEMgQEAQ46OkgyBAQAljqySdYEGAK6NI5N1gQYAkI1BkwyBAQDWjPuTDIEBAP2OQZMMgQEAQ477
    kwyBAQC0jfuR04IGAMOMeZLYggYAl43bkT2DAQBijZ6Sd4MBADKOe5LUggYA1oxCk4+DBgAljeCS
    MYMGAJOO4JIwgwYAQ45Bk46DBgBmi8GPVoQGAGOL+ZAhhAYAzYsWkUGEAQDWi1ePToUGAGqLwo/A
    hQYAY4tCkNiEBgDNi2CQ9oQBAMmLH5G2hQEAYIs+kdSFBgBbjVKPx4MGAGCM9I/QgwEAPo27j+eD
    AQBWjFKPy4QGAHaMu4+uhAEAx45Sj8eDBgCpjruP54MBAMqNTo/DhAYA6I24j6WEAQBSjU6POoUG
    AFeMUY82hgYAdYy6jxmGAQA0jbiPWIUBAMCOTo86hQYAyo1Ojy+GBgDojbiPEYYBAKKOuI9YhQEA
    yovYkQCFAQBki2eSI4QGAMOLoJPrgwYAAIxdky6EAQDNi4KSRIQBAMqLQZMDhQEAYYv2kR6FBgBh
    i22SlYUGAGGLYpMfhQYAyouLkrOFAQCZjAGT1YMBADCNnpPpgwYAbI1aky6EAQCdjLeTioQBAAWO
    AJPTgwEAno6dk+mDBgAKjraTiYQBABuP2451gQYAsI+zjwyBAQCSj9KPdYEGAGqQ+o4MgQEAiJDb
    jnWBBgAekbOPDIEBAP+Q0o91gQYAG49JkHWBBgCwjyGRDIEBAJKPP5F1gQYAapBnkAyBAQCIkEmQ
    dYEGAB6RIZEMgQEA/5A/kXWBBgC/j8SP3oIGAEuPV49HgwYAtZBSj0SDBgDUjkOQ1oIGANePRpHV
    ggYA845jkD+DAQC2jymRPoMBAFOQUpDbggYAHpFSkKaDBgB4kOeQgoMBALuQqpA+gwYA15H5jgyB
    AQD1kdyOdoEGAGyS0o94gQYAjJK1jw+BAQAnk+KOioEBAKKTtY8kggEA5JIPkMyBBgA5k9KPRYIG
    ANeRZ5AMgQEA9ZFJkHaBBgBskj+ReIEGACeTT5CKgQEAjJIikQ+BAQA5kz+RRYIGAKKTIpEkggEA
    O5PcjruCBgClk/mO2YIBAKSTs4+TgwEAO5PSj7GDBgA7k0mQu4IGAKWTZ5DZggEAO5M/kbGDBgCk
    kyGRk4MBABuPtpF1gQYAsI+OkgyBAQCSj6ySdYEGAIiQtpF1gQYAapDUkQyBAQAekY6SDIEBAP+Q
    rJJ1gQYAG48jk3WBBgCwj/uTDIEBAIiQI5N1gQYAapBBkwyBAQAekfuTDIEBANqOtJHRggYAuI+O
    ktmCBgDzjsuRPYMBAHyPTZIfgwEAz46dknWDAQBWkMWR1oIGAB6RyJGigwYAqpA1kjeDBgAjkNOS
    NIMGAL+POpONgwYAJJE0k6CDBgD1kbaRdoEGANeR1JEMgQEAbJKtkniBBgAnk72RioEBAIySj5IP
    gQEA5JJ9kcyBBgA5k62SRYIGAKKTj5IkggEA9ZEjk3aBBgDXkUGTDIEBACeTKpOKgQEAjJL8kw+B
    AQDkkuqSzIEGAKKT/JMkggEAO5O2kbuCBgA7k6ySsYMGAKWT1JHZggEApJOOkpODAQA7kyOTu4IG
    AKWTQZPZggEApJP7k5ODAQA0kFCPxoMGABaQuo/jgwEAN49Oj8OEBgBVj7iPpIQBALOQV4+vhAYA
    G5HEjzuEBgC7kGGQB4UBALuQKJFFhAEAI5FGkSOEBgAykFGPMoUGADePTY8vhgYAEpC7j1CFAQBV
    j7aPEIYBAMqQXI8DhgYAJZHDj6OFBgAlkUOQJYUGACmRPpGVhQYAv5AgkbOFAQA7k9uOKIQGAKST
    +o5GhAEApJOzjwCFAQA7k0mQKIQGAKSTZ5BGhAEApJMhkQCFAQA7k9KPHoUGADuT246VhQYApJP6
    jrOFAQA7kz+RHoUGADuTSZCVhQYApJNnkLOFAQC9kJSSPoQBACaRs5IhhAYAv5DUkQCFAQCCj/aS
    0YMBANuOWZMrhAEAEJCdk+qDBgB5j7WTiYQBAFKQXpMuhAEAKZG1kR6FBgAqkW2S1IUGAL6QSpP3
    hAEAJ5Fpk9iEBgDBkIuStoUBALyQApSuhQEAO5O2kSiEBgCkk9SRRoQBAKSTjpIAhQEAO5MjkyiE
    BgCkk0GTRoQBAKST+5MAhQEAO5Oskh6FBgA7k7aRlYUGAKST1JGzhQEAO5Mjk5WFBgCkk0GTs4UB
    AGKL0oqJhgYAy4uzimmGAQBpi/+JJYcGAK6LPYpmhwEAYYs/jIqGBgDKix2MbYYBAGWLS4v7hgYA
    z4tpixmHAQC2igGK2YcGANyJk4rQhwYAE4sQi3SHBgD4ikSKGYgBAPWJrYo8iAEAXIvYireHAQC9
    im+L0YcGANyJAIzQhwYAhYoxix6IAQACi7CLEIgBAPaJGow8iAEAXYs/jLSHAQAEjPOMT4YBAGOL
    t4z9hgYAzIvSjB6HAQDDi+uNxoYGAAGMqI0KhwEAE4t7jHWHBgC9ituM0YcGANyJbY3QhwYAhYqe
    jB6IAQACixuNEYgBAA+L8I1+hwYA0YpnjtGHBgD5iYqNOogBALOKSI47iAEAU4uzjcGHAQD6i1+O
    w4cBAL6LoY59hwYAbY3wjFOGAQDZjJCNaoYGAJ2MTI2uhgEACo5Mja+GAQBGjpCNa4YGADGN643G
    hgYAnIwDjmWHAQBtjaeNCocBANiMR44hhwYAno7sjceGBgAKjgWOZ4cBAEaOSY4jhwYAbY1gjr+H
    AQAujaOOfIcGAJuMtI4iiAEAnI6ojn6HBgARjtGOKYgBACmRlIqMhgYAv5Cyim6GAQArkR6KAocG
    ALuQF4x1hgEAKJH/i42GBgDBkGyLJIcBACqRiosDhwYAPJGbir2HAQA7kQiMvYcBADuTHIqLhgYA
    OZOTigGHBgCik7GKIocBADuTiouLhgYApZNsi22GAQA5kwCMAYcGAKKTHowihwEAf5FbinuHBgD3
    kR2Kz4cGAG2SlIrOhwYAKJMWiryHAQDlklaKeYcGAI2SsYo3iAEA9pGKi86HBgB+kciLeocGAGyS
    AYzOhwYA1pFtiziIAQAnk4OLvIcBAOWSw4t6hwYAjZIejDiIAQDbjvGMU4YBAHiPTI2vhgEAtI+Q
    jWqGBgBKkPOMU4YBACORgI15hgYAu5DgjBeHAQAkkf6M9oYGAA2Q643GhgYA246pjQuHAQB7jwOO
    aIcBALePRo4khwYAS5CmjQeHAQDikAaOZYcBACGRRo4hhwYAOJFujbyHAQDXjmWOxYcBABSQn46C
    hwYAb4/OjhSIAQBSkGKOzIcBABGRCo8piAEAO5P3jIuGBgClk9mMbYYBADiTbo0ChwYApZNGjm2G
    AQA7k2SOi4YGAKKTi40ihwEA85H3jMuHBgB6kTSNdYcGAGqSbY3OhwYA0ZHajDSIAQAmk/GMvYcB
    AOSSMY16hwYA9pFkjtCHBgDYkUeOOogBACeTXY68hwEA5ZKdjnmHBgCJkomNOIgBANeLUI+1hgYA
    cousjxeHBgC0i/CPVIcBAGWLQpBDhgYA0ItfkF2GAQCui+SQ74YBAGSLIpEqhwYApYtikW6HAQDc
    idqO0IcGALeKtY/XhwYA9YnzjjyIAQB6inqPIYgBAPuK9I8aiAEARovdjtGHBgAqjIKP1YcBAGaL
    +o46iAEAG4qHkM+HBgAHi8SQgIcGAI+K/5DRhwYArYodkTuIAQBLi4uQx4cBAFONTo+mhgYAp4yo
    j1eHAQA3jbiPwYYBAMCOTY+lhgYAGI6pj0GHAQCnjrmPv4YBAHGMUo+KhwYA1Yz5jtyHBgATjTqP
    IogBAOKNW49/hwYASI4Lj9eHBgCejZqPwocBAI2OVI8MiAEAYIu0kUqGBgDMi8yRY4YBALGLUJLo
    hgEAaYuOkiWHBgBii2KTiYYGAMuLQ5NphgEArovNkmaHAQDdibaR0IcGAA2LM5J/hwYAtoqRktmH
    BgD3idCRPIgBAHuKVZIliAEATYv2kcWHAQDciSKT0IcGABOLoJN0hwYA+IrTkhmIAQD1iT2TPIgB
    AIWKwZMeiAEAXItok7eHAQDtj0yP5oYGAIaQoI8/hgEAB5C3j8qGAQAjkciPBocGACWRRpCOhgYA
    vZBnkHCGAQDckFqR9YYBAOeQ3pBzhwEAKJEckS2HBgB4j0+PWYcGALqPA4/RhwYAWo+5j3WHAQD2
    j0mPE4gBAMmQaY9mhwYAOpEij8GHBgCKkK6Pp4cBADmRRpC+hwEApJOxj2mGAQA8k9CPiIYGADmT
    244BhwYAopP4jiGHAQA7kz+RioYGAKSTIZFshgEAPpNIkPuGBgCok2aQGYcBAGyS2o7NhwYAeZEK
    kHaHBgCykZCPyIcGAMeRq481iAEAMpPKj7SHAQDukguQdIcGAI2S+I42iAEAmJJrkNCHBgD9kUCR
    04cGAF+SLZAciAEA4JEjkT2IAQAvk0GRuYcBAN2SqpAQiAEAKpH3kUuGBgC+kN2RZIYBAMKQkJIj
    hwEAK5GtkgKHBgApkSSTjIYGAL+QQZNuhgEAwZD7kySHAQBEkb6RyIcBADyRKpO9hwEAO5OskouG
    BgClk46SbYYBADqTtpH/hgYAo5PUkR+HAQClk/yTbYYBADmTI5MBhwYAopNAkyKHAQCEkX2Rg4cG
    AHGSuJHOhwYA95Gtks+HBgDXkZCSOIgBAOeSepF3hwYAKJOmkryHAQCTktaRNogBAH+R6pJ7hwYA
    bZIjk86HBgDWkf2TOIgBAOWS5ZJ5hwYAjZJAkzeIAQAcgBOUioEBALeArpQPgQEA14CQlHiBBgBf
    gFOUzIEGAKF/rpQkggEACoCQlEWCBgBOgRmUdoEGACWCr5QMgQEARIKRlHWBBgAcgICVioEBALeA
    G5YPgQEA14D9lXiBBgBfgMCVzIEGAKF/G5YkggEACoD9lUWCBgBOgYaVdoEGAGyBaZUMgQEAJYIc
    lgyBAQBEgv6VdYEGAAiAGZS7ggYACICRlLGDBgCff6+Uk4MBAAiAhpW7ggYAnn9pldmCAQAIgP6V
    sYMGAJ9/HJaTgwEAu4IZlHWBBgCTg6+UDIEBACiEGZR1gQYAsYORlHWBBgDZgmiVDIEBALuCh5V1
    gQYAk4MclgyBAQBGhGiVDIEBACiEh5V1gQYAsYP+lXWBBgAcgO2WioEBANiAaZd6gQYADYBpl0aC
    BgBfgCyXzIEGAE6B85Z2gQYAa4HWlgyBAQBEgmqXeIEGALiAiZcSgQEApH+JlyWCAQDYgDSYRoIG
    ALiAnZglggEAVYElmIqBAQAngouXD4EBABWB4pfMgQYARII3mEWCBgAngqCYJIIBAAmA85a8ggYA
    nn/WltiCAQAKgGqXsYMGAByAJZjCggEAX4Dil4KCBgChf4uXlIMBANeAN5ixgwYAt4CgmJSDAQBO
    gTmYvIIGAESCOZixgwYAa4GjmNiCAQAlgqOYk4MBANmC1pYMgQEAu4LzlnaBBgBGhNaWDIEBACiE
    85Z2gQYAsYNql3iBBgDBgiWYioEBAJSDi5cPgQEAgYLil8yBBgCUg6CYJIIBAC+EJZiKgQEA74Pi
    l8yBBgCxgzeYRYIGALuCOZi7ggYA2YKjmNmCAQCTg6OYk4MBACiEOZi7ggYAsYM5mLGDBgBGhKOY
    2YIBAAiAGZQohAYAn3+vlACFAQCff2iVRoQBAAiAh5UohAYAn38clgCFAQAIgJGUHoUGAAiAGZSV
    hQYACID+lR6FBgAIgIeVlYUGAJ9/aJWzhQEAdIMWlOKEAQA0g1eUoYQGAEqE+5NFhAYAooRWlKGE
    BgAzgw2VWIUGANGC2ZOWhQYAOoP0k7eFAQByg8qUm4UBAA6EbpRBhQEASYSylP2EBgCihA2VWIUG
    AA6EJJX4hQEANIPFlQ6GBgBJhGmVs4UGAKKExJUPhgYAnn/WlkaEAQAIgPOWKIQGAByAJZgvhAEA
    X4Dil++DBgChf4uXAYUBALeAoJgBhQEAToE5mCiEBgBsgaOYRoQBACWCo5gAhQEACoBqlx+FBgAI
    gPOWlYUGAJ5/1pazhQEA14A3mB+FBgBfgOKXXIUGAByAJZichQEARII5mB6FBgBOgTmYlYUGAGyB
    o5izhQEAu4I5mCiEBgDZgqOYRoQBAJODo5gAhQEAKIQ5mCiEBgBGhKOYRoQBALuCOZiVhQYA2YKj
    mLOFAQCxgzmYHoUGACiEOZiVhQYARoSjmLOFAQCVhRmUdYEGAACFr5QMgQEAHoWRlHWBBgADhxmU
    dYEGAG2Gr5QMgQEAi4aRlHWBBgCzhWiVDIEBAJWFh5V1gQYAAIUclgyBAQAehf6VdYEGAAOHh5V1
    gQYAbYYclgyBAQCLhv6VdYEGANqHr5QMgQEA+YeRlHWBBgBwiBmUdYEGAEiJr5QMgQEAZomRlHWB
    BgAhh2iVDIEBANqHHJYMgQEA+Yf+lXWBBgCOiGiVDIEBAHCIh5V1gQYASIkclgyBAQBmif6VdYEG
    ALOF1pYMgQEAlYXzlnaBBgAfhWqXeIEGAAOH85Z2gQYAjIZql3iBBgABhYuXD4EBAJyFJZiKgQEA
    XIXil8yBBgAfhTeYRYIGAAGFoJgkggEAboaLlw+BAQAJhyWYioEBAIyGN5hFggYAyYbil8yBBgBu
    hqCYJIIBAJWFOZi7ggYAHoU5mLGDBgAAhaOYk4MBALOFo5jZggEAA4c5mLuCBgCLhjmYsYMGAG2G
    o5iTgwEAIIfWlgyBAQD5h2qXeIEGAI6I1pYMgQEAcIjzlnaBBgBmiWqXeIEGANyHi5cPgQEAdogl
    mIqBAQD5hzeYRYIGADaI4pfMgQYA3IegmCSCAQBJiYuXD4EBAKSJ4pfMgQYAZok3mEWCBgBJiaCY
    JIIBAPmHOZixgwYAIIejmNmCAQDah6OYk4MBAHCIOZi7ggYAZok5mLGDBgCOiKOY2YIBAEiJo5iT
    gwEA3oQSlOWEAQC3hfqTRYQGAEuGEpTlhAEAD4ZWlKGEBgAlh/mTRIQGAHuFbZRBhQEAt4WylPyE
    BgDehMmUnIUBAHuFJZX4hQEA6YZtlECFAQAPhg2VWIUGACSHsZT8hAYAS4bJlJyFAQDphiSV+IUB
    ALeFaZWzhQYAD4bElQ+GBgAlh2iVs4UGAL2HFJTjhAEAfYdWlKCEBgCUiOuTVoQGAH2HDZVYhQYA
    u4fIlJmFAQBRiCmV84UBAJSIopQNhQYAloghlI+FBgB8h8WVD4YGAJKIapWyhQYAlYU5mCiEBgAA
    haOYAIUBALOFo5hGhAEAA4c5mCiEBgBthqOYAIUBAB6FOZgehQYAlYU5mJWFBgCzhaOYs4UBAIuG
    OZgehQYAA4c5mJWFBgAhh6OYRoQBANqHo5gAhQEAcIg5mCiEBgCOiKOYRoQBAEiJo5gAhQEA+Yc5
    mB6FBgAhh6OYs4UBAGaJOZgehQYAcIg5mJWFBgCOiKOYs4UBAAiAkZSLhgYAnn+vlG2GAQAKgBqU
    AYcGAAiA/pWLhgYAnn8clm2GAQChf2qVIocBAAqAh5UBhwYAXoBXlHmHBgDWgBmUzocGAByAl5S8
    hwEALoL+k9GHBgBMgY+U0IcGAGaBqZQ8iAEA9YEtlR6IAQBfgMSVeocGANeAh5XOhwYAHIAElr2H
    AQC2gGqVOIgBAC6CapXRhwYAToH+ldCHBgBrgRuWOogBADqDrZRthgEA0YLOlIqGBgDVgtqT+4YG
    AD+D+ZMZhwEAdIODlU+GAQDTgkaV/YYGAD2DYZUehwEAcYM4lgqHAQAOhNyVr4YBAEqEIJZrhgYA
    zYLPlLSHAQCEgguVdYcGAHKCP5QQiAEAxIJDlsGHAQBzgquVEIgBAAuAapeLhgYAoX/XliKHAQAL
    gPSWAocGAKF/ipduhgEA14A3mIuGBgBfgOKXyYYGALeAoJhuhgEAHIAmmAiHAQBDgjmYioYGACWC
    o5hshgEAToE3mAGHBgBrgaCYIYcBANeA9JbOhwYAHIBwl72HAQBfgDGXeocGALeA15Y4iAEAQoL4
    ltGHBgBOgWqXzocGACWC2ZY7iAEA0YAmmL2HAQAQgeOXeocGAGqBipc4iAEANIN6lsaGBgChhHyW
    x4YGAA2ElZZnhwEASYTYliOHBgCPg6OYaIYBALqCOJgAhwYA14KhmCCHAQCvgzqYiIYGACeEPZj6
    hgYARYSnmBeHAQB/gn+WfocGAGuD8ZbGhwEAL4Mxl36HBgC2gm6XzocGAJ+EN5d/hwYARoScl9GH
    BgAIhGKXHYgBAHuC5Zd5hwYAOYIpmLqHAQDUgpCXN4gBAOeD75dzhwYApYM0mLGHAQCFhOKXEYgB
    AN6EgJVThgEAt4UglmuGBgB7hdyVr4YBAN6EOJYLhwEAS4aAlVOGAQAkhyCWa4YGAOiG3JWvhgEA
    S4Y4lguHAQAriKeUdYYBAJiIj5SMhgYAm4gZlAKHBgC6h4OVVIYBACyIcJUXhwEAuoc3lgmHAQCU
    iA+WeYYGAJWIjpX3hgYA7ohXlHqHBgBmiRmUzocGAKyIl5S9hwEA64jDlXWHBgBkiYeVzIcGAKmI
    /pW8hwEAQolplTSIAQB6hZWWaIcBALeF2JYjhwYAD4Z8lseGBgDohpWWZ4cBACSH2JYjhwYAHIU6
    mIeGBgD9hKOYZ4YBAJWFPpj5hgYAs4WomBWHAQCKhjqYh4YGAGqGo5hnhgEAAoc+mPmGBgDZhPeW
    yIcBALSFnZfRhwYAdoVklx2IAQBHhveWyIcBAA2GOJd/hwYAIoedl9CHBgDkhmSXHYgBAFaF8Jdx
    hwYAGYU6mK6HAQD0heOXEIgBAIaGOpiuhwEAxIbwl3GHBgB8h3yWxoYGAFKIlpZlhwEAkojWliGH
    BgD3hzqYiIYGANiHo5hohgEAIYeomBWHAQBmiTmYioYGAEiJo5hshgEAcIg8mPqGBgCOiKaYGIcB
    ALOH95bIhwEAeoc3l36HBgBTiFmXGogBAGaJ9JbQhwYAkoiUl9GHBgBJidaWOogBADSI7JdzhwYA
    +Ic2mLKHAQBhh+OXD4gBAKGJ45d4hwYAaIkrmLuHAQDQiNiXE4gBAN2JGZR1gQYAtYqvlAyBAQDT
    ipGUdYEGAEqLGZR1gQYAIoyvlAyBAQBAjJGUdYEGAPuJaJUMgQEA3YmHlXWBBgC1ihyWDIEBANOK
    /pV1gQYAaYtolQyBAQBKi4eVdYEGACKMHJYMgQEAQIz+lXWBBgC4jBmUdYEGAJCNr5QMgQEAro2R
    lHWBBgAljhmUdYEGAP2Or5QMgQEAuIyHlXWBBgDWjGiVDIEBAJCNHJYMgQEAro3+lXWBBgBDjmiV
    DIEBACWOh5V1gQYA/Y4clgyBAQD7idaWDIEBAN2J85Z2gQYA1Ipql3iBBgBoi9aWDIEBAEqL85Z2
    gQYAQYxql3iBBgDkiSWYioEBALaKi5cPgQEAEYvil8yBBgDUijeYRYIGALaKoJgkggEAUYslmIqB
    AQAjjIuXD4EBAEGMN5hFggYAI4ygmCSCAQDdiTmYu4IGANOKOZixgwYA+4mjmNmCAQC1iqOYk4MB
    AEqLOZi7ggYAQIw5mLGDBgBoi6OY2YIBACKMo5iTgwEAuIzzlnaBBgDVjNaWDIEBAK6Napd4gQYA
    Q47WlgyBAQAljvOWdoEGAL6MJZiKgQEAkY2Llw+BAQB+jOKXzIEGAK6NN5hFggYAkY2gmCSCAQAr
    jiWYioEBAP6Oi5cPgQEA643il8yBBgD+jqCYJIIBALiMOZi7ggYAro05mLGDBgDVjKOY2YIBAJCN
    o5iTgwEAJY45mLuCBgBDjqOY2YIBAP2Oo5iTgwEAA4wWlOKEAQDDi1eUoYQGAMOLDZVYhQYAYYvZ
    k5aFBgDKi/STt4UBAAGMypSbhQEAw4vFlQ6GBgDZjPuTRYQGAG2NEpTlhAEAMY1WlKGEBgBHjvqT
    RYQGAJ6OVpShhAYAnYxulEGFAQDZjLKU/YQGADGNDZVYhQYAnYwklfiFAQBtjcmUnIUBAAqObZRB
    hQEARo6ylPyEBgCejg2VWIUGAAqOJZX4hQEA2YxplbOFBgAxjcSVD4YGAEaOaZWzhQYAno7ElQ+G
    BgDdiTmYKIQGAPuJo5hGhAEAtYqjmACFAQBKizmYKIQGAGmLo5hGhAEAIoyjmACFAQDTijmYHoUG
    AN2JOZiVhQYA+4mjmLOFAQBAjDmYHoUGAEqLOZiVhQYAaIujmLOFAQC4jDmYKIQGANaMo5hGhAEA
    kI2jmACFAQAljjmYKIQGAEOOo5hGhAEA/Y6jmACFAQCujTmYHoUGALiMOZiVhQYA1oyjmLOFAQAl
    jjmYlYUGAEOOo5izhQEAko8ZlHWBBgAbj5GUdYEGAP+QGZR1gQYAapCvlAyBAQCIkJGUdYEGALCP
    aJUMgQEAko+HlXWBBgAbj/6VdYEGAB6RaJUMgQEA/5CHlXWBBgBqkByWDIEBAIiQ/pV1gQYAbJIa
    lHiBBgDXka6UDIEBAPWRkZR2gQYAJ5OXlIqBAQDkkleUzIEGADmTGpRFggYAbJKHlXiBBgDXkRyW
    DIEBAPWR/pV2gQYAjJJqlQ+BAQAnkwSWioEBAOSSxJXMgQYAOZOHlUWCBgCik2qVJIIBADuTkZS7
    ggYAO5MZlLGDBgClk66U2YIBADuT/pW7ggYAO5OHlbGDBgCkk2iVk4MBAKWTHJbZggEAsI/WlgyB
    AQCSj/OWdoEGABuPapd4gQYAHZHWlgyBAQAAkfOWdoEGAImQapd4gQYAmY8lmIqBAQBZj+KXzIEG
    ABuPN5hFggYAa5CLlw+BAQAGkSWYioEBAImQN5hFggYAxpDil8yBBgBrkKCYJIIBAJKPOZi7ggYA
    G485mLGDBgCwj6OY2YIBAACROZi7ggYAiJA5mLGDBgBqkKOYk4MBAB2Ro5jZggEAbJL0lniBBgD1
    kWqXeIEGAIyS15YOgQEAJ5Nwl4mBAQA4k/SWRYIGAKKT15YlggEA5JIxl8yBBgDYkYqXDoEBAHKS
    JpiJgQEA9ZE3mEWCBgAzkuKXzIEGANiRoJglggEAJ5MmmD+CAQA4k2qXu4IGADuT85axgwYApZPW
    lpODAQBskjeYu4IGAPWROZixgwYA15GjmJODAQDkkuKXfoIGAKKTipfYggEAjJKgmNiCAQDbjhKU
    5YQBALWP+ZNEhAYADZBWlKCEBgBNkBSU44QBACSR65NWhAYAeI9tlECFAQC0j7GU/IQGAAyQDZVY
    hQYA247JlJyFAQB4jySV+IUBACORopQNhQYAJZEhlI+FBgBKkMiUmYUBAOGQKZXzhQEAtI9olbOF
    BgAMkMWVD4YGACKRapWyhQYAO5ORlCiEBgCkk6+URoQBAKSTaJUAhQEAO5P+lSiEBgCkkxyWRoQB
    ADuTGZQehQYAO5ORlJWFBgCkk6+Us4UBADuTh5UehQYAO5P+lZWFBgCkkxyWs4UBAJKPOZgohAYA
    sI+jmEaEAQD/kDmYKIQGAGqQo5gAhQEAHpGjmEaEAQAbjzmYHoUGAJKPOZiVhQYAsI+jmLOFAQCI
    kDmYHoUGAP+QOZiVhQYAHpGjmLOFAQClk9aWAIUBADmTapcohAYAbJI3mCiEBgDXkaOYAIUBAOSS
    4pfqgwYAJ5MlmKqDAQCik4uXRYQBAIySoJhFhAEAO5Pzlh6FBgA5k2qXlYUGAPWROZgehQYAbJI3
    mJWFBgAnkyWYGIUBAOSS4pdYhQYAopOLl7KFAQCMkqCYsoUBAMqLrZRthgEAYYvOlIqGBgBli9qT
    +4YGAM+L+ZMZhwEABIyDlU+GAQBji0aV/YYGAMyLYZUehwEAAYw4lgqHAQC9iv6T0YcGANyJkJTQ
    hwYAE4sLlXWHBgACiz+UEIgBAPaJqZQ8iAEAhYoulR6IAQBdi8+UtIcBAL2KapXRhwYA3In9ldCH
    BgACi6uVEIgBAPmJGpY6iAEAU4tDlsGHAQBtjYCVU4YBANmMIJZrhgYAnYzcla+GAQBtjTiWC4cB
    AAqO3JWvhgEARo4glmuGBgDDi3qWxoYGANOKOZiKhgYAtYqjmGyGAQDdiTeYAIcGAPuJoZgghwEA
    P4w6mIiGBgAfjKOYaIYBAEmLOJgAhwYAZ4uhmCCHAQAPi3+WfocGANKK+JbRhwYA3Ylrl86HBgC0
    itmWO4gBAPuL8ZbGhwEARYtul86HBgC/izGXfocGAAqL5Zd5hwYAyYopmLqHAQD6iYyXN4gBADWM
    NJixhwEAZIuQlzeIAQAxjXyWx4YGAJyMlZZnhwEA2YzYliOHBgCejnyWx4YGAAqOlZZohwEARo7Y
    liOHBgCsjTqYh4YGAIyNo5hnhgEAt4w9mPqGBgDVjKeYF4cBAPqOo5hnhgEAJY4+mPmGBgBDjqiY
    FYcBAGmN95bIhwEA1Yycl9GHBgAvjTeXf4cGAJeMYpcdiAEAnI44l3+HBgBEjp2X0YcGAAaOZJcd
    iAEAd4zvl3OHBgAUjeKXEYgBAOaN8JdxhwYAqI06mK6HAQCDjuOXEIgBACiRj5SNhgYAu5CmlHWG
    AQAqkRmUA4cGANuOgJVThgEAeI/cla+GAQC0jyCWa4YGANqOOJYLhwEASpCDlVSGAQAjkQ+WeYYG
    ALuQcJUXhwEAJJGOlfaGBgBKkDeWCYcBADuRl5S9hwEAOJH+lbyHAQA7kxmUi4YGADmTkJQBhwYA
    opOulCKHAQA7k4eVi4YGAKWTaZVthgEAOJP9lQKHBgCikxuWIocBAH6RV5R6hwYA9pEalM6HBgBs
    kpCUzocGACeTE5S8hwEA5ZJTlHqHBgCNkq2UOIgBAHqRw5V1hwYA85GHlcuHBgBqkv2VzocGANGR
    apU0iAEA5JLAlXqHBgAmk4CVvYcBAImSGJY4iAEADJB8lsaGBgB3j5WWZ4cBALSP2JYjhwYA4ZCW
    lmWHAQAikdaWIYcGABmPOpiHhgYAko8+mPmGBgCwj6iYFYcBAIeQOpiIhgYAaJCjmGiGAQAAkTyY
    +oYGAB6RppgYhwEA1o73lsiHAQAJkDeXfocGALGPnZfQhwYAc49klx2IAQBDkPeWyIcBACGRlZfQ
    hwYA45BZlxuIAQBTj/CXcYcGABaPOpiuhwEA8Y/jlw+IAQCIkDaYsocBAMSQ7JdzhwYAYJHYlxOI
    AQA7k/OWioYGAKWT1pZthgEAN5NplwCHBgD1kTmYioYGANmRo5hthgEAbJI0mP+GBgDlkuKXw4YG
    ACiTJJiChgEAoJOJlyCHAQCNkp2YHocBAPaR9JbQhwYAbJJql8uHBgDZkdeWOogBACeT7Ja8hwEA
    5ZIsl3mHBgD4kSuYu4cBADGS45d4hwYAjJKKlzOIAQA=
    """
  
  static let sumDriveWallString: String? = """
    NQkAAAAAAAB/lR2AiIEBABuWuIAOgQEA/pXYgHiBBgAXlqF/JYIBAPqVC4BEggYAv5VfgMuBBgDM
    lNKAiYEBAGeVa4EOgQEAiJVOgXiBBgAPlRCBzIEGALuUToFFggYAUZRrgSSCAQDKlB2APoIBAA6V
    YIB9ggYAhZULgLuCBgBllaJ/2IIBALqU2IC7ggYAUZS4gNiCAQDxlh+AhYEBAC+XZIDHgQYAZJgg
    gIKBAQCIl72ACoEBAGuX3IB0gQYAy5fJf+uBAQCMlxGAKYIGANSWb4EMgQEA85ZQgXWBBgBCmG+B
    DIEBAGCYUIF1gQYATpfMf2uCAQBzlluAgIIGALCWGIDEggEAqJfGgECDAQDpl2mAhoIGACWYKIDN
    ggEAtZfngNWCBgAxmF+B04IGAM2UPYKKgQEAD5V9gsyBBgAcliaCDIEBAP6VRIJ2gQYAZ5XYgg+B
    AQCIlbqCeIEGAM2UqoOKgQEAUpTYgiSCAQC7lLqCRYIGAByWk4MMgQEA/pWxg3aBBgC5lESCu4IG
    AE+UJoLZggEAuZSxg7uCBgBPlJOD2YIBAImXJoIMgQEAa5dEgnWBBgDWltmCDIEBAPSWu4J1gQYA
    Q5jZggyBAQBhmLuCdYEGAImXk4MMgQEAa5exg3WBBgDLlB2AqoMBAA6VYIDqgwYAG5agf5WDAQD7
    lQqAsoMGAE+UbIGTgwEAuZROgbGDBgBllaJ/RoQBAIWVC4AohAYAUZS4gEWEAQC6lNiAKIQGAMyU
    HYAYhQEAHpahfwKFAQD9lQuAH4UGALmUToEehQYAT5RsgQCFAQDFltWAtIMGACuXrIChgwEAtZYa
    gDCEAQBzll2A8IMGAG6XioF2gwEAypbYgB+FBgAzl7eAAYUBAMqWTYEphAYANJdngUmEAQBPlNmC
    k4MBALiUu4KxgwYAT5QlgkaEAQC4lESCKIQGAE+Uk4NGhAEAuJSxgyiEBgBPlNmCAIUBALiUu4Ie
    hQYALZfLgTSDBgBrlz6CLoQBAC2XgYLrgwYAQJgjgo+DBgADmOKB1IMBAMuWQ4IfhQYANJciggSF
    AQAHmJeCioQBAC2XOIOhhAYAbpf2guKEAQBDmNyCRYQGAAeYToNBhQEAQ5iTg/yEBgDYmNyAdIEG
    APaYvYALgQEA+ZgRgCuCBgA5mcl/7oEBAJ6YZIDIgQYAz5khgICBAQBjmr6ACoEBAEWa3YB0gQYA
    pZrJf+mBAQBlmhCAJ4IGAAqaZYDGgQYArplwgQyBAQDNmVCBdYEGALuYzH9sggEAVplqgIiCBgCT
    mSmAz4IBAB+Z5oDYggYABJnFgEKDAQAmmst/aIIBAI2a5IDYggYAcprDgEGDAQCemV6B1YIGADmb
    JYB7gQEAdptlgMOBBgCqnB6AhIEBANGbwIAJgQEAs5vdgHOBBgARnMR/2YEBANSbCIAcggYAG5tw
    gQyBAQA7m1CBdYEGAIucbYEMgQEAqZxOgXaBBgCUm8B/WYIBAMKaaICFggYA+5oigMqCAQCXm3qA
    IYMBAKqcCoC6ggYAjJygf9iCAQDUm7uA2oIGAA6bXYHVggYA2JhEgnWBBgD2mCaCDIEBAGSaJoIM
    gQEARppEgnWBBgCwmdmCDIEBANiYsYN1gQYA95iTgwyBAQDOmbuCdYEGAGSak4MMgQEARpqxg3WB
    BgDRmyaCDIEBALObRIJ1gQYAHpvZggyBAQA8m7uCdYEGAIuc2YIMgQEAqZy7gnWBBgDRm5ODDIEB
    ALObsYN1gQYAzZiBgXaDAQA7moGBdoMBAICcw4CMgwYAPJyDgM2DAQAanCiBM4MGAJ+cGoBqhAEA
    iZy3gAGFBgBDnHaAP4UBACace4E6hAEAQ5z2gMKEAQCRnJWBIIQGAJCYw4EwgwYA1pg7gi6EAQBv
    meGB04MBAJqYf4LpgwYA/pnDgTCDBgCtmSOCjoMGAEWaOoIshAEACJp/gumDBgB0mZeCiYQBAJuY
    N4OhhAYA15jzguWEAQB0mU6DQYUBALGZ24JFhAYACZo3g6GEBgBFmvOC5YQBALCZk4P8hAYAJ5sZ
    gouDBgCEm6+BL4MGAOqa14HQgwEAeZt8gumDBgCOnBaCn4MGALubPoIshAEA45qVgoiEAQAonCuC
    94QBAJGcSoLYhAYAH5vZgkSEBgB3mzaDoIQGAOKaToNAhQEAHpuSg/yEBgCOnMyCVoQGALeb9ILj
    hAEAjpyDgw2FBgCIlSiEeIEGAGeVRYQPgQEAu5QohEWCBgAPleqDzIEGAFKURYQkggEAHJYAhQyB
    AQDNlBiFioEBAGeVsoUPgQEAiJWVhXiBBgAPlViFzIEGALuUlYVFggYAUpSyhSSCAQD+lR6FdoEG
    AE+UAIXZggEAuZQehbuCBgD0liiEdYEGANaWRoQMgQEAYZgohHWBBgCJlwCFDIEBAEOYRoQMgQEA
    1pazhQyBAQD0lpWFdYEGAGuXHoV1gQYAQ5izhQyBAQBhmJWFdYEGAM2UhYaKgQEAD5XFhsyBBgAc
    lm6GDIEBAP6Vi4Z2gQYAZ5Ughw+BAQCIlQKHeIEGAM2U8oeKgQEAu5QCh0WCBgBSlCCHJIIBAByW
    24cMgQEA/pX5h3aBBgC5lIuGu4IGAE+UbobZggEAuZT5h7uCBgBPlNuH2YIBAImXbYYMgQEAa5eL
    hnWBBgDWliGHDIEBAPSWA4d1gQYAQ5ghhwyBAQBhmAOHdYEGAImX2ocMgQEAa5f5h3WBBgBQmDGH
    1oIGAJmX54fWggYAuJQohLGDBgBPlEaEk4MBAE+Us4WTgwEAuJSVhbGDBgBPlACFRoQBALiUKIQe
    hQYAT5RGhACFAQC4lB6FKIQGALiUlYUehQYAT5SzhQCFAQBPlCGHk4MBALiUA4exgwYAT5RthkaE
    AQC4lIuGKIQGAE+U2odGhAEAuJT5hyiEBgC4lAOHHoUGAE+UIYcAhQEA0Jbnh6CDBgCJlyGHkIMG
    AMqXZYfQgwEAqJgsh+eDAQDBl8KGy4QGANCWMYdWhAYAzZayh9iEBgA3l9CH9oQBAOCXLIeuhAEA
    sJlGhAyBAQD3mACFDIEBAM6ZKIR1gQYAZJoAhQyBAQDYmB6FdYEGALCZs4UMgQEARpoehXWBBgDO
    mZWFdYEGADybKIR1gQYAHptGhAyBAQCpnCiEdYEGANGbAIUMgQEAi5xGhAyBAQAem7OFDIEBADyb
    lYV1gQYAs5sehXWBBgCLnLOFDIEBAKmclYV1gQYA2JiLhnWBBgD3mG2GDIEBAGSabYYMgQEARpqL
    hnWBBgCwmSGHDIEBANiY+Yd1gQYA95jahwyBAQDOmQOHdYEGAGSa2ocMgQEARpr5h3WBBgDSmLKH
    1IIGAPCY0Ic9gwEAupkzh9uCBgA+mrOH1oIGAF2a04c/gwEA0ZtthgyBAQCzm4uGdYEGAB6bIYcM
    gQEAPJsDh3WBBgCLnCGHDIEBAKmcA4d1gQYA0ZvahwyBAQCzm/mHdYEGACmbNIfeggYAvZvCh9uC
    BgBImceGRoMGAMWYwobHgwYAMprDhseDBgATmiyH54MBADSZv4bDhAYAUpkoh6WEAQC1mseGR4MG
    AJ6bwYbGgwYAH5zChkSDBgCBmyuH44MBAImcwoemgwYAoZq/hsOEBgAdnMeGr4QGAL+aKIekhAEA
    hpw0hzuEBgAmnNGHB4UBAI+cs4clhQYAh5ULgJWFBgC6lNiAlYUGAA+VX4BYhQYAZ5Whf7KFAQBR
    lLeAsoUBAB2WoX9vhgEAT5RsgW2GAQDMlB2Ag4YBAA+VYIDEhgYAh5UOgACHBgBolaV/IIcBAL2U
    2YAAhwYAVJS5gCCHAQD+lQuAi4YGALmUT4GKhgYAuJYdgJyFAQB2ll+AXIUGADOXuIBuhgEAzJZO
    gZWFBgA2l2yBs4UBAMqW2ICLhgYAdpZfgMmGBgC5lhyAB4cBAMqWToEBhwYAM5drgSGHAQC4lESC
    lYUGAE+UJYKzhQEAuJSxg5WFBgBPlNmCbYYBAE+Uk4OzhQEAupREggGHBgBRlCeCIocBALmUu4KL
    hgYAupSxgwGHBgBRlJSDIYcBADaXJoJthgEAy5a6gpaFBgBrl6uDm4UBADSX1YK3hQEANJeQg3KG
    AQDMlkOCi4YGAMqWsIOMhgYAypa6ggGHBgAzl9iCIocBAIeV2IDLhwYAaJW5gDSIAQADlhyAvYcB
    AMSVX4B6hwYAD5UVgXmHBgDMlFWBvIcBAP6VToHOhwYAHZZqgTiIAQB2lhCBeocGALmW0YC9hwEA
    h5VEgs6HBgDMlMGCvIcBAA+VgYJ6hwYAZ5UngjiIAQCGlbGDzocGAGaVlIM3iAEA/ZW6gs6HBgAe
    lteCOIgBALiWPYK8hwEAdpZ9gnqHBgC3lqmDvocBAJicIYDZhQEAKpxvgbWFAQCTnE+B1IUGACac
    v4BqhgEAkJzcgEyGBgAsnHGBI4cBAJWcjoEChwYA15iqg5yFAQBFmqqDnIUBACac44KuhQEAKZwi
    gm6GAQCQnAGDj4UGALSbqYOZhQEAJZyHg3WGAQCTnAWCjIYGACuc3IIkhwEAkpxwg42GBgCUnPqC
    AocGAKWcDIK9hwEApZx4g72HAQBPlACFs4UBAE+URoRthgEAuJQehZWFBgBPlLSFbIYBALmUKISL
    hgYAUJQBhSCHAQC4lJaFioYGALqUH4UAhwYALZfug1iFBgBtl2SEUIYBAC2XpYQOhgYAQ5hJhLOF
    BgAHmAWE94UBAMiWJoQDhwYAMZdBhCeHAQAHmLyEroYBAC2XW4XGhgYAapcYhQqHAQBDmACFaoYG
    AAaYc4VlhwEAQpi3hSGHBgC4lIuGlYUGAE+UbYazhQEAuJT5h5WFBgBPlCCHbYYBAE+U2oezhQEA
    u5SMhgGHBgBRlG6GIocBALmUA4eLhgYAupT5hwCHBgBQlNuHIIcBAECXx4ZOhQYAwJfBhjeGBgDU
    ljOHwIUGAJ6YKIdYhQEA35crhxmGAQBBl8GGtYYGAM+Ws4dDhgYAOpfQh16GAQDalh6HF4cGAByX
    Y4dVhwEAo5gqh76GAQAemBGHSIcBAMyUL4S8hwEADpXvg3mHBgBilf+ENogBAPyVJ4TPhwYAHJZE
    hDiIAQANlVyFeYcGAISVHYXNhwYAypSchbuHAQD4lZSF0YcGABGWrIU+iAEAdJbqg3uHBgBzllmF
    f4cGALKWGIXDhwEAaJfPhcGHAQCHlYyGzocGAA+VyYZ6hwYAZ5VvhjeIAQDMlAmHvIcBAIOV+IfO
    hwYAYJXZhzeIAQD+lQOH0IcGABuWIYc6iAEA05ZuhtiHBgAslxOGfIcGAJaWMIYgiAEAEZewhh2I
    AQBAmGuG2ocGAOKXxYaEhwYAA5gohh+IAQB+mKuGIYgBAK6W9IfKhwEApJcFh8qHAQCbmO6DWIUG
    ANeYYYRThgEAdJkFhPiFAQCbmKWED4YGAAma7oNYhQYAsJlKhLOFBgBFmmGEU4YBAAiapYQPhgYA
    dJm9hK+GAQCbmFyFxoYGANeYGIUKhwEAdJl2hWeHAQCwmQGFa4YGAAiaXYXHhgYARZoZhQuHAQCw
    mbmFI4cGAB6bSYSzhQYAdpvug1eFBgDimgWE+IUBAHabpYQPhgYAjJxLhLKFBgC0m2OEU4YBAEuc
    CoTzhQEA4pq8hK6GAQAmnFCEF4cBAI6cboT2hgYAHpsAhWqGBgB3m1uFxoYGACGbt4UkhwYA5Zpz
    hWiHAQCNnPCEeYYGALabFoUHhwEAi5y3hSGHBgBMnHeFZYcBAL2Yv4Y6hQYANJm+hi+GBgAqmr+G
    OoUGAFOZKIcRhgEADJooh1iFAQC+mL6GpYYGACuavYalhgYAg5kZh0GHAQARmimHv4YBAJybwoYy
    hQYAoZq9hi+GBgA0nM2GA4YGAHybK4dQhQEAv5onhxCGAQCQnDOHo4UGAPCbEIc/hgEAJ5zYh3CG
    AQBXm7yG5oYGAHGbKIfKhgEAj5y2h46GBgCNnDmHBocGANeY0YXAhwEAQZrVhcWHAQCinN6EvIcB
    ALyb0oXMhwEAmZgUhnyHBgBMmcyGf4cGAHuZQoYpiAEABpoYhn6HBgCymXuG14cGAPeZxIYMiAEA
    CZkLh8KHAQDFmiqHdYcBACSbdIbRhwYAfpsQhoKHBgDimr+GWYcGANmaP4YUiAEAYJu6hhOIAQCk
    nJOGwocGADOc2oZmhwYAfZx8hiqIAQD0mx+Hp4cBAKOct4e+hwEAIJ3ZgHeBBgA+nbmADoEBACCd
    C4BEggYAPp2ifyOCAQDknGGAzIEGAA+eHYCJgQEAjJ7ZgHqBBgCNng6ARIIGAE+eYIDMgQYA+J1s
    gQyBAQAVnk+BdoEGAP+dnH/SggEAF54JgLqCBgCsnrmAEYEBAK2epn8kggEAV5/ZgEWCBgDAn7mA
    JYIBAEefVoGKgQEABZ8WgcyBBgAFn2CAgoIGAEifHYDCggEAW59PgbyCBgDFn2yB2YIBACCdRIJ1
    gQYAPp0mggyBAQCMnkSCeIEGAPid2YIMgQEAIJ2xg3WBBgA+nZODDIEBABaeu4J2gQYAjJ6xg3iB
    BgCtnieCD4EBAEefwYKKgQEAwp8ngiSCAQBZn0SCRYIGAAWfgYLMgQYArZ6Ugw+BAQBZn7GDRYIG
    AMKflIMkggEAW5+7gruCBgDFn9mC2YIBADydAYCVgwYAeJ22f1mDAQD4nMF/1YMBAI6eC4CxgwYA
    /52df0CEAQB3nbZ/xYQBAOScXYCmhAYAPJ0BgAKFBgD6nMB/RIUBABieCYAnhAYAjZ4LgB6FBgCv
    nqJ/k4MBAMOfuICUgwEAWp/YgLGDBgBInx2AL4QBAAafYIDvgwYArp6ifwGFAQBan9iAH4UGAMOf
    t4ABhQEAW59OgSiEBgDFn2yBRoQBAMWfJYKTgwEAXJ9EgrGDBgDFn5ODk4MBAFyfsYOxgwYAxZ8l
    ggCFAQBcn0SCHoUGAFyfu4IohAYAxZ/ZgkaEAQBcn7GDHoUGAMWfk4MAhQEA+J1GhAyBAQA+nQCF
    DIEBABaeKIR2gQYAIJ0ehXWBBgD4nbOFDIEBAIyeH4V4gQYAFp6VhXaBBgBHny+EioEBAK2eAYUP
    gQEABZ/vg8yBBgDCnwGFJIIBAEefnIWKgQEABZ9chcyBBgBZnx+FRYIGAFufKIS7ggYAxZ9GhNmC
    AQBbn5WFu4IGAMWfs4XZggEAIJ2LhnWBBgA+nW2GDIEBAIyejIZ4gQYA+J0ghwyBAQAgnfmHdYEG
    AD6d2ocMgQEAFp4Dh3aBBgCMnvmHeIEGAK2eboYPgQEAwp9uhiSCAQBZn4yGRYIGAAWfyYbMgQYA
    R58Jh4qBAQCtntyHD4EBAMKf3IckggEAWZ/5h0WCBgBbnwOHu4IGAMWfIIfZggEAxZ8AhZODAQBc
    nx6FsYMGAFyfKIQohAYAxZ9GhEaEAQDFnwCFAIUBAFyflYUohAYAxZ+zhUaEAQBcnx6FHoUGAMWf
    bYaTgwEAXJ+LhrGDBgDFn9qHk4MBAFyf+YexgwYAxZ9thgCFAQBcn4uGHoUGAFyfA4cohAYAxZ8h
    h0aEAQDFn9qHAIUBAFyf+YcehQYA/J2ef7CFAQBlnbN/PYYBAOGcZIARhgYAF54JgJWFBgAynQiA
    dYYGAOmc1n+9hgEA+Z2hfyGHAQBBnbeAJIcGAACdd4BohwEAjZ4LgIuGBgAXngqAAYcGAEifHYCc
    hQEABZ9fgFyFBgCtnqF/boYBAMOft4BuhgEAW59OgZWFBgDFn2yBs4UBAAWfX4DIhgYAWZ/XgIuG
    BgBInxyAB4cBAFqfTYEBhwYAw59qgSCHAQDFnyOCaYYBAFyfu4KVhQYAxZ/ZgrOFAQDFn5CDaIYB
    AFyfQoKIhgYAXJ+vg4iGBgBfn7qC/IYGAMif2IIZhwEA+523gDaIAQCTnhuAvIcBAFSeXoB5hwYA
    F57WgMyHBgBgnY6BzYcGAD+dcIE2iAEAjp5NgcyHBgAGnxCBeYcGAEmf0YC8hwEArp5pgTaIAQDo
    nMyBeocGAD+d3II3iAEA1p0Egs+HBgDvnR2CO4gBAIGeoYIeiAEA6Jw4g3qHBgBgnfqCzocGALie
    3oLRhwYA1p1wg9CHBgDwnYuDPIgBAFOfPIK0hwEADp99gnSHBgBYn7CDsocBAP2eH4MPiAEAXJ8o
    hJWFBgDFn0aEs4UBAMWf/oRohgEAXJ+VhZWFBgDFn7OFs4UBAF+fKIT6hgYAyZ9GhBeHAQBcnx2F
    iIYGAF+flYX6hgYAyZ+0hReHAQDFn2uGaIYBAFyfA4eVhQYAxZ8hh7OFAQDFn9uHbIYBAFyfioaI
    hgYAW5/4h4qGBgBfnwOH+oYGAMmfIYcXhwEAXZ1nhMuHBgDlnKSEdIcGADudSYQ0iAEAuZ5MhNCH
    BgCBng6EHogBAF+d1IXQhwYAQJ22hTmIAQDUnd2E0IcGALieuYXQhwYA7Z32hDyIAQCBnnuFHYgB
    AA+f7INzhwYA/Z6NhA+IAQAPn1qFc4cGAFifHoWyhwEA/Z76hQ+IAQDWnUqGz4cGAPCdZYY7iAEA
    gZ7ohhyIAQDjnHuHdocGAB2dAofIhwYANp0ghzSIAQD6nduHOIgBALmeJofQhwYAF575h86HBgAP
    n8eGc4cGAFmfi4axhwEAT5/7h7qHAQD+nmaHEIgBAIiVb4h4gQYAZ5WNiA+BAQC7lG+IRYIGAA+V
    MojMgQYAUpSNiCSCAQAclkiJDIEBAM2UX4mKgQEAiJXdiXiBBgAPlZ+JzIEGALuU3YlFggYA/pVm
    iXaBBgBPlEiJ2YIBALmUZom7ggYA9JZwiHWBBgDWlo6IDIEBAGGYcIh1gQYAiZdIiQyBAQBDmI6I
    DIEBAPSW3Yl1gQYAa5dmiXWBBgBhmN2JdYEGABuYaYjUggYAO5iGiD2DAQCfl12J2oIGAC2Y6YnY
    ggYAZ5X6iQ+BAQDNlM2KioEBAFKU+okkggEAD5UNi8yBBgAclrWKDIEBAP6V04p2gQYAZ5Vniw+B
    AQCIlUqLeIEGAM2UOoyKgQEAu5RKi0WCBgBSlGeLJIIBAByWI4wMgQEA/pVAjHaBBgBPlLWK2YIB
    ALmU04q7ggYAuZRAjLuCBgBPlCOM2YIBANaW+4kMgQEAiZe1igyBAQBDmPuJDIEBAGuX04p1gQYA
    1pZpiwyBAQD0lkqLdYEGAEOYaYsMgQEAYZhKi3WBBgCJlyKMDIEBAGuXQIx1gQYAuJRwiLGDBgBP
    lI6Ik4MBALiU3YmxgwYAT5RIiUaEAQC4lHCIHoUGAE+UjogAhQEAuJRmiSiEBgC4lN2JHoUGAHmX
    yIiBgwEANpcFiT2DBgDQllqJpIMGAG6XF4pzgwEAzpZpiCGEBgA3l4aIQYQBADSXSIkAhQEAzpbX
    iSOEBgDLlmaJHoUGAE+U+4mTgwEAT5Rpi5ODAQC4lEqLsYMGAE+UtYpGhAEAuJTTiiiEBgBPlPuJ
    AIUBAE+UIoxGhAEAuJRAjCiEBgC4lEqLHoUGAE+UaYsAhQEALZdaijSDBgAtlxCL64MGAGuXzoou
    hAEAQJiyio+DBgADmHKK1YMBADeX8olEhAEANJexigSFAQDLltKKH4UGAAeYJ4uKhAEALZfIi6GE
    BgBul4aL4oQBAEOYa4tFhAYAB5jei0GFAQBDmCKM/IQGALCZjogMgQEA95hIiQyBAQDOmXCIdYEG
    AGSaSIkMgQEA2JhmiXWBBgBGmmaJdYEGAM6Z3Yl1gQYAr5mPiDqDAQABmUuJPYMBAM6ZrojQggYA
    HplsidOCBgBEmiSJ0YIGAF6aO4k9gwEAnJnridSCBgA8m3CIdYEGAB6bjogMgQEAqZxwiHWBBgDR
    m0iJDIEBAIucjogMgQEAPJvdiXWBBgCzm2aJdYEGAKmc3Yl1gQYAQZu2iNWCBgAgm5qIPoMBACKb
    /4nZggYA5pq+iR+DAQDAmzaJ1oIGALCZ+4kMgQEA95i1igyBAQDYmNOKdYEGAGSatYoMgQEARprT
    inWBBgCwmWmLDIEBANiYQIx1gQYA95gijAyBAQDOmUqLdYEGAGSaIowMgQEARppAjHWBBgAem/uJ
    DIEBANGbtYoMgQEAi5z7iQyBAQCzm9OKdYEGAB6baYsMgQEAPJtKi3WBBgCLnGmLDIEBAKmcSot1
    gQYA0ZsijAyBAQCzm0CMdYEGAM2YD4p3gwEAOZoOinWDAQAlnBqIPoMGAOKbWIiCgwEAFJymiTeD
    BgCInDmJooMGACWcmIhFhAEAjZy2iCOEBgAnnASKPoQBAJCcI4ohhAYAKZxEiQCFAQCTnCaJHoUG
    AI+YUIoxgwYAb5lwitODAQCamA+L6YMGANaYy4ouhAEA/ZlQijCDBgCtmbKKjoMGAAiaDovpgwYA
    RZrJiiuEAQB0mSeLiYQBAJuYx4uhhAYA15iCi+WEAQB0md6LQYUBALGZa4tFhAYACZrGi6GEBgBF
    moKL5YQBALCZIoz8hAYAjZtEijSDBgApm6qKjYMGAOyaZ4rRgwEAepsNi+qDBgCOnKWKoIMGALyb
    z4ouhAEA45oli4mEAQAonLuK94QBAJGc2orYhAYAH5tqi0SEBgB3m8aLoIQGAB6bIoz8hAYA4prd
    i0CFAQCOnFuLVoQGALebhIvjhAEAjpwSjA2FBgBnldWMD4EBAIiVt4x4gQYAD5V6jMyBBgBSlNWM
    JIIBALuUt4xFggYAzZSnjYqBAQCIlSSOeIEGALuUJI5FggYAD5XnjcyBBgAclpCNDIEBAP6Vro12
    gQYAuZSujbuCBgBPlJCN2YIBANaW1owMgQEA9Ja4jHWBBgBDmNaMDIEBAGGYuIx1gQYA9JYljnWB
    BgCJl5CNDIEBAGuXro11gQYAYZgljnWBBgBnlUKOD4EBAM2UFI+KgQEAUpRCjiSCAQAPlVSPzIEG
    AByW/Y4MgQEA/pUbj3aBBgBnla+PD4EBAIiVko94gQYAUpSvjySCAQC7lJKPRYIGAByWapAMgQEA
    /pWIkHaBBgBPlP2O2YIBALmUG4+7ggYAuZSIkLuCBgBPlGqQ2YIBANaWQ44MgQEAiZf9jgyBAQBD
    mEOODIEBAGuXG491gQYA1pawjwyBAQD0lpKPdYEGAEOYsI8MgQEAYZiSj3WBBgCJl2qQDIEBAGuX
    iJB1gQYAUJjBj9aCBgCZl3eQ1oIGAE+U1oyTgwEAuJS4jLGDBgC4lCWOsYMGAE+U1owAhQEAuJS4
    jB6FBgBPlJCNRoQBALiUro0ohAYAuJQljh6FBgBPlEOOk4MBAE+UsI+TgwEAuJSSj7GDBgBPlP2O
    RoQBALiUG48ohAYAT5RDjgCFAQBPlGqQRoQBALiUiJAohAYAT5SwjwCFAQC4lJKPHoUGANCWd5Cg
    gwYAiZexj5CDBgDKl/SP0IMBAKiYu4/ngwEAwZdSj8uEBgDQlsGPVoQGAM2WQpDYhAYA4Je7j66E
    AQCwmdaMDIEBAM6ZuIx1gQYA2JiujXWBBgD3mJCNDIEBAGSakI0MgQEARpqujXWBBgDOmSWOdYEG
    AB6b1owMgQEAPJu4jHWBBgCLnNaMDIEBAKmcuIx1gQYAPJsljnWBBgDRm5CNDIEBALObro11gQYA
    qZwljnWBBgCwmUOODIEBAPeY/Y4MgQEA2Jgbj3WBBgBkmv2ODIEBAEaaG491gQYAsJmwjwyBAQDY
    mIiQdYEGAPeYapAMgQEAzpmSj3WBBgBkmmqQDIEBAEaaiJB1gQYA0phCkNSCBgC6mcKP24IGAD6a
    Q5DWggYAHptDjgyBAQDRm/2ODIEBAIucQ44MgQEAs5sbj3WBBgAem7CPDIEBADybko91gQYAi5yw
    jwyBAQCpnJKPdYEGANGbapAMgQEAs5uIkHWBBgApm8SP3oIGAL2bUpDbggYASJlXj0aDBgDFmFKP
    x4MGADKaUo/HgwYAE5q7j+eDAQA0mU6Pw4QGAFKZuI+lhAEAtZpXj0eDBgCem1CPxoMGAB+cUo9E
    gwYAgZu6j+ODAQCJnFKQpoMGAKGaTo/DhAYAHZxXj6+EBgC/mriPpIQBAIacxI87hAYAj5xDkCWF
    BgBPlEiJs4UBAE+UjohshgEAuJRmiZWFBgC4lHCIioYGAFCUSYkghwEAuJTeiYqGBgC5lGaJAIcG
    AMqWrojVhQYANJeQiLaFAQDLlt2JlYUGAMyWkogthwYAGJdViPSGAQALl9OIcYcBAMqWJYlLhgYA
    Npc/iWWGAQDLlgGKLocGABeXw4n2hgEAuJTTipWFBgBPlLWKs4UBAE+U/IlshgEAuJRAjJWFBgBP
    lGiLbYYBAE+UIoyzhQEAUZS2iiGHAQC6lNSKAYcGALmUS4uLhgYAupRBjAGHBgBRlCOMIYcBADSX
    +4mzhQEANZe2im6GAQDLlkmLloUGAGuXO4ybhQEANJdli7eFAQA0lyCMcoYBAMuW1IqLhgYAC5dA
    inSHAQDKlkCMjIYGAMmWS4sChwYAM5doiyOHAQDKlHeIu4cBAA2VN4h5hwYAX5VGiTaIAQD2lW+I
    04cGABOWjYg+iAEADZWkiXiHBgCClWWJzocGAMmU5Im6hwEA9ZXdidSHBgBvljOIg4cGAG6WoYmE
    hwYArJZlic6HAQAOlRGLeYcGAIaV1IrOhwYAZZW3ijeIAQARlvqJPogBAMuUUYu8hwEAhpVBjM6H
    BgBmlSSMN4gBAPyVSovPhwYAG5ZniziIAQB0lg+LeocGALeW1orDhwEAt5Y5jL6HAQCTnK+IlYUG
    ACmckYizhQEAlJzdidSFBgAonE2JZIYBAJGcjYgshwYAUJxOiHKHAQBEnMmI84YBAJScZ4lLhgYA
    LJwBiiOHAQCVnB6KAocGANeYOYychQEARZo6jJyFAQArnPyJtoUBACeccouuhQEAKZyyim6GAQCQ
    nJGLj4UGALSbOYyZhQEAk5yUioyGBgArnGyLJIcBAJKc/4uNhgYAlJyKiwKHBgCsnC+JxocBAKac
    m4q9hwEApZwIjL2HAQBPlNaMbYYBALiUro2VhQYAT5SQjbOFAQC5lLiMi4YGALiUJY6KhgYAupSu
    jQCHBgBQlJGNIIcBAC2XfoxYhQYALZc1jQ6GBgBtl/OMUIYBAEOY2YyzhQYAB5iVjPeFAQDIlraM
    A4cGADGX0YwnhwEAB5hMja6GAQAtl+uNxoYGAGqXqI0KhwEAQ5iQjWqGBgAGmAKOZYcBAEKYRo4h
    hwYAuJQbj5WFBgBPlP2Os4UBAE+UQ45shgEAuJSIkJWFBgBPlLCPbYYBAE+UapCzhQEAUZT+jiKH
    AQC7lBuPAYcGALmUko+LhgYAupSJkACHBgBQlGuQIIcBAECXV49OhQYAwJdRjzeGBgDUlsKPwIUG
    AJ6YuI9YhQEA35e6jxmGAQBBl1GPtYYGAM+WQpBDhgYA2paujxeHBgAcl/KPVYcBAKOYuY++hgEA
    Hpihj0iHAQDMlL6MvIcBAA6Vfox5hwYA/JW3jM+HBgAcltSMOIgBAISVrY3NhwYAypQsjruHAQAN
    leyNeYcGAGKVjo02iAEA+JUjjtGHBgB0lnmMe4cGALKWqI3DhwEAc5bpjX+HBgAPlVmPeocGAIeV
    HI/OhwYAZ5X+jjeIAQARljuOPogBAMyUmY+8hwEAg5WHkM6HBgBglWmQN4gBAP6Vk4/QhwYAG5ax
    jzqIAQAsl6KOfIcGAGiXX47BhwEA05b+jtiHBgCWlsCOIIgBABGXP48diAEA4pdVj4SHBgBAmPuO
    2ocGAAOYuI4fiAEAfpg7jyGIAQCkl5WPyocBAJuYfoxYhQYAdJmVjPiFAQCbmDSND4YGANeY8IxT
    hgEACJp+jFiFBgCwmdmMs4UGAAiaNY0PhgYARZrxjFOGAQB0mUyNr4YBAJuY643GhgYA15injQqH
    AQB0mQWOZ4cBALCZkI1rhgYACJrsjceGBgBFmqmNC4cBALCZSY4jhwYAdpt9jFeFBgAem9mMs4UG
    AOKalIz4hQEAdps1jQ+GBgCMnNqMsoUGACWcF4x1hgEAS5yajPOFAQC0m/OMU4YBAOKaTI2vhgEA
    JpzgjBeHAQCOnP6M9oYGAB6bkI1qhgYAd5vrjcaGBgAhm0aOJIcGAOWaA45ohwEAjZyAjXmGBgC2
    m6aNB4cBAIucRo4hhwYATJwGjmWHAQC9mE6POoUGADSZTo8vhgYAKppOjzqFBgBTmbePEYYBAAya
    uI9YhQEAvphNj6WGBgArmk2PpYYGAIOZqI9BhwEAEZq5j7+GAQCcm1GPMoUGAKGaTY8vhgYANJxc
    jwOGBgB8m7uPUIUBAL+ato8QhgEAkJzDj6OFBgDwm6CPP4YBAFebTI/mhgYAcZu3j8qGAQCPnEaQ
    joYGAI2cyI8GhwYAopxujbyHAQCZmKOOfIcGANeYYI7AhwEATJlbj3+HBgB7mdGOKYgBAAaaqI5+
    hwYAQZpljsWHAQCymQuP14cGAPeZU48MiAEACZmaj8KHAQDFmrmPdYcBAH6bn46ChwYA4ppPj1mH
    BgAkmwOP0YcGANmazo4UiAEAYJtJjxOIAQC8m2KOzIcBADOcaY9mhwYApJwjj8KHBgB9nAuPKogB
    APSbro+nhwEAo5xHkL6HAQD4nY6IDIEBAD6dSIkMgQEAFp5wiHaBBgAgnWaJdYEGAIyeZol4gQYA
    Fp7diXaBBgBHn3aIioEBAK2eSYkPgQEABZ82iMyBBgDCn0mJJIIBAEef5ImKgQEABZ+kicyBBgBZ
    n2aJRYIGAFufcIi7ggYAxZ+OiNmCAQBbn92Ju4IGAPid+4kMgQEAPp21igyBAQAgndOKdYEGAIye
    1Ip4gQYA+J1oiwyBAQAgnUCMdYEGAD6dIowMgQEAFp5Ki3aBBgCMnkGMeIEGAK2etooPgQEAwp+2
    iiSCAQAFnxGLzIEGAFmf1IpFggYAR59Ri4qBAQCtniOMD4EBAMKfI4wkggEAWZ9BjEWCBgDFn/uJ
    2YIBAFufSou7ggYAxZ9oi9mCAQDFn0iJk4MBAFyfZomxgwYAXJ9wiCiEBgDFn46IRoQBAMWfSIkA
    hQEAXJ/diSiEBgBcn2aJHoUGAMWftYqTgwEAXJ/TirGDBgDFnyKMk4MBAFyfQIyxgwYAxZ/7iUaE
    AQDFn7WKAIUBAFyf04oehQYAXJ9KiyiEBgDFn2mLRoQBAMWfIowAhQEAXJ9AjB6FBgD4ndWMDIEB
    ABaeuIx2gQYAIJ2ujXWBBgA+nZCNDIEBAIyero14gQYAFp4ljnaBBgBHn76MioEBAAWffozMgQYA
    rZ6RjQ+BAQBHnyuOioEBAFmfro1FggYAwp+RjSSCAQAFn+uNzIEGAFufuIy7ggYAxZ/VjNmCAQBb
    nyWOu4IGAPidQ44MgQEAPp39jgyBAQAgnRuPdYEGAIyeG494gQYA+J2wjwyBAQAgnYiQdYEGAD6d
    apAMgQEAFp6Sj3aBBgCMnomQeIEGAK2e/o4PgQEAwp/+jiSCAQAFn1mPzIEGAFmfG49FggYAR5+Z
    j4qBAQCtnmuQD4EBAFmfiZBFggYAwp9rkCSCAQDFn0OO2YIBAFufko+7ggYAxZ+wj9mCAQDFn5CN
    k4MBAFyfro2xgwYAXJ+4jCiEBgDFn9aMRoQBAFyfJY4ohAYAXJ+ujR6FBgDFn5CNAIUBAMWf/Y6T
    gwEAXJ8bj7GDBgDFn2qQk4MBAFyfiJCxgwYAxZ9DjkaEAQDFn/2OAIUBAFyfG48ehQYAXJ+SjyiE
    BgDFn7CPRoQBAFyfiJAehQYAxZ9qkACFAQBcn3CIlYUGAMWfjoizhQEAxZ9FiWmGAQBcn92JlYUG
    AFqfcIj/hgYAxJ+NiB+HAQBcn2SJiIYGAF+f3Yn7hgYAxZ/7ibOFAQDFn7OKaIYBAFyfSouVhQYA
    xZ9oi7OFAQDFnyCMaIYBAFyf0oqIhgYAyJ/7iRmHAQBcnz+MiIYGAF+fSov6hgYAyZ9pixeHAQBk
    nbCI0YcGAOyc7oiChwYARZ2SiDuIAQCOnm+IzIcGAGCdHYrOhwYAP53/iTeIAQDXnSeJ0IcGALie
    AIrRhwYA8p1CiTuIAQCBnsSJH4gBAAafNIh3hwYAr56MiDWIAQAOn6CJdIcGAFOfX4m0hwEA6Zxb
    inuHBgA/nWyLN4gBANadk4rQhwYA8J2tijyIAQCBnjCLHogBAGCdiovOhwYA6JzIi3qHBgC5nm6L
    0IcGANadAIzQhwYAD58Pi3OHBgBZn9OKsocBAP6eQooOiAEAWJ9AjLKHAQD+nq+LD4gBAFyfuIyV
    hQYAxZ/WjLOFAQBcnyWOlYUGAMWfjY1ohgEAX5+4jPqGBgDJn9aMF4cBAFyfrI2IhgYAX58ljvqG
    BgDFn0OOs4UBAMWf+o5ohgEAXJ+Sj5WFBgDFn7CPs4UBAMWfapBshgEAXJ8aj4iGBgDJn0OOF4cB
    AFufiJCKhgYAX5+Sj/qGBgDJn7GPF4cBAOWcM410hwYAXZ33jMuHBgA7ndmMNIgBALme24zQhwYA
    8J0ajDyIAQCBnp6MHogBAF+dZI7QhwYAQJ1GjjmIAQDUnWyN0IcGALieSI7QhwYA7Z2GjTyIAQCB
    ngqOHYgBAA+ffIxzhwYA/Z4cjQ+IAQBYn62NsocBAA+f6Y1zhwYA1p3ajs+HBgDwnfSOO4gBAB2d
    ko/IhwYA45wKkHaHBgA2na+PNIgBAPqda5A4iAEAuZ62j9CHBgAXnoiQzocGAIGeeI8ciAEAD59W
    j3OHBgBZnxqPsYcBAP2eiY4PiAEA/p71jxCIAQDNlIKQioEBAGeVHJEPgQEAiJX/kHiBBgAPlcKQ
    zIEGALuU/5BFggYAUpQckSSCAQDNlO+RioEBAIiVbJJ4gQYAu5RskkWCBgAPlS+SzIEGAByW2JEM
    gQEA/pX1kXaBBgC5lPWRu4IGAE+U2JHZggEA1pYekQyBAQD0lv+QdYEGAEOYHpEMgQEAYZj/kHWB
    BgD0lm2SdYEGAImX15EMgQEAa5f2kXWBBgBhmG2SdYEGABuY+ZDUggYAO5gWkT2DAQCfl+2R2oIG
    AC2YeZLYggYAZ5WKkg+BAQDNlFyTioEBAFKUipIkggEAHJZFkwyBAQD+lWOTdoEGAIiV2ZN4gQYA
    Z5X3kw+BAQC7lNmTRYIGAA+VnJPMgQYAUpT3kySCAQAclrKUDIEBAE+URZPZggEAuZRjk7uCBgBP
    lLKU2YIBANaWi5IMgQEAiZdFkwyBAQBDmIuSDIEBAGuXY5N1gQYA9Jbak3WBBgDWlviTDIEBAGGY
    2pN1gQYAiZeylAyBAQBDmPiTDIEBAE+UHpGTgwEAuJT/kLGDBgC4lG2SsYMGALiU/5AehQYAT5Qe
    kQCFAQBPlNeRRoQBALiU9pEohAYAuJRtkh6FBgB5l1eRgYMBADaXlJE9gwYA0JbqkaSDBgDOlvmQ
    IYQGADeXFpFBhAEAN5dgkPaEAQDOlmeSI4QGAMuW9pEehQYANJfYkQCFAQBPlIuSk4MBALiU2pOx
    gwYAT5T4k5ODAQBPlEWTRoQBALiUY5MohAYAT5SLkgCFAQBQlLKURYQBALqU2ZMehQYAUJT3kwCF
    AQBul6eSc4MBAC2X6pI0gwYAa5ddky6EAQBAmEKTj4MGAAOYAZPVgwEALZegk+uDBgA3l4KSRIQB
    ADSXQZMEhQEAy5Zikx+FBgAtl1eUoYQGAG6XFpTihAEAB5i3k4qEAQBDmPuTRYQGAAeYbpRBhQEA
    sJkekQyBAQDOmf+QdYEGANiY9pF1gQYA95jXkQyBAQBkmteRDIEBAEaa9pF1gQYAzpltknWBBgDw
    mGCQPYMBAK+ZH5E6gwEAXZpjkD+DAQDOmT2R0IIGAB6Z+5HTggYAAZnbkT2DAQBEmrSR0YIGAF6a
    y5E9gwEAnJl7ktSCBgAemx6RDIEBADyb/5B1gQYAi5wekQyBAQCpnP+QdYEGADybbZJ1gQYA0ZvX
    kQyBAQCzm/aRdYEGAKmcbZJ1gQYAIJspkT6DAQBBm0aR1YIGACKbjpLZggYA5ppNkh+DAQDAm8WR
    1oIGALCZi5IMgQEA95hFkwyBAQDYmGOTdYEGAGSaRZMMgQEARppjk3WBBgCwmfiTDIEBAPeYspQM
    gQEAzpnak3WBBgBkmrKUDIEBAB6bi5IMgQEA0ZtFkwyBAQCLnIuSDIEBALObY5N1gQYAPJvak3WB
    BgAem/iTDIEBAKmc2pN1gQYA0ZuylAyBAQCLnPiTDIEBACWcqpA+gwYA4pvnkIKDAQCInMiRooMG
    ABScNZI3gwYAJZwokUWEAQCNnEaRI4QGACacYZAHhQEAJ5yUkj6EAQCQnLOSIYQGACmc1JEAhQEA
    k5y1kR6FBgDNmJ6Sd4MBAI+Y4JIxgwYAb5kAk9ODAQDWmFqTLoQBAP2Z4JIwgwYAOZqdknWDAQCt
    mUGTjoMGAEWaWZMrhAEAmpiek+mDBgAImp2T6YMGAHSZtpOJhAEAm5hWlKGEBgDXmBKU5YQBAHSZ
    bZRAhQEAsZn6k0WEBgAJmlaUoYQGAEWaEpTlhAEAjZvTkjSDBgApmzqTjYMGAOya9pLRgwEAjpw0
    k6CDBgC8m16TLoQBAHqbnZPqgwYAKJxKk/eEAQCRnGmT2IQGAB+b+ZNEhAYA45q1k4mEAQB3m1aU
    oIQGAOKabZRAhQEAjpzrk1aEBgC3mxSU44QBAM2UyZSKgQEAZ5VklQ+BAQCIlUeVeIEGAA+VCZXM
    gQYAu5RHlUWCBgBSlGSVJIIBAP6V0JR2gQYAzpQ2lomBAQAQlXaWy4EGAB2WH5YMgQEA/5U9lnaB
    BgC5lNCUu4IGALqUPZa6ggYAUJQglteCAQDWlmWVDIEBAPSWR5V1gQYAa5fQlHWBBgBDmGWVDIEB
    AGGYR5V1gQYAipcelgyBAQBslz2WdoEGAGiV0ZYOgQEAiZW0lneBBgBUlNGWI4IBAL2Us5ZEggYA
    ZZWKlySCBgAilcuX5IEBAM2V45dEgQEATZZolyGBAQAVlpqXdoEGAD6WO5hKggYAIJalmC2CAQBT
    lIuX3oIBALyUapf8ggYAZpWemN+CAQCHlTWY/IIGANmWz5YLgQEA9ZazlnaBBgBGl9uXN4EBAEiY
    zpYKgQEAYpizlnaBBgDFl1+XKYEBAIeXlpd2gQYAtZY1mJOBAQB5luyX0oEGAIyXp5gvggEAIpg2
    mJWBAQDml+yX04EGAKqXPZhMggYAtpY4mL2CBgDVlqGY3YIBACOYOpi+ggYAQpijmN6CAQBQlGWV
    koMBALqUR5WxgwYAUJTWlpCDAQBQlByWSoQBALqU0JQnhAYAupSHld+EBgBQlGmV/YQBALqU/pVo
    hAYAT5TXlvyEAQBDmLKU/IQGALqU9JZygwYAUpSLl0qEAQDMlCWYeYMBAA+V4pc5gwYAaZWhmEqE
    AQD9lTiYcoMGABuWopiPgwEAu5Rrl2eEBgC5lPSW3oQGAImVN5hnhAYAEZXjl6OEBgDOlCuY3IQB
    AP+VOZjfhAYAHZajmPyEAQCNl6KYk4MBANaWophKhAEAq5c4mLGDBgD0ljiYaIQGACKYOJgnhAYA
    QJiimEWEAQBqlziY34QGAIiXopj9hAEA2JjQlHWBBgCwmWWVDIEBAEaa0JR1gQYAzplHlXWBBgDZ
    mD2WdoEGAPeYHpYMgQEAZZoelgyBAQBGmj2WdoEGAB6bZZUMgQEAPJtHlXWBBgCzm9CUdYEGAIuc
    ZZUMgQEAqZxHlXWBBgDSmx6WDIEBALObPZZ2gQYAtZnOlgqBAQCzmNuXOIEBAPSYlpd2gQYAMplf
    lymBAQDQmbOWdoEGAJ+aX5cpgQEAIJrblziBAQBimpaXdoEGAI+ZNpiVgQEAGJk9mEyCBgBUmeyX
    04EGAPmYp5gvggEAhZo9mEyCBgBnmqeYL4IBAJCZOpi+ggYAr5mjmN6CAQAim86WCoEBAD2bs5Z2
    gQYAjpvblziBAQCPnM2WCoEBAKqcs5Z2gQYADJxflymBAQDPm5aXdoEGAP2aNpiVgQEAwZrsl9OB
    BgDUm6eYL4IBAGqcNpiVgQEALpzsl9OBBgDymz2YTIIGAP6aOpi+ggYAHZujmN6CAQBrnDqYvoIG
    AIqco5jeggEAsJmylPyEBgAem7GU/IQGAI6copQNhQYAGJk5mLGDBgD6mKOYk4MBAIWaOZixgwYA
    Z5qjmJODAQAYmTiYHoUGAPqYopgAhQEAj5k5mCiEBgCtmaOYRoQBAIWaOZgehQYAZ5qjmACFAQDU
    m6OYk4MBAPKbOZixgwYA/Jo5mCiEBgAam6OYRoQBANSbo5gAhQEAaZw5mCiEBgCInKOYRoQBAPKb
    OZgehQYAT5QekWyGAQC4lPaRlYUGAE+U15GzhQEAuJQAkYqGBgC5lGySi4YGALqU9ZEBhwYAUZTY
    kSGHAQA0lx+RtoUBAMqWPpHVhQYAy5ZtkpWFBgA6l2CQXoYBABiX5JD0hgEAzJYikS2HBgAMl2KR
    cYcBAMqWtJFLhgYANpfOkWWGAQDLlpCSLocGABiXUpL1hgEAupRik5WFBgBQlESTs4UBAE+UipJt
    hgEAeZQBk3OHAQC5lD+TLocGAG2UfZP1hgEAupQblEuGBgBPlAGUZYYBAHqUbJRyhwEANJeLkrOF
    AQA1l0WTbYYBAMuW2ZOWhQYANJf0k7eFAQA0l6+UcYYBAMuWY5OLhgYADJfPknOHAQDKltqTAYcG
    ADSX+JMhhwEADZXGkHmHBgDKlAaRu4cBAPaV/5DThwYAE5YckT6IAQCElfSRz4cGAMuUapLBhwEA
    DpUxknmHBgBildWRN4gBAPaVbJLThwYAb5bDkIOHBgCuloSQyocBAK2W9JHNhwEAb5YwkoSHBgCO
    lWOT04cGAHKVRpM+iAEAE5aKkj6IAQDXlNuTzYcBABaVn5OEhwYAcJWzlD6IAQAAltuTz4cGACOW
    +pM3iAEAuZZmk8GHAQB2lp6TeYcGAJOcPpGVhQYAKZwgkbOFAQAnnGeQcIYBAJScbZLUhQYAUJze
    kHKHAQCRnByRLIcGAEScWZHzhgEAKJzdkWSGAQCUnPeRS4YGACyckJIjhwEAlZytkgKHBgArnIuS
    toUBACmcQZNuhgEAkJwhlI+FBgAnnAKUroUBAJOcJJOMhgYAK5z7kySHAQCUnBmUAocGAKycvpHG
    hwEAppwqk72HAQClnJeUvYcBAFGUsJS2hQEAupSSlNWFBgC6lP6V1IUGAFGUHJa1hQEAupSHlUqG
    BgBOlG2VZIYBALiUrZQthwYAa5TqlPWGAQC9lD2WAocGAFOUH5YjhwEALZcNlViFBgBrl8qUm4UB
    AG2Xg5VQhgEAQ5hplbOFBgAHmCSV94UBAC2XxJUOhgYAypbPlIyGBgDIlkaVAocGADGXYZUlhwEA
    LZd6lsaGBgBqlziWCocBAAeY25WuhgEAQ5gflmqGBgAHmJKWZYcBAHiU2pdxhQEAuJSVl7GFBgBP
    lM2Wc4YBAGyUXJfuhQEAjZU7mNSFBgBvlaWYtYUBANKUMphJhgEAFZXqlxCGBgC7lLOWjYYGALGU
    jJcihwYAbJTMl+KGAQBqlE6XYocBAGeVQZgjhwYAJ5WImOaGAQD/lTmYS4YGABmWpZhlhgEAppWG
    mGSHAQDzljmY1IUGANWWopi1hQEAYJg3mNSFBgBCmKGYtoUBAEOY1pYhhwYA2JZBmCSHBgCcloyY
    6YYBABmXg5hmhwEAapc5mEqGBgCDl6WYY4YBAEWYQJglhwYACJiKmOmGAQCGmIOYZ4cBABSVDZWD
    hwYAjZXQlNOHBgDUlE6Vx4cBAACWSJXPhwYAIpZnlTeIAQCGlTyWzocGAMmUsJbAhwEAEJV5lnqH
    BgBllR6WN4gBAHaWCJV6hwYAuZbIlLyHAQCzljeWw4cBAHSWeJZ+hwYAZpWLl9iHBgAllU2XHogB
    APqVspbQhwYAE5bLljyIAQCklcuXHogBAMmUKZjAhwEAC5Xnl36HBgA/liuYwYcBAC2XMZd9hwYA
    aZftlsKHAQDWlo6X2IcGAJiWUpchiAEAFpfQlxuIAQBCmIqX2YcGAAOYSZceiAEAgJjKlx+IAQB7
    lueXfYcGAOmX5Zd+hwYArpcqmMKHAQCbmA2VWIUGANeYyZSchQEAdJkklfeFAQDXmICVU4YBAAma
    DZVYhQYARZrJlJyFAQCwmWmVs4UGAEWagJVThgEAm5jElQ+GBgAJmsSVD4YGAHSZ25WuhgEAm5h7
    lsWGBgDXmDaWCYcBAHWZkpZlhwEAsJkflmqGBgAJmnuWxoYGAEWaN5YKhwEAdpsNlVeFBgAem2iV
    s4UGAOKaJJX4hQEAtJvIlJmFAQCMnGqVsoUGACWcppR1hgEAS5wplfOFAQC0m4KVVIYBAHabxJUP
    hgYAkpyPlI2GBgAmnHCVF4cBAI6cjpX2hgYAHpsglmqGBgDimtuVroYBAHabe5bGhgYA45qTlmaH
    AQCNnA+WeYYGALSbN5YIhwEATJyWlmWHAQCPmTiYlYUGAK2ZopizhQEAZZqimGiGAQCxmdaWIYcG
    ANaYN5hKhgYA75ijmGOGAQBzmYiY5oYBAISaOZiIhgYAsZlBmCSHBgDvmYaYZYcBAPyaOZiVhQYA
    GpujmLOFAQDSm6OYaIYBAGmcOZiVhQYAiJyjmLOFAQAem9eWIocGAIyc1pYhhwYA/Jo9mPqGBgAb
    m6eYF4cBAPGbOpiIhgYAapw8mPuGBgCInKaYGIcBAKKc/ZW8hwEAnJgwl32HBgDYmOyWwYcBAHGZ
    TJcgiAEACZoxl36HBgBGmu6WwocBALCZjJfZhwYA75nNlx2IAQAamSqYwocBAFaZ5pd+hwYAh5o1
    mLaHAQB1mzWXfocGAB2bmZfRhwYA35pelxyIAQBdm96XEYgBAK+b9JbGhwEAi5yUl9GHBgBMnFmX
    GogBAMCa7ZdzhwYALpzsl3OHBgDxmzaYsocBAPidHZEMgQEAFp4AkXaBBgAgnfaRdYEGAD6d15EM
    gQEAjJ72kXiBBgAWnm2SdoEGAEefBpGKgQEABZ/GkMyBBgCtntiRD4EBAEefc5KKgQEAwp/YkSSC
    AQBZn/aRRYIGAAWfM5LMgQYAW58AkbuCBgDFnx2R2YIBAFufbZK7ggYA+J2KkgyBAQA+nUWTDIEB
    ACCdY5N1gQYAjJ5jk3iBBgD4nfiTDIEBAD6dspQMgQEAFp7ak3aBBgCtnkaTD4EBAMKfRpMkggEA
    WZ9jk0WCBgBHn+GTioEBAK2es5QPgQEABZ+hk8yBBgDCn7OUJIIBAMWfipLZggEAW5/ak7uCBgDF
    n/iT2YIBAMWf15GTgwEAXJ/2kbGDBgBcn/+QKIQGAMWfHpFGhAEAXJ9tkiiEBgDFn9eRAIUBAFyf
    9pEehQYAxZ9Fk5ODAQBcn2OTsYMGAMWfspSTgwEAxZ+LkkaEAQDFn0WTAIUBAFyfY5MehQYAXJ/a
    kyiEBgDFn/iTRoQBAMWfspQAhQEAIJ3QlHWBBgD4nWWVDIEBAIye0ZR4gQYAFp5HlXaBBgAhnT2W
    doEGAD+dHpYMgQEAjJ48lniBBgBIn06ViYEBAAWfDpXMgQYAWZ/RlEWCBgCtnh6WD4EBAEqfsJaG
    gQEAwp8eliOCAQBZnzyWRIIGAASfeJbNgQYAW59HlbuCBgDFn2WV2YIBAPydzJYLgQEA+pzZlzaB
    AQA7nZWXdYEGAHidXZcngQEAF56zlnaBBgBtnsyXKoEBAK2ejJdugQYAXp07mEmCBgCaneqX0YEG
    AECdpZgrggEA1J0ymI+BAQCunkGYJIIGAHGeiJjkgQEA1p05mLyCBgDvnaWY1oIBAO2eTpcngQEA
    qJ9Ml+KBAQBjn4uXI4IGAEufKJiGgQEACZ/nl8iBBgCpn8uXYoIBAFqfs5a6ggYAx5/LltOCAQDv
    noWYY4IBAE2fKpj9ggEAXJ/QlLGDBgDEnx6WkoMBAFufPJawgwYAXJ9HlSiEBgDFn2WVRoQBAFyf
    0JQehQYAxZ8elv+EAQBbnz2WHoUGAF+dOZiwgwYAQJ2imJKDAQCwnkGYlYMGAHSei5hYgwEAX505
    mB6FBgBAnaKY/4QBANWdOJgnhAYA7p2lmECEAQBznouYxYQBAK+eQZgChQYArZ9Rl1eDAQBjn42X
    lYMGAKafzpfVgwEACJ/mlzmDBgDynoOY1oMBAFufspYnhAYAx5/LlkCEAQCtn1GXxYQBAGOfjZcC
    hQYApZ/Ol0OFAQBNnyqYbIQBAAif5penhAYA8Z6DmEOFAQBcn/+QlYUGAMWfHZGzhQEAXJ9tkpWF
    BgDFn9WRaYYBAFqf/5D/hgYAxJ8dkR+HAQBcn/SRiIYGAF+fbJL7hgYAxZ+LkrOFAQDFn0KTaIYB
    AFyf2pOVhQYAxZ/4k7OFAQDFn7CUaIYBAFyfYZOIhgYAyJ+KkhmHAQBfn9qT+oYGAMmf+JMXhwEA
    7Jx9kYKHBgBknT+R0YcGAEWdIZE7iAEAjp7/kMyHBgBgnaySzocGAD+djpI3iAEA1522kdCHBgC4
    npCS0YcGAPKd0ZE7iAEAgZ5Tkh+IAQAGn8OQd4cGAE+fi5C6hwEAr54ckTWIAQBTn+6RtIcBAA6f
    L5J0hwYA6ZzqknuHBgDWnSKT0IcGAPCdPJM8iAEAYJ0ZlM6HBgDonFeUeocGAD+d+5M3iAEAuZ79
    k9CHBgCBnsCTHogBAFmfYpOyhwEA/p7Rkg6IAQAPn56Tc4cGAP6eP5QPiAEAXJ9HlZWFBgDFn2WV
    s4UBAMWfHZZohgEAXJ/PlIiGBgBfn0eV+oYGAMmfZpUXhwEAXJ88loiGBgBCnaOYbYYBANWdOJiU
    hQYA752kmK+FAQB5npCYOYYBAKqei5cjhwYAX505mIuGBgCxnkGYc4YGANadNpgAhwYA9J2gmCGH
    AQBbn7OWlIUGAMafzZavhQEAsp9YlziGAQBNnyuY2oUBAAif5pcVhgYAY5+Ql3OGBgCdn9SXuoYB
    AF6ftJb6hgYAyJ/SlhiHAQDqns2XZocBAPWefJi6hgEAXZ2GlcuHBgA7nWmVNIgBANadkJTQhwYA
    uZ5rldCHBgDwnaqUPIgBAIGeLZUeiAEA5ZzDlXWHBgBCndaWOogBANWd/JXQhwYA750WljuIAQCK
    nqSWJIgBAA+fC5VzhwYAWJ/QlLKHAQD9nqyVD4gBAFifPZayhwEAD595lnOHBgBgnfSW0IcGAMqc
    2JcTiAEAvJ7cltCHBgDXnWqXzocGAPSdi5c3iAEAm53il3mHBgBhnSqYvIcBAAWfJJcCiAEA
    """
}
