//
//  IntermediateUnit.swift
//  MolecularRendererApp
//
//  Created by Philip Turner on 4/12/24.
//

import Foundation
import HDL
import MM4
import Numerics

struct IntermediateUnit {
  var propagate: [Rod]
  var generate: [Rod]
  var driveWall: DriveWall
  
  var holePatterns: [HolePattern] = []
  var rods: [Rod] {
    var output: [Rod] = []
    output.append(contentsOf: propagate)
    output.append(contentsOf: generate)
    return output
  }
  
  init() {
    // Create the source rod.
    var boundsSet: [SIMD2<Float>] = []
    boundsSet.append(SIMD2(2, 6))
    boundsSet.append(SIMD2(10, 14))
    boundsSet.append(SIMD2(16, 20))
    
    let lattice = Self.createLattice(boundsSet: boundsSet)
    var rod = Rod(lattice: lattice)
    rod.rigidBody.rotate(angle: -.pi, axis: [0, 1, 0])
    do {
      let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
      var center = rod.rigidBody.centerOfMass
      center = SIMD3(-center.x, center.y, center.z)
      center.x += 22 * latticeConstant
      rod.rigidBody.centerOfMass = center
    }
    
    // Create the logic rods.
    var holeOffsets: [SIMD3<Float>] = []
    
    do {
      var offset = SIMD3<Float>(0, 2.75 + 0.5, 0.5)
      var source = rod
      let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
      source.rigidBody.centerOfMass += SIMD3(offset) * latticeConstant
      source.rigidBody.centerOfMass += SIMD3(0, 0.85, 0.91)
      propagate = Self.createLayers(source: source)
      
      offset += SIMD3(0, 1.5, 1.5)
      holeOffsets.append(offset)
    }
    
    do {
      var offset = SIMD3<Float>(0, 2.75 + 0.5, 0.5 + 6)
      var source = rod
      let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
      source.rigidBody.centerOfMass += SIMD3(offset) * latticeConstant
      source.rigidBody.centerOfMass += SIMD3(0, 0.85, 0.91)
      generate = Self.createLayers(source: source)
      
      offset += SIMD3(0, 1.5, 1.5)
      holeOffsets.append(offset)
    }
    
    // Create the hole patterns.
    for offset in holeOffsets {
      // Emulate the presence of other layers in the logic unit.
      for layerID in -1...2 {
        let y = 6 * Float(layerID)
        holePatterns.append(
          Self.createHolePattern(offset: SIMD3(0, y, 0) + offset))
      }
    }
    
    // Create the ramp patterns.
    var rampPatterns: [RampPattern] = []
    for offset in holeOffsets {
      // Emulate the presence of other layers in the logic unit.
      for layerID in -1...2 {
        let y = -3.25 + 6 * Float(layerID)
        rampPatterns.append(
          Self.createRampPattern(offset: SIMD3(22, y, 0) + offset))
      }
    }
    driveWall = Self.createDriveWall(patterns: rampPatterns)
  }
}

// MARK: - Rods

extension IntermediateUnit {
  // Create a lattice for a logic rod.
  static func createLattice(boundsSet: [SIMD2<Float>]) -> Lattice<Hexagonal> {
    Lattice<Hexagonal> { h, k, l in
      let h2k = h + 2 * k
      Bounds { 32 * h + 2 * h2k + 2 * l }
      Material { .elemental(.carbon) }
      
      Volume {
        let pattern = Self.createDriveWallInterface()
        pattern(h, h2k, l)
      }
      
      for bounds in boundsSet {
        let pattern = Self.createKnobPattern(bounds: bounds)
        Volume {
          pattern(h, h2k, l)
        }
      }
    }
  }
  
  // Create an interface to the drive wall.
  static func createDriveWallInterface() -> KnobPattern {
    return { h, h2k, l in
      Concave {
        Concave {
          Origin { 1 * h2k }
          Plane { h2k }
          Origin { 1 * h }
          Plane { h2k - 3 * h } // k - h
        }
        Convex {
          Origin { 1.5 * h2k }
          Plane { h2k }
          Origin { 0.5 * h }
          Plane { -h }
        }
      }
      Replace { .empty }
    }
  }
  
  // Accepts bounds in multiples of the cubic diamond lattice constant.
  static func createKnobPattern(bounds: SIMD2<Float>) -> KnobPattern {
    let cubicConstant = Constant(.square) { .elemental(.carbon) }
    let hexagonalConstant = Constant(.hexagon) { .elemental(.carbon) }
    let shrunkBounds = bounds + SIMD2(0.125, -0.125)
    let scaledBounds = shrunkBounds * cubicConstant / hexagonalConstant
    
    return { h, h2k, l in
      Concave {
        Concave {
          Origin { scaledBounds[0].rounded(.down) * h }
          Plane { h }
        }
        Concave {
          Origin { 0.5 * h2k }
          Plane { -h2k }
        }
        Concave {
          Origin { scaledBounds[1].rounded(.up) * h }
          Plane { -h }
        }
      }
      Replace { .empty }
    }
  }
  
  // Spawns the logic rods for all Y layers, from a single source rod.
  static func createLayers(source: Rod) -> [Rod] {
    let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
    let spacing = 6 * latticeConstant
    
    var output: [Rod] = []
    for layerID in 0..<2 {
      var rod = source
      rod.rigidBody.centerOfMass.y += spacing * Double(layerID)
      output.append(rod)
    }
    return output
  }
}

// MARK: - Housing

extension IntermediateUnit {
  static func createHolePattern(offset: SIMD3<Float>) -> HolePattern {
    { h, k, l in
      Origin { offset[0] * h + offset[1] * k + offset[2] * l }
      
      Concave {
        Concave {
          Plane { k }
          Plane { l }
        }
        Concave {
          Origin { 4.25 * k + 4 * l }
          Plane { -k }
          Plane { -l }
        }
      }
      
      Replace { .empty }
    }
  }

  static func createRampPattern(offset: SIMD3<Float>) -> RampPattern {
    { h, k, l in
      Origin { offset[0] * h + offset[1] * k + offset[2] * l }
      
      Concave {
        Concave {
          Plane { k }
          Plane { l }
        }
        Concave {
          Origin { 4 * l }
          Plane { -l }
        }
        Concave {
          Plane { -h - k }
          Origin { 2 * -h }
          Plane { -h }
        }
      }
      
      Replace { .empty }
    }
  }
  
  static func createDriveWall(patterns: [RampPattern]) -> DriveWall {
    var driveWallDesc = DriveWallDescriptor()
    driveWallDesc.dimensions = SIMD3(22, 17, 14)
    driveWallDesc.patterns = patterns
    driveWallDesc.patterns.append { h, k, l in
      Origin { (22 - 5.5) * h }
      Plane { -h }
      Replace { .empty }
    }
    driveWallDesc.patterns.append { h, k, l in
      Origin { (22 - 1) * h }
      Plane { h }
      Replace { .empty }
    }
    driveWallDesc.surfaceAtoms = Self.driveWallString
    
    let latticeConstant = Double(Constant(.square) { .elemental(.carbon) })
    var driveWall = DriveWall(descriptor: driveWallDesc)
    driveWall.rigidBody.centerOfMass.x += (5.5 + 1) * latticeConstant
    return driveWall
  }
}

extension IntermediateUnit {
  static let driveWallString: String? = """
    dQ8AAAAAAABcmByAHIABAKaX0YAcgAEAp5ccgNGAAQDYmNeAC4AGAPaYt4ChfwEA2JgLgNeABgD2
    mKF/t4ABAJuYX4BfgAYAYphOgQuABgBCmGuBoX8BAJWXToHXgAYA6pcQgV+ABgAsl2uBt4ABAM6Z
    ToEIgAYA2ZhDggiABgCxmWyBnn8BAPeYJoKefwEAYpgLgE6BBgCWl9eAToEGAOqXX4AQgQYAQpih
    f2uBAQAsl7eAa4EBAM6ZCIBOgQYA2ZgIgEOCBgCxmZ5/bIEBAPeYn38lggEAlJdEgk6BBgCTl0mB
    Q4IGACqXJoJrgQEAKZdngSaCAQDImRyAHIABAEWa14AKgAYAY5q3gKF/AQBFmgqA14AGAGOaoX+3
    gAEACJpfgF+ABgA1mxyAHIABANCbt4ChfwEAspvXgAqABgDQm6F/t4ABALKbCoDXgAYAdZtfgF+A
    BgBGmkSCCIAGAB6bbIGefwEAZJolgp9/AQA8m06BCIAGAIuca4GefwEA0Zslgp9/AQCzm0SCCIAG
    AEaaCYBDggYAHpuef2yBAQBlmp9/JIIBADybCIBOgQYAi5yef2uBAQDRm59/JYIBALObCIBEggYA
    p5c9ghyAAQBimLqCCoAGAEKY2IKhfwEAlZe6gteABgDql32CX4AGACyX2IK2gAEAzpm7ggiABgCw
    mdmCn38BAPeYk4OefwEAqJeqgxyAAQBCmEWEoX8BAGOYKIQKgAYA6pfqg16ABgAtl0aEtYABAJaX
    KITWgAYA2ZixgwiABgCwmUaEn38BAPeYAIWefwEAzpkohAiABgCNl9SCLIIGAEmXGYP0gQEAJ5eZ
    g2WBAQCUl7KDTIEGACiXBYVngQEAQ5d+hPmBAQCTl0OEMIIGAB2b2YKffwEAZJqTg59/AQA8m7uC
    CIAGAIuc2YKefwEA0ZuTg59/AQBGmrGDCIAGAB6bRoSffwEAZJoAhZ9/AQCzm7GDCIAGADybKIQI
    gAYAi5xGhJ5/AQDRmwCFn38BAKiXG4A8ggEAY5gLgLqCBgCWl9WAuoIGAOuXXoB8ggYAQpihf9eC
    AQAul7OA2IIBANCZCIC5ggYAt5mcf9OCAQAxmbZ/WIMBAKKXAYK9ggEA5pfBgX2CBgBDl66BToMB
    APyXc4DJgwEAQZi3gI6DBgBXmBqAaoQBAJyX2IBthAEAspjAf9SDAQD1mAGAlIMGALeZnX9AhAEA
    0JkJgCeEBgAvmbh/xIQBAJyYXoCmhAYAS5c2gdKDAQCNl3OBjYMGAD+YOIJygwYA65fVgd2DBgDl
    lxqBpoQGAKqXG4IahAEAV5fHgbyEAQDEmR+Co4MGABmZGIJphAYAHpuff9mCAQBlmp9/koMBADyb
    CIC7ggYAi5yef9mCAQDRm59/k4MBAEaaCYCwgwYAHpuff0aEAQBlmp9//4QBALObCICxgwYAPJsI
    gCiEBgCLnJ5/RoQBANGbn38AhQEAQZodgiKEBgAzmyOCpoMGAL6bI4IwhAYARpeSgmiCAQBAmLuC
    74IGAKqXY4PTggEA65cmg4yCBgB9mAiDJYMBAMSZ7ILWggYANJnKgoGDAQBumYWCPIMGAP+YmoM7
    gwEAWJcAhHaCAQDvl6SEhIIGAGiYaITUggYASphKhD6DAQAZmbKDz4IGAI+ZKITPggYAfZhugr+D
    AQBMmIiCAYUBAP+YhIJQhAEA3JqHgj6DBgCfmsuCgYMBADOb74LaggYAMJx9gjSDBgDum7+CdYMB
    AEGabIPUggYAXpqMgz2DAQAim1GEPYMBAK6ZR4Q5gwEAbpoHhT2DAQC+m3qD2oIGAEObboTUggYA
    JpzRgz6DBgDimw6EgYMBAF6ahoJDhAEAIZuGggaFAQAmnIeCiIQGACecTYRBhAEAJpyNgwaFAQCi
    nByAHIABAD6duICkfwEAHp3YgA2ABgA+naR/uIABAB6dDYDYgAYA4ZxfgF+ABgDpndiA2IAGAFKe
    uIC4gAEAqJxOgQmABgBAnSeCoX8BAB+dRIIKgAYAl50VgV+ABgDanVWBHIABAOydRILXgAYAVZ4n
    greAAQConAmAToEGAJedX4AVgQYAQJ2hfyeCAQAfnQqARIIGANqdHIBVgQEA7J3XgESCBgBVnreA
    J4IBAO6dToFOgQYA7p1EgkSCBgBYnmuBa4EBAFieJYIlggEAqJy7ggiABgBAnZSDoX8BAJedgYJf
    gAYA2p3BghyAAQBVnpSDt4ABAB+dsYMKgAYAqZwohAiABgBAnQGFoX8BAJed74NfgAYA2p0vhByA
    AQDsnbGD14AGAFWeAYW3gAEA7p27gk6BBgBYntmCbIEBAFiek4MlggEA7p0ohE6BBgDunbGDRIIG
    AFieRoRsgQEAWJ4AhSWCAQConAiAu4IGAJedX4CBggYAQJ2hf5SDAQDanRyAwYIBAFWet4CUgwEA
    7p1OgbuCBgBYnmyB2YIBAFieJYKTgwEAH50KgLGDBgCXnV+A74MGAKmcCIAohAYAQJ2hfwGFAQDs
    ndeAsYMGANqdHIAvhAEAVZ63gAGFAQDunUSCsYMGAO6dToEohAYAWJ5sgUaEAQBYniWCAIUBAO6d
    u4K7ggYAWJ7ZgtmCAQBYnpODk4MBAO6dKIS7ggYAWJ5GhNmCAQBYngCFk4MBAIqc74IwhAYA7p27
    giiEBgBYntmCRoQBAFiek4MAhQEAipx6g6aDBgCPnG6EIYQGAO6dsYOxgwYA7p0ohCiEBgBYnkaE
    RoQBAFieAIUAhQEAqJcYhRyAAQBCmLKFoX8BAGOYlYUKgAYA6pdYhV6ABgAtl7OFtYABAJaXlYXW
    gAYA2ZgehQiABgCwmbOFn38BAM6ZlYUIgAYAqJeFhhyAAQBCmCCHoX8BAGOYAocKgAYALZchh7WA
    AQCWlwOH1oAGAOqXxYZegAYA2ZiLhgiABgD3mG2Gnn8BALCZIYeffwEAzpkDhwiABgCTlx+FTYEG
    AEaX74X3gQEAk5exhS+CBgCTl42GTYEGACeXc4ZmgQEAl5cfhzKCBgBGmh6FCIAGAB6bs4WffwEA
    s5sehQiABgA8m5WFCIAGAIucs4WefwEARpqLhgiABgBkmm2Gn38BAB6bIYeffwEA0Ztthp9/AQCz
    m4uGCIAGADybA4cIgAYAi5wgh55/AQCol/KHHIABAGOYb4gKgAYAlpdwiNaABgDqlzKIXoAGANmY
    +IcIgAYA95jbh55/AQDOmXCICIAGAEKYjYihfwEAqJdfiRyAAQAtl42ItYABAOqXn4legAYA2Zhm
    iQiABgCwmY6In38BAPeYSImefwEAlJf6h0yBBgAol9+HZoEBAEqXXof8gQEAjJeMiCiCBgCTl2eJ
    TIEGAECXx4jtgQEAJ5dOiWWBAQBGmvmHCIAGAGSa2oeffwEA0Zvah59/AQCzm/mHCIAGADybcIgI
    gAYARppmiQiABgAem46In38BAGSaSImffwEAi5yOiJ5/AQDRm0iJn38BALObZokIgAYAsZffhM6C
    AQBUl3CFc4IBAPCXEIaFggYAaJjUhdWCBgBKmLWFPoMBANuY4ITSggYA1ZnchdSCBgD6mP+EO4MB
    ALeZv4U/gwEAspdMhs+CAQBYl96Gd4IBAHSYSYfbggYAWZgsh0WDAQDamEyG04IGALGZJYfZggYA
    9Jhkhj+DAQBzmeaGH4MBAIyaJYXTggYAxJvwhNaCBgANm6aF1oIGAFeaXYbWggYAkZtxhcuDAQDU
    m7aFj4MGAO6bEYVyhAEANJxShbCEBgA3m8yFaYQBAHubEIalhAYA2ZophsuDAQAjmt+Gy4MBAGea
    JIePgwYAf5qEhmiEAQDImTuHaIQBAMOayIalhAYAHZttho+DBgCzl7aH0YIBAPaXfYeJggYATZdK
    iGuCAQBDmJKI24IGAAGYVYgggwEA7JjLh9eCBgCUl2WJu4IGACuXRonaggEAbJmXh8uDAQCwmdqH
    j4MGALaYTYjLgwEA+ZiRiI+DBgARmfKHaYQBAFWZNoilhAYA/ZcEicuDAQBCmEeJj4MGAEuXxonT
    gwEAWZiqiGmEAQCdl2eJbYQBAOWXqYmmhAYAnZjuiKWEBgAMmn+HpYQGAB+dH4UKgAYAqZyVhQiA
    BgCXnVyFX4AGANqdnIUcgAEA7J0fhdeABgBAnW6GoX8BAB+djIYKgAYAqZwDhwiABgCXncmGX4AG
    ANqdCYccgAEA7J2MhteABgBVnm6Gt4ABAO6dlYVOgQYA7p0ehUSCBgBYnrOFbIEBAO6dA4dOgQYA
    7p2LhkSCBgBYnm2GJYIBAFieIIdsgQEAQJ3ch6F/AQAfnfmHCoAGAKmccIgIgAYAl502iF+ABgDa
    nXaIHIABAOyd+YfXgAYAVZ7ch7eAAQBAnUmJoX8BAB+dZokKgAYAl52kiV+ABgDaneSJHIABAOyd
    ZonXgAYAVZ5JibeAAQDunXCIToEGAO6d+YdEggYAWJ7ahyWCAQDunWaJRIIGAFiejohsgQEAWJ5I
    iSWCAQDunZWFu4IGAFies4XZggEA7p0Dh7uCBgBYnm2Gk4MBAFieIYfZggEAjZzwhKCDBgDunR6F
    sYMGAO6dlYUohAYAWJ60hUaEAQDunYuGsYMGAFiebYYAhQEA7p0DhyiEBgBYniGHRoQBAO6dcIi7
    ggYAWJ7ah5ODAQBYno6I2YIBAFieSImTgwEA7p35h7GDBgBYntqHAIUBAO6dcIgohAYA7p1mibGD
    BgBYno6IRoQBAFieSIkAhQEAQJi7gP2EBgD8l3iAOoUBAFiYGoDXhQEAnZfXgNiFAQD0mAKAAoUG
    ALKYwH9ChQEA0JkJgJSFBgC3mZ1/rYUBAJ2YXoAThgYAkpeAgf2EBgBEl0eBOoUBAGmYHoIfhQYA
    8ZfRgV2FBgDllxiBE4YGALSXG4KbhQEAj5kYgt+EBgDbmBuCl4UGAPyXd4CmhgEAQZi6gGqGBgBY
    mBmARYcBAKGX0YBDhwEAspjAf7CGAQD1mAKAb4YGADCZuH8yhgEAt5mdfxuHAQDQmQmAAYcGAEeX
    QIGphgEAkpd7gWuGBgBRl8CBLIYBAGiYHoKKhgYArpcXggKHAQDwl8+ByIYGAM2ZGoKLhgYA2pgc
    ggKHBgBGmgmAHYUGAB6bn3+zhQEAs5sIgB6FBgA8mwiAlYUGAIucnn+zhQEAhJoYgtSFBgBBmx2C
    I4UGAMGbH4KghQYARpoJgIuGBgBlmp9/bIYBAB6bn38hhwEA0Zuff22GAQCzmwiAi4YGADybCIAD
    hwYAi5yefyCHAQBEmhmCAYcGAPqaGYJKhgYA1ZsigiWHBgD7mISCtoUBAEqYiIJshgEAr5mDgm2G
    AQD0mIiCGocBAK2ZgoL9hAEAZpqCgraFAQDim8uCxYQBACichYL3hQYAJpxMhKuFAQBdmoaCGIcB
    ABGbhYJjhgEA45vIgjOGAQCVm2iC54YBACWci4N2hgEAJJxShBCHAQBCmLmA2IcGAP6XdoAViAEA
    9ZgBgN2HBgAwmbd/oIcBAJ2YXYCAhwYAs5jAfx6IAQDPmQmAcIgGAIuXb4HZhwYA5pcUgX+HBgBH
    l7CBmocBAEOYI4LbhwYARZcvgReIAQCNlyqCiogGALKZIoLchwYAWpgVgLaIAQCfl9CAtogBAKeX
    G4BiiQEA6pdfgKCJBgDZmAiAaokGALGZn3+OiAEA95ief0yJAQCdmFuA8ogGAJOXTYFsiQYA5ZcS
    gfKIBgA9l/GBw4gBACeXZ4FRiQEARpoIgPmHBgBkmp9/24cBANGbn3/ahwEAs5sIgPmHBgA8mwiA
    cIgGAB+bIoLbhwYARpoIgGaJBgAem59/jogBAGSan39IiQEAi5yef46IAQDRm59/SIkBALObCIBm
    iQYAA5hpgpyHAQBUl3CCRYgBAEKY2oKSiAYAAZgag02IAQDXmMKC84cBAHeZaIKbhwEAmph+gjeI
    BgCymdiCkogGAHeZGoNMiAEA75icgy6IAQA+mEaENIgBAGCYKISdiAYA1pizg5qIBgCPmWeEm4gG
    AJSXu4JmiQYAKpfZgkiJAQCil7CDrogBAOiX64PxiAYALJdGhEiJAQCVlymEaIkGAEiawILzhwEA
    45pngpqHAQAKmn2CNogGANSb2YLahwYAkpscg5mHAQANm+mClIgGAG+ai4MuiAEArplJhDGIAQCM
    mmuDl4gGACKbPIQtiAEAYZr+hDGIAQBGnMuDmYcBAO2bZ4TzhwEAxJugg5SIBgBCmyGEl4gGADCc
    pYQ2iAYAH50KgB+FBgCXnV+AXIUGAKmcCICVhQYA7J3XgB+FBgDanRyAnIUBAO6dRIIehQYA7p1O
    gZWFBgBYnmyBs4UBAECdoX9uhgEAH50KgIyGBgCpnAiAA4cGAJedX4DJhgYA7J3XgIyGBgBVnreA
    boYBANqdHIAJhwEA7p1EgouGBgBYniWCbYYBAO6dToEDhwYAWJ5sgSCHAQCNnOyCoYUGAO6du4KV
    hQYAWJ7ZgrOFAQCPnGyDJIUGAI+cbYSPhQYA7p2xgx6FBgDunSiElYUGAFieRoS0hQEAjZzpghSH
    BgBYnpODbYYBAO6du4IDhwYAWJ7ZgiGHAQCOnGuDk4YGAJCcboT6hgYA7p2xg4uGBgBYngCFbYYB
    AO6dKIQDhwYAWJ5GhCGHAQBAnaF/3IcBAB+dCoD5hwYAqZwIgHCIBgCXnV+ANogGAOyd14D5hwYA
    VZ63gNyHAQDanRyAdogBAO6dRIL5hwYAWJ4lgtqHAQDunU6BcIgGAECdoX9JiQEAH50KgGaJBgCX
    nV+ApIkGAOyd14BmiQYAVZ63gEmJAQDanRyA5IkBAO6dRIJmiQYAWJ5sgY6IAQBYniWCSIkBAFie
    k4PahwEA7p27gnCIBgCLnI6D24cGAO6dsYP5hwYAWJ4AhdqHAQDunSiEcIgGAFie2YKOiAEAWJ6T
    g0iJAQDunbGDZokGAFieRoSOiAEAWJ4AhUiJAQCRm3KFPoUBANabs4UAhQYA75sQheCFAQA0nFOF
    HYYGADabzIXXhQEAe5sQhhOGBgDamimGOYUBAGeaJIf9hAYAI5rghjmFAQB/moSG1oUBAMiZO4fW
    hQEAw5rIhhKGBgAfm2yG/YQGAJCbcoWqhgEA1Zu0hW2GBgDsmxmFQocBADWbzoVDhwEA2pophqaG
    AQAjmuCGpoYBAGeaJIdqhgYAfpqFhkOHAQDImTuHQ4cBAB6bbYZqhgYAsJnbh/2EBgBsmZeHOYUB
    APmYkoj9hAYAtZhOiDmFAQARmfKH1oUBAFWZNogShgYAQZhKif2EBgD9lweJOYUBAESX1ok6hQEA
    WZipiNaFAQCel2aJ2IUBAOaXp4kThgYAnpjtiBKGBgBsmZeHpoYBALCZ24dqhgYAtZhOiKeGAQD5
    mJKIaoYGABGZ8odDhwEA/ZcGiaeGAQBCmEmJaoYGAEqXy4mshgEAWZipiEeHAQCll1SJUIcBAAya
    f4cShgYA8Zf4hViIAQA2mLiFmIgGAP+Y94QviAEAGZndhJqIBgBvmHuFS4gBAK6ZsYUxiAEAzpmV
    hZqIBgA9mB2HM4gBAGCYAoeciAYAFZlAh/CHAQDXmIuGmogGAPKYa4YwiAEAnJcXhbSIAQDhl1iF
    9IgGAJGXlYVsiQYAJ5e0hU6JAQCgl42GrogBACyXIYdIiQEAlZcDh2iJBgDpl8aG8YgGAIKa0oXw
    hwEARZoehZqIBgDCmhKGNYgGADebGoXzhwEAL5xbhYCHBgB5mxKGgIcGAHmbW4U1iAYAypmHhvOH
    AQDCmsiGgIcGAAuayIY1iAYAWZj5h/SHAQBCmKWIf4gGAFWZNYiAhwYAVZl/hzWIBgCdmDmINogG
    AEOYM4nxhwYA6peXiYyHBgBDl72JHYgBAJ6Y7IiEhwYApJf+h6iIAQCWl3KIZIkGAOmXPYjpiAYA
    LJeRiEaJAQCgl2SJsYgBAOaXp4nsiAYAK5cBikSJAQAsl0SJ/4kBAAuaf4eAhwYAj5zthBCFBgDu
    nR6FHoUGAO6dlYWVhQYAWJ60hbSFAQDunYuGHoUGAO6dA4eVhQYAWJ4hh7OFAQCQnO2EfYYGAO6d
    HoWLhgYA7p2VhQOHBgBYnrSFIYcBAO6di4aLhgYAWJ5thm2GAQDunQOHA4cGAFieIYchhwEA7p35
    hx6FBgDunXCIlYUGAO6dZokehQYAWJ6OiLOFAQDunfmHi4YGAFie2odthgEA7p1wiAOHBgDunWaJ
    i4YGAFieSIlthgEAWJ6OiCGHAQDunR6F+YcGAO6dlYVwiAYA7p2LhvmHBgBYnm2G2ocBAO6dA4dw
    iAYA7p0ehWaJBgBYnrOFjogBAO6di4ZmiQYAWJ5thkiJAQBYniGHjogBAO6d+Yf5hwYAWJ7ah9qH
    AQDunXCIcIgGAO6dZon5hwYAWJ5IidqHAQDunfmHZokGAFie2odIiQEA7p1miWaJBgBYno6IjogB
    AFieSIlIiQEAQpj6iaF/AQBjmN2JCoAGAKeXzYocgAEALZf7ibWAAQCWl92J1oAGAOqXDYtfgAYA
    sJn7iZ9/AQD3mLWKnn8BAM6Z3YkIgAYA2ZjTigiABgBCmGeLoX8BAGKYSosKgAYAqJc6jByAAQAs
    l2eLtoABAJWXSovXgAYAsJlpi59/AQDOmUqLCIAGANmYQIwIgAYA95gijJ5/AQCUl9OKToEGACqX
    tYprgQEAKZf4iSWCAQCSl9mJQ4IGAJSXQoxMgQYASJepi/SBAQCNl2OLLIIGACeXKYxlgQEAHpv7
    iZ9/AQBkmrWKn38BAEaa04oIgAYAPJvdiQiABgCLnPuJnn8BANGbtYqffwEAs5vTigiABgAem2mL
    n38BAEaaQIwIgAYAZJoijJ9/AQA8m0qLCIAGAIucaIuefwEA0ZsijJ9/AQCzm0CMCIAGAEKY1Yyh
    fwEAY5i3jAqABgCol6eNHIABAC2X1oy1gAEAlpe4jNaABgDql3qMXoAGALCZ1oyffwEAzpm4jAiA
    BgDZmK2NCIAGAPeYkI2efwEAY5gkjgqABgBCmEKOoX8BAJaXJY7WgAYA6pfnjV6ABgAtl0OOtYAB
    AM6ZJY4IgAYA2ZgbjwiABgCwmUOOn38BAPeY/Y6efwEAk5evjU2BBgBDlw6N+YEBAJOX0owwggYA
    KJeVjWeBAQCTlxyPTYEGAJOXQY4vggYARpd+jveBAQAnlwOPZoEBAB6b1oyffwEARpqujQiABgBk
    mpCNn38BADybuIwIgAYAi5zVjJ5/AQDRm5CNn38BALObro0IgAYARpobjwiABgAem0OOn38BAGSa
    /Y6ffwEAPJsljgiABgCLnEOOnn8BANGb/Y6ffwEAs5sbjwiABgDml1GKfYIGAEaXIotoggEAopeQ
    ir2CAQBDlz2KToMBAG6ZFYs8gwYA65e1i4yCBgBAmEqL74IGAKqX8ovTggEAfZiYiyWDAQDEmXyL
    1oIGABmZQozPggYANJlai4GDAQD/mCmMO4MBAI2XA4qNgwYA65dlit2DBgA/mMeKcoMGAH2Y/oq/
    gwEAV5dWir2EAQCql6uKGoQBAEyYGIsBhQEA/5gUi1CEAQDEma+Ko4MGABmZqIpphAYA3JoXiz6D
    BgAwnA2LNIMGAEGa+4vUggYAn5pai4GDAQBemhyMPYMBADObf4vaggYAvpsJjNqCBgDum06LdYMB
    AEGarYoihAYAXpoWi0OEAQAhmxaLBoUBADObs4qmgwYAvpuzijCEBgAmnBeLiIQGACacHIwGhQEA
    WJePjHaCAQBomPiM1IIGALGXb43OggEA75czjYSCBgBKmNqMPoMBAI+ZuIzPggYA25hwjdKCBgD6
    mI+NO4MBAFSXAI5zggEAaJhjjtWCBgCyl9uOz4IBAPCXoI6FggYASphFjj6DAQDVmWyO1IIGANqY
    247TggYAt5lPjj+DAQCMmrSN04IGAK6Z1ow5gwEAIpvhjD2DAQBumpeNPYMBAEOb/ozUggYAxJt/
    jdaCBgDim56MgYMBACacYYw+gwYAV5rtjtaCBgANmzaO1oIGACec3YxBhAEA7pugjXKEAQDZmriO
    y4MBAJGbAY7LgwEA1JtGjo+DBgAdm/2Oj4MGADebW45phAEANJzijbCEBgB7m5+OpYQGAKmc3YkI
    gAYAQJ22iqF/AQAfndSKCoAGAJedEYtfgAYAVZ62ireAAQDsndSK14AGAKmcSosIgAYAQJ0jjKF/
    AQAfnUGMCoAGANqdUYscgAEA7J1BjNeABgBVniOMt4ABAO6d3YlOgQYAWJ77iWyBAQBYnrWKJYIB
    AO6d04pEggYA7p1Ki06BBgBYnmiLbIEBAO6dQIxEggYAWJ4ijCWCAQCpnLiMCIAGAECdkY2hfwEA
    H52ujQqABgCXnX6MX4AGANqdvowcgAEA7J2ujdeABgBVnpGNt4ABAKmcJY4IgAYAQJ3+jqF/AQAf
    nRuPCoAGAJed641fgAYA2p0rjhyAAQDsnRuP14AGAFWe/o63gAEA7p24jE6BBgBYntWMbIEBAO6d
    ro1EggYAWJ6QjSWCAQDunSWOToEGAO6dG49EggYAWJ5DjmyBAQBYnv2OJYIBAO6d3Ym7ggYAWJ77
    idmCAQBYnrWKk4MBAO6dSou7ggYAWJ5pi9mCAQBYniKMk4MBAO6d04qxgwYA7p3diSiEBgBYnvuJ
    RoQBAFietYoAhQEAipwJjKaDBgCKnH+LMIQGAO6dQIyxgwYA7p1KiyiEBgBYnmmLRoQBAFieIowA
    hQEA7p24jLuCBgBYntaM2YIBAFiekI2TgwEA7p0ljruCBgBYnkOO2YIBAFie/Y6TgwEAjZx/jaCD
    BgCPnP2MIYQGAO6dro2xgwYA7p24jCiEBgBYntaMRoQBAFiekI0AhQEA7p0bj7GDBgDunSWOKIQG
    AFieQ45GhAEAWJ79jgCFAQColxSPHIABAEKYr4+hfwEAY5iSjwqABgDql1SPXoAGAC2XsI+1gAEA
    lpeSj9aABgCwmbCPn38BAPeYapCefwEAzpmSjwiABgCol4KQHIABAEKYHJGhfwEAY5j/kAqABgDq
    l8KQXoAGAC2XHZG1gAEAlpf/kNaABgDZmIiQCIAGALCZHpGffwEAzpn/kAiABgBKl+2P/IEBACiX
    b5BmgQEAl5eujzKCBgCUl4mQTIEGAECXVpHtgQEAjJcckSiCBgAem7CPn38BAGSaapCffwEAPJuS
    jwiABgCLnLCPnn8BANGbapCffwEARpqIkAiABgAemx6Rn38BALObiJAIgAYAPJv/kAiABgCLnB2R
    nn8BAKiX75EcgAEAQpiKkqF/AQBjmGySCoAGAOqXL5JegAYALZeLkrWAAQCWl22S1oAGANmY9ZEI
    gAYA95jYkZ5/AQCwmYuSn38BAM6ZbZIIgAYAp5dckxyAAQBimNmTCoAGAJWX2ZPXgAYA6peck1+A
    BgDZmGOTCIAGAPeYRZOefwEAzpnakwiABgCTl/eRTIEGACeX3pFlgQEAkpdokkOCBgApl4eSJYIB
    AJSXY5NOgQYAKpdFk2uBAQCNl/OTLIIGAEaa9pEIgAYAZJrXkZ9/AQAem4uSn38BANGb15GffwEA
    s5v2kQiABgA8m22SCIAGAIucipKefwEARppjkwiABgBkmkWTn38BANGbRZOffwEAs5tjkwiABgA8
    m9qTCIAGAFiXbo93ggEAs5dGkNGCAQD2lw2QiYIGAHSY2I/bggYAWZi7j0WDAQCxmbSP2YIGAPSY
    9I4/gwEAc5l2jx+DAQBNl9mQa4IBAEOYIpHbggYAAZjkkCCDAQDsmFuQ14IGAGyZJpDLgwEA/ZeU
    kcuDAQBZmDmRaYQBALaY3JDLgwEAsJlqkI+DBgD5mCCRj4MGABGZgpBphAEAVZnGkKWEBgCdmH2R
    pYQGACOab4/LgwEAZ5qzj4+DBgB/mhSPaIQBAMOaWI+lhAYAyJnLj2iEAQAMmg+QpYQGAJSX9JG7
    ggYAK5fVkdqCAQBDl82SToMBAKKXIJO9ggEA5pfgkn2CBgBGl7GTaIIBAECY2pPvggYAxJkMlNaC
    BgA0meqTgYMBAG6ZpJM8gwYAQpjWkY+DBgBLl1WS04MBAI2XkpKNgwYAnZf3kW2EAQDllzmSpoQG
    AFeX5pK9hAEAP5hXk3KDBgDrl/SS3YMGAH2YjpO/gwEAqpc7kxqEAQBMmKeTAYUBAMSZPpOjgwYA
    /5ijk1CEAQAZmTiTaYQGANyappM+gwYAn5rqk4GDAQAzmw6U2oIGADCcnJM0gwYA7pvek3WDAQBB
    mjyTIoQGAF6apZNDhAEAIZulkwaFAQAzm0KTpoMGAL6bQpMwhAYAJpymk4iEBgCpnJKPCIAGAECd
    a5ChfwEAl51Zj1+ABgDanZmPHIABAFWea5C3gAEAH52JkAqABgCpnACRCIAGAJedxpBfgAYA2p0G
    kRyAAQDsnYmQ14AGAO6dko9OgQYAWJ6wj2yBAQBYnmqQJYIBAO6dAJFOgQYA7p2IkESCBgBYnh2R
    bIEBAECd2JGhfwEAH532kQqABgCpnG2SCIAGAJedM5JfgAYA2p1zkhyAAQDsnfaR14AGAFWe2JG3
    gAEAQJ1Gk6F/AQAfnWOTCoAGAKmc2pMIgAYAl52hk1+ABgDaneGTHIABAOydY5PXgAYAVZ5Gk7eA
    AQDunW2SToEGAO6d9pFEggYAWJ7XkSWCAQBYnoqSbIEBAO6d2pNOgQYA7p1jk0SCBgBYnkWTJYIB
    AO6dko+7ggYAWJ6wj9mCAQBYnmqQk4MBAO6d/5C7ggYAWJ4ekdmCAQDunZKPKIQGAFiesI9GhAEA
    WJ5qkACFAQDunYiQsYMGAO6d/5AohAYAWJ4ekUaEAQDunW2Su4IGAFie15GTgwEAWJ6LktmCAQDu
    ndqTu4IGAFieRZOTgwEA7p32kbGDBgBYnteRAIUBAO6dbZIohAYAWJ6LkkaEAQCKnA6UMIQGAO6d
    Y5OxgwYAWJ5FkwCFAQDundqTKIQGAJOXD4r+hAYA8Jdgil2FBgBpmK6KH4UGALSXqoqchQEAj5mo
    it+EBgDbmKuKl4UGAPuYFIu2hQEATpdLii6GAQCRlwiKbIYGAEmYF4tshgEAZ5itiouGBgDvl16K
    yYYGAK2XpooDhwEAr5kTi22GAQDNmamKi4YGANmYq4oBhwYA9JgXixmHAQCtmRKL/YQBAISaqIrU
    hQYAZpoRi7aFAQBBm62KI4UGAMGbr4qghQYAKJwUi/eFBgDim1qLxYQBAESaqYoBhwYAXZoVixiH
    AQD6mqiKSoYGABGbFYtjhgEAlZv3iueGAQDVm7KKJYcGAOObWIszhgEAJZwbjHaGAQAmnNyMq4UB
    AO+boI3ghQEA2pq4jjmFAQCRmwGOPoUBANabQ44AhQYAH5v8jv2EBgA2m1yO14UBADSc4o0dhgYA
    e5ugjhOGBgAknOGMEIcBAOybqY1ChwEA2pq4jqaGAQCQmwKOqoYBANWbQ45thgYAHpv8jmqGBgA1
    m16OQ4cBAEyXNoqYhwEAjZf4id6HBgABmPmKnocBAEKYs4rbhwYAlZeUiq+IBgAsl7OKkYgBAHeZ
    +IqbhwEAspmyituHBgCamA6LN4gGAP+XqItMiAEAQZhpi5GIBgDXmFGL84cBAHeZqotMiAEAspln
    i5KIBgDWmEKMmogGAO+YLIwuiAEAlJcfiiaJBgCUl0uLZokGACuXaYtIiQEAopc/jK6IAQDjmveK
    mocBAAqaDIs2iAYAH5uyituHBgBImk+L84cBAG+aG4wuiAEAjJr6i5eIBgCSm6uLmYcBANSbaYva
    hwYARpxajJmHAQANm3mLlIgGAMSbL4yUiAYAP5jVjDSIAQBgmLiMnYgGAI+Z94ybiAYA/5iHjS+I
    AQAZmW2NmogGADaYSI6YiAYA8ZeHjliIAQBvmAuOS4gBAM6ZJI6aiAYA15gbj5qIBgCumUCOMYgB
    APKY+44wiAEALJfWjEeJAQCVl7iMaIkGAOiXe4zxiAYAnJemjbSIAQCRlyWObIkGAOGX5430iAYA
    J5dDjk6JAQCumdiMMYgBACKbzIwtiAEARZqujZqIBgBhmo2NMYgBAO2b9ozzhwEAN5upjfOHAQBC
    m7CMl4gGADCcNY02iAYAgppijvCHAQDCmqKONYgGAC+c642AhwYAeZuhjoCHBgB5m+uNNYgGAO6d
    04oehQYA7p3diZWFBgBYnvuJs4UBAI+c/IskhQYAjZx8i6GFBgDunUCMHoUGAO6dSouVhQYAWJ5p
    i7OFAQBYnrWKbYYBAO6d04qLhgYA7p3diQOHBgBYnvuJIYcBAI6c+4uThgYAjZx5ixSHBgDunUCM
    i4YGAFieIoxthgEA7p1KiwOHBgBYnmmLIYcBAI+cfI0QhQYAj5z8jI+FBgDuna6NHoUGAO6duIyV
    hQYAWJ7WjLSFAQDunRuPHoUGAO6dJY6VhQYAWJ5DjrSFAQCQnH2NfYYGAJCc/oz6hgYA7p2ujYuG
    BgBYnpCNbYYBAO6duIwDhwYAWJ7WjCGHAQDunRuPi4YGAFie/Y5thgEA7p0ljgOHBgBYnkOOIYcB
    AFietYrahwEA7p3TivmHBgDund2JcIgGAIucHozbhwYA7p1AjPmHBgBYniKM2ocBAO6dSotwiAYA
    WJ77iY6IAQBYnrWKSIkBAO6d04pmiQYAWJ5pi46IAQDunUCMZokGAFieIoxIiQEA7p2ujfmHBgBY
    npCN2ocBAO6duIxwiAYA7p0bj/mHBgBYnv2O2ocBAO6dJY5wiAYAWJ7WjI6IAQDuna6NZokGAFie
    kI1IiQEA7p0bj2aJBgBYnkOOjogBAFie/Y5IiQEAbJkmkDmFAQD9l5aROYUBAFmYOZHWhQEAtZjd
    kDmFAQCwmWqQ/YQGAPmYIpH9hAYAEZmCkNaFAQBVmcaQEoYGAJ6YfZEShgYAbJkmkKaGAQD9l5WR
    p4YBAFmYOJFHhwEAtZjekKeGAQCwmWqQaoYGAPmYIZFqhgYAEZmCkEOHAQAjmm+POYUBAGeas4/9
    hAYAf5oUj9aFAQDDmliPEoYGAMiZy4/WhQEADJoPkBKGBgAjmm+PpoYBAGeas49qhgYAfpoUj0OH
    AQDImcuPQ4cBAEGY2pH9hAYAk5eekv6EBgBEl2aSOoUBAJ6X9ZHYhQEA5pc2khOGBgBpmD2TH4UG
    APCX8JJdhQYAtJc6k5yFAQCPmTeT34QGANuYOpOXhQYA+5ijk7aFAQBCmNmRaoYGAE6X25IuhgEA
    SpdakqyGAQCRl5eSbIYGAKWX45FQhwEAZ5g9k4uGBgBJmKeTbIYBAK2XNZMDhwEA75ftksmGBgDN
    mTmTi4YGAK+Zo5NthgEA2Zg7kwGHBgD0mKeTGYcBAK2ZoZP9hAEAhJo3k9SFBgBmmqGTtoUBAEGb
    PJMjhQYA4pvqk8WEAQDBmz6ToIUGACicpJP3hQYARJo5kwGHBgBdmqWTGIcBAPqaOJNKhgYAEZuk
    k2OGAQDjm+eTM4YBAJWbh5PnhgEA1ZtBkyWHBgA9mK2PM4gBAGCYkY+ciAYAFZnPj/CHAQBVmQ+Q
    NYgGAFmYiZD0hwEAQpg1kX+IBgBVmcWQgIcGAJ6Ye5GEhwYAnZjJkDaIBgCglx2ProgBAOmXVo/x
    iAYALJexj0iJAQCVl5OPaIkGAKSXjZCoiAEA6ZfNkOmIBgCWlwKRZIkGACyXIJFGiQEAypkXj/OH
    AQDCmliPgIcGAAuaDpCAhwYAC5pYjzWIBgDqlyeSjIcGAEOYwpHxhwYATJfGkpiHAQCNl4iS3ocG
    AEOXTZIdiAEAAZiJk56HAQBCmEOT24cGACyXQ5ORiAEAlZckk6+IBgBBmPmTkYgGAHeZh5ObhwEA
    splBk9uHBgDXmOGT84cBAJqYnZM3iAYAspn3k5KIBgCgl/ORsYgBAOaXNpLsiAYAlJevkiaJBgAs
    l9OR/4kBACuXkJJEiQEAlJfak2aJBgDjmoaTmocBAEia35PzhwEACpqckzaIBgAfm0GT24cGANSb
    +JPahwYADZsIlJSIBgDunZKPlYUGAFiesI+zhQEA7p2IkB6FBgDunf+QlYUGAFieHpGzhQEAWJ5q
    kG2GAQDunZKPA4cGAFiesI8hhwEA7p2IkIuGBgDunf+QA4cGAFieHpEhhwEA7p32kR6FBgDunW2S
    lYUGAFiei5KzhQEAjZwMlKGFBgDunWOTHoUGAO6d2pOVhQYA7p32kYuGBgBYnteRbYYBAO6dbZID
    hwYAWJ6LkiGHAQCNnAiUFIcGAO6dY5OLhgYAWJ5Fk22GAQDundqTA4cGAFieapDahwEA7p2Sj3CI
    BgDunYiQ+YcGAO6d/5BwiAYAWJ6wj46IAQBYnmqQSIkBAO6diJBmiQYAWJ4ekY6IAQDunfaR+YcG
    AFie15HahwEA7p1tknCIBgDunWOT+YcGAFieRZPahwEA7p3ak3CIBgDunfaRZokGAFie15FIiQEA
    WJ6Lko6IAQDunWOTZokGAFieRZNIiQEAQZihf/2JAQBimAqA34kGAC2XtID9iQEAlpfWgN+JBgCo
    lxuAzIoBAOuXXoAMiwYAsJmff/uJAQDPmQiA3YkGAPeYn3+1igEA2ZgIgNOKBgAqlyaC+4kBAJSX
    RILdiQYAKZdngbaKAQCTl0mB04oGAOaXwYENiwYAY5gLgEmLBgBCmKF/Z4sBAJaX1YBKiwYALpez
    gGiLAQBBmLeAHYwGAPyXc4BZjAEA0JkIgEmLBgC3mZx/YosBAPWYAYAjjAYAspjAf2SMAQAxmbZ/
    6IsBAKKXAYJMiwEAjZdzgRyMBgBLlzaBYowBAEOXroHdiwEAP5g4ggGMBgDEmR+CM4wGAB6bn3/7
    iQEAZZqff7SKAQBGmgmA0ooGADybCIDdiQYAi5yef/uJAQDRm59/tYoBALObCIDTigYAHpuff2iL
    AQBGmgmAQIwGAGWan38hjAEAPJsIgEqLBgCLnJ5/aIsBANGbn38ijAEAs5sIgECMBgAzmyOCNYwG
    ACeXmIP2iQEASJcZg4SKAQCNl9SCvIoGAEaXkoL3igEA65clgxyLBgCTl7KD3YkGACiXAoX6iQEA
    Qpd9hIqKAQBZl/+DB4sBAJOXQoTAigYA75ekhBSLBgBAmLuCfosGAKqXYoNjiwEAfZgIg7WLAQDE
    meyCZYsGAG6ZhYLLiwYA/5iag8uLAQA0mcqCEYwBAEqYSoTNiwEAaJhohGOLBgAZmbKDX4sGAI+Z
    KIRfiwYA3JqHgs2LBgCfmsuCEYwBADOb74JpiwYAMJx9gsOLBgDum7+CBYwBAEGabINjiwYAXpqM
    g8yLAQAim1GEzYsBAK6ZR4TIiwEAbpoHhcyLAQC+m3qDaYsGACac0YPNiwYAQ5tuhGOLBgDimw6E
    EYwBAFeYGoD6jAEAnJfYgPyMAQBAmLuAjI0GALeZnX/QjAEA0JkJgLaMBgD0mAKAkY0GAC+ZuH9U
    jQEAnJhegDWNBgCqlxuCqYwBAOuX1YFsjAYAk5eAgY2NBgDllxqBNo0GAFeXx4FMjQEAaZgegq+N
    BgAZmRiC+IwGAI+ZGIJvjQYAWJgagGeOAQCdl9eAZ44BAPyXeIDJjQEAQZi6gPmOBgCymMB/0o0B
    ANCZCYAjjgYA9ZgCgP+OBgC3mZ1/PY4BADCZuH/BjgEAnZhegKKOBgBEl0eByY0BALSXG4IqjgEA
    8ZfRge2NBgCSl3uB+o4GAOWXGIGijgYAUZfAgbuOAQBomB6CGo8GANuYG4InjgYAzZkaghuPBgAe
    m59/1owBAEaaCYCtjQYAZZqff4+NAQA8mwiAuIwGAIucnn/VjAEA0Zuff5CNAQCzmwiAro0GAEGa
    HYKyjAYAvpsjgsCMBgBBmx2Cs40GAEaaCYAajwYAHpuff0OOAQBlmp9//I4BADybCIAljgYAi5ye
    f0OOAQDRm59//Y4BALObCIAbjwYAhJoYgmSOBgDBmx+CMI4GAPqaGYLajgYAfZhugk+MAQBMmIiC
    kY0BAP+YhILgjAEASpiIgvuOAQD7mISCRo4BAK+Zg4L8jgEAXpqGgtKMAQCtmYKCjY0BACGbhoKV
    jQEAJpyHgheNBgDim8uCVI0BACecTYTRjAEAJpyNg5aNAQBmmoKCRo4BACichYKHjgYA45vIgsKO
    AQAmnEyEO44BACWci4MFjwEAqZwIgN2JBgBAnaF/tooBAB+dCoDUigYAl51fgBGLBgBVnreAtooB
    AOyd14DUigYA7p1Ogd2JBgBYnmyB+4kBAFieJYK1igEA7p1EgtOKBgCpnAiASosGAECdoX8jjAEA
    H50KgEGMBgDanRyAUYsBAOyd14BBjAYAVZ63gCOMAQDunU6BSosGAFiebIFoiwEA7p1EgkCMBgBY
    niWCIowBAO6du4LdiQYAWJ7ZgvuJAQBYnpODtYoBAO6dKITdiQYAWJ5GhPuJAQBYngCFtYoBAO6d
    sYPTigYA7p27gkqLBgBYntmCaYsBAFiek4MijAEAipx6gzWMBgDunSiESosGAFieRoRpiwEA7p2x
    g0CMBgBYngCFIowBAKmcCIC4jAYAl51fgH6MBgBAnaF/kY0BAB+dCoCujQYA2p0cgL6MAQDsndeA
    ro0GAFWet4CRjQEA7p1OgbiMBgBYnmyB1YwBAO6dRIKujQYAWJ4lgpCNAQCpnAiAJY4GAJedX4Dr
    jQYAQJ2hf/6OAQAfnQqAG48GANqdHIArjgEA7J3XgBuPBgBVnreA/o4BAO6dToEljgYA7p1EghuP
    BgBYnmyBQ44BAFieJYL9jgEAipzvgsCMBgDunbuCuIwGAFie2YLWjAEAWJ6Tg5CNAQCPnG6EsYwG
    AI+cbIOzjQYA7p0ohLiMBgBYnkaE1owBAO6dsYOujQYAWJ4AhZCNAQCNnOyCMI4GAO6du4IljgYA
    WJ7ZgkOOAQBYnpOD/Y4BAI+cbYQejgYAjpxrgyKPBgDunSiEJY4GAO6dsYMbjwYAWJ5GhEOOAQBY
    ngCF/Y4BAJKXHoXfiQYARpfvhYeKAQCTl7GFv4oGAFSXcIUDiwEA8JcRhhSLBgAol3OG94kBAJOX
    jYbdiQYAl5cfh8GKBgBYl9+GBosBALGX34ReiwEAaJjUhWSLBgBKmLWFzosBANuY4IRhiwYA+pj/
    hMqLAQDVmdyFZIsGALeZv4XOiwEAspdMhl+LAQBzmEmHaosGAFiYLIfViwEA2phMhmKLBgD0mGSG
    zosBALGZJYdpiwYAc5nmhq+LAQCMmiWFYosGAMSb8IRmiwYADZumhWaLBgCRm3GFW4wBANSbtoUe
    jAYAV5pdhmaLBgDZmimGWowBAGeaJIcejAYAI5rfhluMAQAdm22GHowGACmX34f0iQEAlZf6h9uJ
    BgBKl16Hi4oBAPWXf4cYiwYAlpeviJSKBgAsl5GIsooBAJaXJokdigYAsZe7h1yLAQBCmJGIaosG
    AACYVIiviwEA7JjLh2eLBgCwmdqHHowGAGyZl4dbjAEA+ZiRiB6MBgC2mE2IW4wBAJWXZYlLiwYA
    LJdGiWmLAQBCmEeJHowGAP2XBIlbjAEAS5fGiWKMAQDumxGFAo0BADebzIX5jAEANJxShT+NBgB7
    mxCGNY0GANabs4WQjQYAf5qEhviMAQDImTuH+IwBAGeaJIeMjQYAw5rIhjSNBgAfm2yGjI0GAO+b
    EIVwjgEAkZtyhc6NAQA2m8yFZo4BADScU4WsjgYAe5sQhqKOBgDVm7SF/I4GANqaKYbJjQEAf5qE
    hmWOAQAjmuCGyI0BAMiZO4dljgEAZ5okh/qOBgDDmsiGoo4GAB6bbYb6jgYAEZnyh/iMAQCwmduH
    jI0GAPmYkoiMjQYAVZk2iDSNBgBZmKqI+IwBAJ2XZ4n8jAEAQZhKiYyNBgDll6mJNo0GAJ2Y7og0
    jQYAEZnyh2WOAQBsmZeHyI0BALWYTojIjQEAsJnbh/qOBgD5mJKI+o4GAFWZNoiijgYA/ZcHicmN
    AQBZmKmIZY4BAESX1onJjQEAnpdmiWeOAQBCmEmJ+o4GAOaXp4mijgYAnpjtiKKOBgAMmn+HNI0G
    AAyaf4eijgYA7p2Vhd2JBgBYnrOF+4kBAO6dHoXTigYAWJ5thrWKAQDunQOH3YkGAFieIYf7iQEA
    7p2LhtOKBgCNnPCEL4wGAO6dlYVKiwYAWJ6zhWmLAQDunR6FQIwGAO6dA4dKiwYAWJ4hh2mLAQDu
    nYuGQIwGAFiebYYijAEAWJ7ah7WKAQDunXCI3YkGAO6d+YfTigYAWJ6OiPuJAQBYnkiJtYoBAO6d
    ZonTigYA7p1wiEqLBgDunfmHQIwGAFie2ocijAEAWJ6OiGmLAQDunWaJQIwGAFieSIkijAEAj5zt
    hKCNBgDunZWFuIwGAFietIXWjAEA7p0eha6NBgDunQOHuIwGAFieIYfWjAEA7p2Lhq6NBgBYnm2G
    kI0BAJCc7YQNjwYA7p2VhSWOBgDunR6FG48GAFietIVDjgEA7p0DhyWOBgDunYuGG48GAFiebYb9
    jgEAWJ4hh0OOAQDunXCIuIwGAO6d+YeujQYAWJ7ah5CNAQBYno6I1owBAO6dZomujQYAWJ5IiZCN
    AQDunXCIJY4GAO6d+YcbjwYAWJ7ah/2OAQDunWaJG48GAFiejohDjgEAWJ5Iif2OAQD8l3eANo8B
    AFiYGYDUjwEAoZfRgNKPAQCymMB/P48BALeZnX+qjwEA0JkJgJGPBgAwmbd/MJABAJ2YXYAQkAYA
    R5dAgTiPAQCulxeCko8BAPCXz4FYjwYA5pcUgQ+QBgBHl7CBKZABANqYHIKRjwYAQpi5gGeQBgD+
    l3aApZABAFqYFYBGkQEAn5fQgEWRAQD1mAGAbJAGALOYwH+tkAEAz5kJgP+QBgCxmZ9/HpEBAJ2Y
    W4CBkQYAi5dvgWmQBgBFly+Bp5ABAEOYI4JqkAYA5ZcSgYGRBgCNlyqCGpEGAD2X8YFSkQEAspki
    gmuQBgAem59/sI8BAGSan39qkAEAPJsIgJKPBgCLnJ5/sI8BANGbn39qkAEARJoZgpCPBgDVmyKC
    tY8GAEaaCICIkAYAHpuffx6RAQCzmwiAiJAGADybCID/kAYAi5yefx2RAQAfmyKCa5AGAAOYaYIs
    kAEA9JiIgqmPAQB3mWiCKpABAFSXcILUkAEAAZgag92QAQBCmNqCIZEGANeYwoKDkAEAmph+gseQ
    BgB3mRqD3JABAO+YnIO9kAEAspnYgiGRBgA+mEaExJABAKKXsIM+kQEA6Jfrg4CRBgBgmCiELZEG
    ANaYs4MqkQYAj5lnhCqRBgBdmoaCqI8BAOOaZ4IpkAEAEZuFgvKOAQCVm2iCd48BAJKbHIMokAEA
    JJxShKCPAQBGnMuDKZABAEiawIKDkAEACpp9gsaQBgDUm9mCapAGAA2b6YIkkQYAb5qLg72QAQCu
    mUmEwZABACKbPIS9kAEAYZr+hMGQAQCMmmuDJpEGAO2bZ4SCkAEAMJylhMWQBgDEm6CDJJEGAEKb
    IYQnkQYAp5cbgPKRAQDql1+AMJIGAGKYCoBukgYAQZihf4ySAQCWl9aAbpIGAC2XtYCNkgEA2ZgI
    gPmRBgD3mJ5/25EBAM+ZCIBskgYAtJmef4iSAQCTl02B+5EGACeXZ4HhkQEAk5dFgmySBgAolymC
    iJIBAP+XdICBkwEAQZi2gECTBgComNd/m5MBAPCYCYBSkwYAJ5m0fx+TAQCPmSaA7ZMBABmZ3IDy
    kwYAVJlkgKOTBgBhlx2Bm5MBAJOXZYFSkwYAPpecgR+TAQBnmI6B8pMGALCXBYLtkwEA75fJgaOT
    BgCQmVCB8ZMGANqYBoLxkwYARpoIgPWRBgBkmp9/15EBACKbnX+GkgEA0puff9aRAQCzmwmA9ZEG
    AD2bCIBrkgYAj5ydf4WSAQAhmsp/k5MBAGKaCYBOkwYAn5q8fxeTAQD9mieA7pMBAIWa34D1kwYA
    wZpmgKWTBgCNm8l/kpMBAAucun8VkwEAzpsHgE2TBgAtnGSAopMGAPGb3IDzkwYAhppDgvCTBgD+
    mlGB8pMGAPGbQ4LxkwYAlJe7gvWRBgAql9qC15EBACiXmIOHkgEALJdGhNeRAQCVlyiE+JEGAJOX
    soNskgYAJ5cDhYqSAQBVl5aCk5MBAJSX14JPkwYARpcUgxeTAQBqmPqC9ZMGALKXcoPvkwEA8Zc2
    g6WTBgDOmfuC8JMGAFaXAoSUkwEARZeBhBiTAQCUl0SET5MGAPGXo4SlkwYAaphnhPWTBgDcmHOD
    8pMGAM+ZaITxkwYA/Zq6gvCTBgBFmnKD8JMGAPKbsIPwkwYAO5tohPCTBgCXnV+AWY8GAKmcCICS
    jwYAQJ2hf2uQAQDanRyAmY8BAFWet4BrkAEA7p1OgZKPBgBYnmyBsI8BAFieJYJqkAEAH50KgImQ
    BgCXnV+AxpAGAKmcCIAAkQYA7J3XgImQBgDanRyABpEBAO6dRIKIkAYA7p1OgQCRBgBYnmyBHZEB
    AI2c6YKjjwYA7p27gpKPBgBYntmCsI8BAFiek4NqkAEAkJxuhIqPBgDunSiEko8GAFieRoSwjwEA
    WJ4AhWqQAQDunbuC/5AGAFie2YIekQEAi5yOg2uQBgDunbGDiJAGAO6dKIT/kAYAWJ5GhB6RAQBA
    naJ/15EBAB+dC4D1kQYAl51fgDGSBgCpnAmAa5IGAOud14D0kQYAVJ62gNaRAQDdnRmAaJIBAO6d
    Q4L1kQYAV54lgtaRAQDtnU2Ba5IGAFqeZYGDkgEAgJ26fwaTAQAAnbx/hZMBAECdAYBEkwYAZ5wh
    gOqTAQCcnVuAn5MGAEGdt4D5kwYAO551gASTAQD2nbaAQ5MGAN6dGYDhkwEAaZxPgfGTBgCbncyB
    npMGAEKdKIL5kwYAPJ70gIOTAQBAnuqBCZMBAPadJ4JFkwYA352QgeKTAQBXnpKD1pEBAO6duYJr
    kgYAWp7TgoSSAQDunbCD9ZEGAFee/4TWkQEA7p0nhGuSBgBZnkCEhJIBAGicuYLxkwYAm505g56T
    BgA5nmiChpMBAD+eV4MJkwEA4J3/guOTAQBCnZWD+ZMGAGicJoTvkwYAm52nhJ6TBgD2nZWDRZMG
    ADie1oOGkwEAQZ7GhAuTAQDfnWyE45MBAPGX+IXokAEAnJcXhUORAQDhl1iFg5EGADaYuIUnkQYA
    /5j3hL6QAQBvmHuF25ABAK6ZsYXBkAEAGZndhCqRBgDOmZWFKpEGAD2YHYfDkAEAoJeNhj6RAQBg
    mAKHLJEGAOmXxoaAkQYA8phrhsCQAQAVmUCHgJABANeYi4YqkQYAkJtyhTqPAQDsmxmF0Y8BAC+c
    W4UQkAYANZvOhdOPAQB5mxKGEJAGANqaKYY2jwEAI5rghjaPAQB+moWG0o8BAMiZO4fSjwEAwprI
    hg+QBgCCmtKFgJABAMKaEobFkAYARZoehSqRBgA3mxqFgpABAHmbW4XFkAYAypmHhoKQAQALmsiG
    xZAGAGyZl4c2jwEAtZhOiDaPAQARmfKH0o8BAFWZNYgPkAYA/ZcGiTaPAQBKl8uJPI8BAFmYqYjX
    jwEApZdUieCPAQDql5eJHJAGAJ6Y7IgTkAYAWZj5h4SQAQCkl/6HN5EBAEKYpYgPkQYA6Zc9iHiR
    BgBVmX+HxZAGAJ2YOYjFkAYAQ5gziYCQBgBDl72JrJABAKCXZIlAkQEA55eniXyRBgALmn+HD5AG
    AJGXloX7kQYAJ5e0hd2RAQCSlx6FbpIGACyXIYfXkQEAlZcDh/iRBgCTl4yGbJIGACiXcoaHkgEA
    RpfuhRiTAQBVl3CFlJMBAJSXsYVPkwYAspffhO+TAQDxlxGGpZMGAGqY1YX1kwYA3JjghPKTBgDP
    mdWF8ZMGAFWX3oaTkwEAk5cfh06TBgCyl02G7pMBAGiYQ4f0kwYA3JhNhvKTBgDPmUKH8ZMGAEaa
    34TykwYAspvfhPCTBgA8m9WF8pMGAEaaTIbxkwYAs5tMhvGTBgA8m0KH8ZMGAJaXcoj0kQYAlZf6
    h2qSBgApl+CHhJIBACyXkYjVkQEAK5cBitSRAQCVlyaJrZIGACuXQ4mQkgEARpdchxaTAQAvl5OI
    RZMBAJiXsIgkkwYAr5fAh+iTAQDwl4CHpJMGAGWYr4jwkwYA25i7h/KTBgDPma+I8ZMGAFSXuomU
    kwEAqpckieWTAQDsl+uInJMGANqYJ4nxkwYARpq5h/GTBgCzm7mH8ZMGADybr4jxkwYARpomifGT
    BgCzmyaJ8ZMGAO6dlYWSjwYAWJ60hbCPAQBYnm2GapABAO6dA4eSjwYAWJ4hh7CPAQDunR6FiJAG
    AO6dlYX/kAYAWJ6zhR6RAQDunYuGiJAGAO6dA4f/kAYAWJ4hhx6RAQBYntqHapABAO6dcIiSjwYA
    WJ6OiLCPAQBYnkiJapABAO6d+YeIkAYA7p1wiP+QBgDunWaJiJAGAFiejogekQEA7p0ehfWRBgDu
    nZSFa5IGAFmer4WFkgEA7p2LhvWRBgBXnmyG1pEBAO6dAYdrkgYAWZ4ch4aSAQBBnQGF+ZMGAKac
    1IXxkwYAkZ0ShqOTBgD2nQOFRpMGADaeRYWIkwEA1Z3aheuTAQAZnUyG9JMGAKacQYfykwYAPJ4z
    hhWTAQDvnXCGTZMGAC2esoaSkwEAz51Ch+6TAQDunfiH9ZEGAFee2ofWkQEA7p1viGuSBgDunWWJ
    9ZEGAFeeR4nWkQEAWp6JiIaSAQCQnX2HpZMGABiduYf1kwYAppyuiPKTBgA7np+HF5MBAO6d3YdP
    kwYALJ4eiJOTAQCQneuIpZMGABidJ4n1kwYAO54NiReTAQDunUqJT5MGACyei4mTkwEAz52viO6T
    AQArl7aK+4kBACuX+Ym2igEAlZfUit2JBgCUl9qJ04oGAOeXUooNiwYARpchi/eKAQBIl6mLhIoB
    ACeXKIz2iQEAk5dBjN2JBgCNl2OLvIoGAOuXtYsciwYAopeRik2LAQBDlz2K3osBAI2XA4ocjAYA
    P5jHigGMBgBumRWLy4sGAMSZr4ozjAYAQJhKi36LBgB9mJiLtYsBAKqX8otjiwEAxJl8i2WLBgAZ
    mUKMX4sGAP+YKYzLiwEANJlaixGMAQDcmheLzYsGADCcDYvDiwYAM5uzijWMBgBBmvuLY4sGAF6a
    HIzMiwEAn5paixGMAQAzm3+LaYsGAL6bCYxpiwYA7ptOiwWMAQBClw2NiooBACiXko36iQEAkpeu
    jd+JBgCTl9KMwIoGAFmXj4wHiwEA75czjRSLBgAolwKP94kBAJOXHI/diQYARpd+joeKAQCTl0GO
    v4oGAFSXAI4DiwEA8JegjhSLBgBomPiMY4sGAEqY2ozNiwEAsZdvjV6LAQCPmbiMX4sGANuYcI1h
    iwYA+piPjcqLAQBomGOOZIsGAEqYRY7OiwEAspfcjl+LAQDVmWyOZIsGALeZT47OiwEA2pjbjmKL
    BgCumdaMyIsBACKb4YzNiwEAjJq0jWKLBgBumpeNzIsBAEOb/oxjiwYAJpxhjM2LBgDEm3+NZosG
    AOKbnowRjAEAV5rtjmaLBgDZmriOWowBAA2bNo5miwYAkZsBjluMAQDUm0aOHowGAB2b/Y4ejAYA
    65dlimyMBgCql6uKqowBAH2Y/opPjAEAV5dWikyNAQCTlw+KjY0GAEyYGIuRjQEAaZiuiq+NBgD/
    mBSL4IwBABmZqIr4jAYAj5moim+NBgDwl2CK7Y0GALSXqoorjgEATpdLir6OAQCRlwiK/I4GAGeY
    rYoajwYASZgXi/yOAQDbmKuKJ44GAPuYFItGjgEAzZmpihuPBgCvmROL/I4BAEGarYqyjAYAXpoW
    i9KMAQCtmRKLjY0BACGbFouVjQEAvpuzisCMBgBBm62Ks40GACacF4sXjQYA4ptai1SNAQAmnByM
    lo0BAGaaEYtGjgEAhJqoimSOBgDBm6+KMI4GAPqaqIrajgYAKJwUi4eOBgDjm1iLwo4BACWcG4wF
    jwEAJ5zdjNGMAQDum6CNAo0BADebW475jAEANJzijT+NBgDWm0OOkI0GAHubn441jQYAH5v8joyN
    BgDvm6CNcI4BACac3Iw7jgEA2pq4jsmNAQCRmwGOzo0BADabXI5mjgEANJzijayOBgDVm0OO/I4G
    AHuboI6ijgYAHpv8jvqOBgDund2J3YkGAFie+4n7iQEAWJ61irWKAQDundOK04oGAO6dSovdiQYA
    WJ5pi/uJAQBYniKMtYoBAO6dQIzTigYA7p3diUqLBgBYnvuJaYsBAFietYoijAEA7p3TikCMBgCK
    nAmMNYwGAO6dSotKiwYAWJ5pi2mLAQDunUCMQIwGAFieIowijAEA7p24jN2JBgBYntaM+4kBAFie
    kI21igEA7p2ujdOKBgDunSWO3YkGAFieQ477iQEAWJ79jrWKAQDunRuP04oGAI2cf40vjAYA7p24
    jEqLBgBYntaMaYsBAO6dro1AjAYAWJ6QjSKMAQDunSWOSosGAFieQ45piwEA7p0bj0CMBgBYnv2O
    IowBAO6d3Ym4jAYAWJ77idaMAQBYnrWKkI0BAO6d04qujQYAipx/i8CMBgCPnPyLs40GAO6dSou4
    jAYAWJ5pi9aMAQDunUCMro0GAFieIoyQjQEA7p3diSWOBgBYnvuJQ44BAFietYr9jgEA7p3TihuP
    BgCNnHyLMI4GAI6c+4sijwYA7p1KiyWOBgBYnmmLQ44BAO6dQIwbjwYAWJ4ijP2OAQCPnP2MsYwG
    AI+cfI2gjQYA7p24jLiMBgBYntaM1owBAO6dro2ujQYAWJ6QjZCNAQDunSWOuIwGAFieQ47WjAEA
    7p0bj66NBgBYnv2OkI0BAI+c/IwejgYAkJx9jQ2PBgDunbiMJY4GAFie1oxDjgEA7p2ujRuPBgBY
    npCN/Y4BAO6dJY4ljgYA7p0bjxuPBgBYnkOOQ44BAFie/Y79jgEAKZdvkPSJAQBKl+6Pi4oBAFiX
    bo8GiwEAl5evj8GKBgD1lw6QGIsGAJWXipDbiQYALJchkbKKAQCWlz+RlIoGAFiYvI/ViwEAsZdK
    kFyLAQBzmNmPaosGAPSY9I7OiwEAc5l2j6+LAQCxmbSPaYsGAGyZJpBbjAEAAJjkkK+LAQBCmCGR
    aosGAP2XlJFbjAEA7JhbkGeLBgC2mNyQW4wBALCZapAejAYA+ZggkR6MBgAjmm+PW4wBAGeas48e
    jAYAlpe2kR2KBgArl4iStooBAJSXaZLTigYAK5dFk/uJAQCVl2OT3YkGAOeX4ZINiwYAjZfzk7yK
    BgBGl7GT94oBAJWX9ZFLiwYALJfWkWmLAQBCmNaRHowGAI2XkpIcjAYAQ5fNkt6LAQBLl1WSYowB
    AKKXIZNNiwEAQJjak36LBgA/mFeTAYwGAMSZDJRliwYAbpmkk8uLBgDEmT6TM4wGADSZ6pMRjAEA
    3Jqmk82LBgCfmuqTEYwBADObDpRpiwYAMJyck8OLBgAzm0KTNYwGAO6b3pMFjAEAWZg5kfiMAQAR
    mYKQ+IwBAFWZxpA0jQYAsJlqkIyNBgCdmH2RNI0GAPmYIpGMjQYAbJkmkMiNAQD9l5aRyY0BAFmY
    OZFljgEAtZjdkMiNAQARmYKQZY4BAFWZxpCijgYAsJlqkPqOBgCemH2Roo4GAPmYIZH6jgYAf5oU
    j/iMAQDImcuP+IwBAMOaWI80jQYADJoPkDSNBgBnmrOPjI0GACOab4/IjQEAf5oUj2WOAQDImcuP
    ZY4BAMOaWI+ijgYADJoPkKKOBgBnmrOP+o4GAJ2X95H8jAEA5Zc5kjaNBgBBmNqRjI0GAFeX5pJM
    jQEAk5eeko2NBgCqlzuTqowBAOuX9JJsjAYAfZiOk0+MAQBpmD2Tr40GAEyYp5ORjQEAGZk4k/iM
    BgD/mKOT4IwBAI+ZN5NvjQYAnpf1kWeOAQBEl2aSyY0BAOaXNpKijgYAQpjZkfqOBgCRl5eS/I4G
    AE6X25K+jgEAtJc6kyuOAQDwl/CS7Y0GAGeYPZMajwYASZink/yOAQDbmDqTJ44GAM2ZOZMbjwYA
    +5ijk0aOAQCvmaOT/I4BAEGaPJOyjAYAXpqlk9KMAQCtmaGTjY0BACGbpZOVjQEAvptCk8CMBgBB
    mzyTs40GACacppMXjQYA4pvqk1SNAQCEmjeTZI4GAGaaoZNGjgEAwZs+kzCOBgD6mjiT2o4GACic
    pJOHjgYA45vnk8KOAQDunZKP3YkGAFiesI/7iQEAWJ5qkLWKAQDunf+Q3YkGAFieHpH7iQEA7p2I
    kNOKBgDunZKPSosGAFiesI9piwEAWJ5qkCKMAQDunf+QSosGAFieHpFpiwEA7p2IkECMBgBYnteR
    tYoBAO6dbZLdiQYAWJ6LkvuJAQDunfaR04oGAFieRZO1igEA7p3ak92JBgDunWOT04oGAO6dbZJK
    iwYAWJ6LkmmLAQDunfaRQIwGAFie15EijAEA7p3ak0qLBgDunWOTQIwGAFieRZMijAEA7p2Sj7iM
    BgBYnrCP1owBAFieapCQjQEA7p3/kLiMBgBYnh6R1owBAO6diJCujQYA7p2SjyWOBgBYnrCPQ44B
    AFieapD9jgEA7p3/kCWOBgDunYiQG48GAFieHpFDjgEA7p1tkriMBgBYnouS1owBAO6d9pGujQYA
    WJ7XkZCNAQCKnA6UwIwGAO6d2pO4jAYA7p1jk66NBgBYnkWTkI0BAO6dbZIljgYA7p32kRuPBgBY
    nteR/Y4BAFiei5JDjgEAjZwMlDCOBgDundqTJY4GAO6dY5MbjwYAWJ5Fk/2OAQDvl16KWI8GAK2X
    poqTjwEATJc2iieQAQABmPmKLZABANmYq4qRjwYA9JgXi6mPAQB3mfiKKpABAI2X+IltkAYALJez
    iiCRAQBCmLOKa5AGAJWXlIo/kQYAmpgOi8aQBgCymbKKa5AGAP+XqIvckAEAQZhpiyCRBgCilz+M
    PZEBANeYUYuDkAEAd5mqi9yQAQDumCyMvZABALKZZ4shkQYA1phCjCqRBgBEmqmKkI8GAF2aFYuo
    jwEA45r3iimQAQARmxWL8o4BAJWb94p3jwEA1ZuyirWPBgCSm6uLKJABAEacWowpkAEACpoMi8aQ
    BgAfm7KKa5AGAEiaT4uDkAEAb5objL2QAQCMmvqLJpEGANSbaYtqkAYADZt5iySRBgDEmy+MJJEG
    AD6Y1YzEkAEAYJi4jC2RBgDol3uMgJEGAJyXpo1DkQEA/5iHjb6QAQCPmfeMKpEGABmZbY0qkQYA
    8ZeHjuiQAQA2mEiOJ5EGAOGX542DkQYAb5gLjtuQAQCumUCOwZABAPKY+47AkAEAzpkkjiqRBgDX
    mBuPKpEGACSc4YygjwEA7JupjdGPAQDamriONo8BAJCbAo46jwEANZtejtOPAQAvnOuNEJAGAHmb
    oY4QkAYArpnYjMGQAQAim8yMvZABAGGajY3BkAEARZqujSqRBgDtm/aMgpABADebqY2CkAEAMJw1
    jcWQBgBCm7CMJ5EGAIKaYo6AkAEAwpqijsWQBgB5m+uNxZAGAJSXH4q2kQYAKZe7ioaSAQCVl9WK
    bJIGAJWXS4v1kQYAK5dqi9eRAQCTl0GMbJIGACiXJ4yHkgEAR5c3iheTAQCUl/mJT5MGAFWXJYuU
    kwEA8ZdYiqWTBgBqmByK9ZMGALOXlIrvkwEAz5kdivGTBgDcmJWK8pMGAEaXpIsYkwEAlJdmi0+T
    BgDxl8aLpZMGAGqYiov1kwYAspcBjO+TAQDPmYqL8ZMGANyYAozykwYARpqUivGTBgA8mx2K8ZMG
    ALOblIrxkwYARpoBjPGTBgA8m4qL8ZMGALObAYzxkwYALJfWjNeRAQCVl7iM+JEGAJKXro1ukgYA
    J5eSjYqSAQCRlyWO+5EGACeXQ47dkQEAk5ccj2ySBgAolwKPh5IBAEWXEI0YkwEAVpeSjJSTAQCU
    l9OMT5MGAGqY94z1kwYAspdvje+TAQDxlzONpZMGAM+Z94zxkwYA3JhwjfKTBgBVlwCOlJMBAJSX
    QY5PkwYARpd+jhiTAQBqmGSO9ZMGALKX3I7ukwEA8ZegjqWTBgDPmWSO8ZMGANyY3Y7ykwYARppu
    jfGTBgA8m/eM8ZMGALObbo3xkwYARprcjvGTBgA8m2SO8ZMGALOb247xkwYA7p3diZKPBgBYnvuJ
    sI8BAFietYpqkAEAjZx5i6OPBgDunUqLko8GAFieaYuwjwEAWJ4ijGqQAQDundOKiJAGAO6d3Yn/
    kAYAWJ77iR6RAQCLnB6Ma5AGAO6dQIyIkAYA7p1Ki/+QBgBYnmiLHpEBAJCc/oyKjwYA7p24jJKP
    BgBYntaMsI8BAFiekI1qkAEA7p0ljpKPBgBYnkOOsI8BAFie/Y5qkAEA7p2ujYiQBgDunbiM/5AG
    AFie1owekQEA7p0bj4iQBgDunSWO/5AGAFieQ44ekQEAV560itaRAQDundOK9ZEGAO6d3IlrkgYA
    Wp72iYaSAQDunUCM9ZEGAFeeIYzWkQEA7p1Ji2uSBgBanmSLhpIBAKacG4rykwYAkJ1YiqWTBgAY
    nZSK9ZMGADueeooXkwEA7p23ik+TBgAsnviKk5MBAM+dHIrukwEAppyIi/KTBgCQncWLpZMGABid
    AYz1kwYAO57nixeTAQDunSWMT5MGACyeZoyTkwEAz52Ji+6TAQDuna2N9ZEGAFeej43WkQEA7p22
    jGuSBgBantGMhpIBAO6dGo/1kQYAV578jtaRAQDunSSOa5IGAFqePo6GkgEAppz2jPKTBgCQnTKN
    pZMGABidbo31kwYAO55UjReTAQDunZKNT5MGAM+d94zukwEAppxjjvKTBgCQnaCOpZMGABid3I71
    kwYALJ7TjZOTAQA7nsKOF5MBAO6d/45PkwYAz51kju6TAQBsmSaQNo8BAP2XlZE2jwEAWZg4kdeP
    AQC1mN6QNo8BABGZgpDSjwEAVZnFkA+QBgCemHuRE5AGAD2YrY/DkAEAoJcdjz6RAQDpl1aPgJEG
    AGCYkY8skQYAFZnPj4CQAQBVmQ+QxZAGAFmYiZCEkAEApJeNkDeRAQDpl82QeJEGAEKYNZEPkQYA
    nZjJkMWQBgAjmm+PNo8BAH6aFI/SjwEAwppYjw+QBgDImcuP0o8BAAuaDpAPkAYAypkXj4KQAQAL
    mliPxZAGAEqXWpI8jwEApZfjkeCPAQDqlyeSHJAGAEyXxpInkAEArZc1k5OPAQDvl+2SWI8GAAGY
    iZMtkAEA2Zg7k5GPBgB3mYeTKpABAPSYp5OpjwEAQ5jCkYCQBgCNl4iSbZAGAEOXTZKskAEAoJfz
    kUCRAQDnlzaSfJEGACyXQ5MgkQEAQphDk2uQBgCVlySTP5EGAEGY+ZMgkQYAsplBk2uQBgDXmOGT
    g5ABAJqYnZPGkAYAspn3kyGRBgBEmjmTkI8GAOOahpMpkAEAXZqlk6iPAQCVm4eTd48BABGbpJPy
    jgEA1ZtBk7WPBgBImt+Tg5ABAAqanJPGkAYAH5tBk2uQBgDUm/iTapAGAA2bCJQkkQYALJexj9eR
    AQCVl5OP+JEGACmXcJCEkgEAlpcCkfSRBgAslyGR1ZEBAJWXipBqkgYAVZduj5OTAQBGl+yPFpMB
    AJOXr49OkwYAr5dQkOiTAQDwlw+QpJMGAGiY0o/0kwYAz5nSj/GTBgAvlyKRRZMBAJiXP5EkkwYA
    7Jd7kZyTBgBlmD+R8JMGANuYSpDykwYAz5k/kfGTBgA8m9KP8ZMGAEaaSZDxkwYAs5tJkPGTBgA8
    mz+R8ZMGAJSXr5K2kQYAK5eQktSRAQCVl7aRrZIGACuX05GQkgEAlZfbk/WRBgCVl2WTbJIGACmX
    SpOGkgEAR5fGkheTAQBUl0mSlJMBAJSXiZJPkwYAqpezkeWTAQBqmKyS9ZMGANqYtpHxkwYAz5ms
    kvGTBgBVl7WTlJMBAJOX9pNPkwYAs5ckk++TAQDxl+iSpZMGAGqYGZT1kwYA3Jglk/KTBgDPmRmU
    8ZMGAEaatpHxkwYAs5u2kfGTBgA8m6yS8ZMGAEaaI5PxkwYAs5sjk/GTBgA8mxmU8ZMGAO6dko+S
    jwYAWJ6wj7CPAQBYnmqQapABAO6d/5CSjwYAWJ4ekbCPAQDunZKP/5AGAFiesI8ekQEA7p2IkIiQ
    BgDunf+Q/5AGAFieHpEekQEAWJ7XkWqQAQDunW2Sko8GAFiei5KwjwEAjZwIlKOPBgBYnkWTapAB
    AO6d2pOSjwYA7p32kYiQBgDunW2S/5AGAFiei5IekQEA7p1jk4iQBgDundqT/5AGAFeeaZDWkQEA
    7p2Rj2uSBgBanquPhpIBAO6diJD1kQYA7p3+kGuSBgBanhmRhpIBAKac0I/ykwYAkJ0NkKWTBgAs
    nkCPk5MBADueL5AXkwEAz53Rj+6TAQAYnUmQ9ZMGAKacPpHykwYAkJ16kaWTBgDunWyQT5MGACye
    rZCTkwEAO56ckReTAQDPnT+R7pMBAO6d9ZH1kQYAV57WkdaRAQDunWuSa5IGAFqehpKGkgEA7p1i
    k/WRBgBXnkST1pEBAO6d2ZNrkgYAGJ22kfWTBgCmnKuS8pMGAO6d2pFPkwYALJ4bkpOTAQDPnayS
    7pMBAJCd6JKlkwYAGJ0jk/WTBgCmnBiU8pMGADueCZMXkwEA7p1Hk0+TBgAsnoiTk5MBAM+dGZTu
    kwEAqJfJlByAAQBCmPeToX8BAGOYR5UKgAYALJf3k7aAAQCWl0eV1oAGAOqXCZVegAYA2ZjQlAiA
    BgCwmfiTn38BAPeYspSefwEAzplHlQiABgBCmGSVoX8BAKiXNpYbgAEALZdllbWAAQDrl3aWXoAG
    ALCZZZWffwEA95gflp5/AQDZmD2WCIAGAJSX0ZRMgQYASJc5lPSBAQAnl7iUZYEBAJOXY5UvggYA
    lZc+lkyBBgBCl52V+IEBACmXJJZlgQEARprQlAiABgAem/iTn38BAGSaspSffwEAi5z4k55/AQDR
    m7KUn38BALOb0JQIgAYAPJtHlQiABgAem2WVn38BAGSaHpaffwEARpo9lgiABgCLnGWVnn8BANKb
    HpaffwEAs5s9lgmABgBDmNGWoX8BAGSYtJYKgAYAL5fRlrSAAQCYl7SW1YAGAPyXy5d3gAEAQJiK
    l7eABgC0mc+Wnn8BACeZaJe0fwEAz5mzlgiABgComOOX138BAPCYmpcJgAYAVJnsl2WABgCPmTWY
    JoABAPqYpZjAgAEAGJk7mN2ABgAtl4qXcYEBAJeXapeOgQYAl5f0lgWCBgDpl+KXy4EGAEGYnphy
    gQEAYZg1mI6BBgCmlyWYC4IBAJCZOZhQgQYA15g1mASCBgAim82WnX8BAJ+aX5e8fwEAIZrbl8p/
    AQBimpaXCYAGAMGa7JdmgAYAPZuzlgiABgCPnMyWnX8BAAucXZe6fwEAjZvZl8l/AQDOm5WXB4AG
    AC2c6pdkgAYA/Zo2mCeAAQBnmqeYwYABAIWaPZjfgAYA05ulmL6AAQDxmzuY3IAGAK+ZophwgQEA
    hZozmEaCBgBnmp6YLIIBAP6aOphRgQYAHZujmHGBAQDSm6OYJYIBAPGbOZhDggYAqpeClNOCAQDr
    l0WUjIIGAFiXIJV2ggEAZpiIldOCBgB9mCeUJYMBAEiYapU9gwEAGZnRlM+CBgCPmUiVz4IGAP+Y
    uZQ7gwEArpcGlsiCAQDul8WVg4IGAC6X15YlggEAQ5jWljqDAQDamP+V0oIGAPmYHpY7gwEAs5nZ
    lj6DAQBBmouU1IIGAF6aq5Q9gwEAIptwlT2DAQC+m5mU2oIGAEObjZXUggYAJpzwlD6DBgDimy6V
    gYMBAIyaRJbTggYArplmlTmDAQBumieWPYMBAMSbD5bWggYAJ5xtlUGEAQAmnKyUBoUBAJGbkZbM
    gwEA7pswlnOEAQAznHKWsIQGAOuXMZd9ggYAY5j0ltGCBgCnl3CXwIIBANKZ95bUggYAm5jil32C
    BgDZmGqX0YIGAPaYipc6gwEAXJglmMCCAQD0mJ6YJIIBAAya4JeBggYAT5pwl9aCBgCumtKXL4MG
    AA2bxZbWggYAy5kjmMOCAQBsmhSYcIMBAPWaLpi+ggYADZuWmOWCAQDUm6GYkYMBAN2aRZfNgwEA
    hZq+l2KEAQDLmvCXrYQGANSb1ZaPgwYAGpuMl4yDBgA0m+uWbYQBAHibL5ephAYAJ5ulmE2EAQDy
    mzeYr4MGAEObO5hqhAYAQJ2zlKF/AQAfndGUCoAGAKmcR5UIgAYAl50OlV+ABgDanU6VHIABAOyd
    0ZTXgAYAVZ6zlLeAAQBAnR+Won8BAB+dPJYLgAYAl514ll+ABgDdnbCWGYABAFSeHpa2gAEA6508
    lteABgDunUeVToEGAO6d0JREggYAWJ74k2yBAQBYnrKUJYIBAFieZZVsgQEAV54eliSCAQDunTyW
    Q4IGAKmcs5YJgAYAgJ1Ol7p/AQAAncyXvH8BAECdjJcBgAYAnJ3nl1uABgA7nkyXdYABAPadi5e2
    gAYAZ5wymCGAAQAEnYiYd4ABAEGdQZi3gAYA3p0omBmAAQCbneaXzIEGAO2ds5ZNgQYAPJ7Ll/SA
    AQBAnlGX6oEBAFqey5ZlgQEA9p2NlyeCBgBpnDmYT4EGAIKdhZj2gAEAgpylmGmBAQAHnYuY64EB
    AEKdQZgoggYA350qmJCBAQDunUeVu4IGAFie+JPZggEAWJ6ylJODAQBYnmWV2YIBAFeeHpaSgwEA
    ipyZlKaDBgCPnI2VIYQGAO6d0JSxgwYAWJ74k0aEAQBYnrKUAIUBAO6dR5UohAYAjZwPlqCDBgDu
    nTyWsIMGAFieZZVGhAEAV54elv+EAQCbneaXOYMGAO6dspa5ggYAOZ7Ol2iCAQA/nlGXV4MBAFqe
    y5bTggEAZ5w5mLmCBgCEnYOYaYIBAIGcpZjTggEABp2KmFeDAQDgnSqY/4IBAJud5penhAYA9p2N
    l5WDBgA4ns6X1oMBAO6ds5YnhAYAQZ5Sl8aEAQBZnsyWQIQBAEKdQZiVgwYAg52DmNaDAQBonDeY
    JoQGAIGco5g/hAEABJ2JmMSEAQDfnSqYbIQBACaca5WrhQEAkZuRlkCFAQDumzCW4IUBADOccpYd
    hgYAJZyqlHaGAQAknHGVEIcBAI+bkparhgEA7Js4lkKHAQDQmkmXQIUBAIWayZfQhQEAzpr3lxqG
    BgDVm9OWAYUGABmbiZcFhQYAM5vsltqFAQB3mzGXFoYGAI2aN5jthAEALpuqmLiFAQC2mziY4YQG
    ANaboZj/hAEAR5s/mNeFBgCHnKKYtYUBAM6aTJeqhgEAhZrKlzuHAQDUm9OWbYYGABibjJdxhgYA
    NJvtlkOHAQCTmkCYW4YBAC+bq5glhwEAuJs6mE6GBgDZm6KYboYBAEibQJhDhwYAhpyjmCKHAQD/
    lzeUTIgBAGCYR5WdiAYA1pjSlJqIBgB3mTmUTIgBAO+Yu5QuiAEAj5mGlZuIBgA/mGWVNIgBAP2Y
    GJYviAEAZpimlkKIAQAZmf2VmogGAKKXz5SuiAEAK5f5k0iJAQCVl0iVaIkGAOiXCpXxiAYALJdm
    lUeJAQCdlzaWsogBAOKXd5bziAYAjJqKlJeIBgBvmqqULogBAK2ZaJUxiAEAkps7lJmHAQBGnOqU
    mYcBAMSbv5SUiAYAQptAlZeIBgAim1uVLYgBAGGaHJYxiAEARZo9lpuIBgDtm4aV84cBADebOZbz
    hwEAL5x7loCHBgAwnMWVNogGAHmbepY1iAYA6Zckl2eIAQAzmN2WmIgGALGZzpYwiAEAJplpl0OI
    AQDPmbSWmogGAKeY5JdoiAEA75ial5mIBgApl9KWTIkBAJKXtJZriQYAQpiKl0iJBgD+l86XCYkB
    AC6XipcBigEAVJnrl/SIBgBBmJ6YAYoBABmZO5hsiQYA+5ilmE+JAQCSmTOYtYgBAIKa85bvhwEA
    z5r3l4WHBgDCmjKXNYgGACSay5dOiAEAZpqKl5CIBgB4mzGXgIcGAJeaQJjHhwEAHpuimJGIAQC4
    mzuYvIcGADybOJiviAYA2pujmN2HAQCGnKOYj4gBAIWaOJhniQYAZpqimEiJAQCzmziYJokGANGb
    ophEiQEAh5yhmPyJAQCPnIuUJIUGAI+cjJWPhQYA7p3QlB6FBgBYnviTs4UBAO6dR5WVhQYAj5wM
    lhCFBgDunT2WHoUGAFieZZWzhQEAjpyKlJOGBgCQnI2V+oYGAO6d0JSLhgYAWJ6ylG2GAQBYnviT
    IYcBAO6dR5UDhwYAkJwMln2GBgBXnh6WbIYBAO6dPZaLhgYAWJ5llSGHAQCSneuXEoYGAPadjZcD
    hQYANp7Ql0WFAQDunbOWlIUGAFmezZavhQEAQZ1BmAGFBgCCnYaYQIUBAKacOZjUhQYA1Z0zmNqF
    AQA8nl2XM4YBAO+dlZdwhgYALZ7al7KGAQDunbOWAYcGAFmezZYchwEAGZ08mE2GBgA2naaYa4YB
    AKacOphBhwYAz502mEKHAQCLnK2U24cGAO6d0JT5hwYAWJ6ylNqHAQDunUeVcIgGAFeeHpbahwEA
    7p09lviHBgDundCUZokGAFie+JOOiAEAWJ6ylEiJAQBYnmWVjogBAFeeHpZHiQEA7p09lmWJBgCQ
    neyXfYcGADueX5efhwEA7p2Wl92HBgDunbOWb4gGACye25ceiAEAGJ09mLmHBgCmnDqYrogGADWd
    ppjYhwEAkJ3sl+uIBgA7nl+XDIkBAFqezZaJiAEA7p2Wl0qJBgAtntuXi4kBABidPZgniQYANZ2n
    mEWJAQDPnTaYr4gBACeXuJT2iQEAk5fRlN2JBgBIlziUg4oBAOuXRZQciwYAk5dilb+KBgBZlx+V
    BosBACmXIZb5iQEAQpeclYmKAQCUlz2W3okGAO6XxZUTiwYALpfYlrSKAQCql4KUY4sBAH2YJ5S1
    iwEAZpiIlWOLBgBImGqVzYsBABmZ0ZRfiwYA/5i5lMuLAQCPmUiVX4sGAK6XBpZYiwEAQ5jWlsqL
    AQDamP+VYYsGAPmYHpbKiwEAtJnZls2LAQBBmouUY4sGAF6aq5TMiwEAIptwlc2LAQC+m5mUaYsG
    AEObjZVjiwYAJpzwlM2LBgDimy6VEYwBAK6ZZpXIiwEAbponlsyLAQCMmkSWYosGAMSbD5ZmiwYA
    kZuRllyMAQCXl2uXHooGAOmX45dbigYAmJf1lpSKBgDrlzGXDIsGAJuY4ZcMiwYAYZg1mB6KBgCm
    lyaYmooBAJGZOZjfiQYA2Jg1mJSKBgD0mJ6YtIoBAGOY9JZgiwYAp5dwl1CLAQDSmfeWZIsGANmY
    apdgiwYA9piKl8mLAQBcmCWYUIsBAAya4JcQiwYAsJmimP+JAQBnmp6Yu4oBAIWaNJjVigYA/Jo4
    mN6JBgAZm6KY/IkBANKboZi1igEA8Zs4mNOKBgBPmnCXZosGAK6a0pe+iwYA3ZpFl12MAQANm8WW
    ZYsGANSb1ZYfjAYAGpuMlxyMBgDLmSOYUosBAGyaFJgAjAEA9ZoumE2LBgANm5aYdIsBANSboZgh
    jAEA8ps3mD+MBgAnnG2V0YwBACacrJSWjQEA7pswlgKNAQAznHKWP40GACaca5U7jgEAJZyqlAWP
    AQCRm5GW0I0BAO6bMJZwjgEAM5xylq2OBgCFmr6X8owBAMua8Jc8jQYANJvrlvyMAQB4my+XOI0G
    ANWb05aQjQYAGZuJl5SNBgAnm6WY3IwBAI2aN5h8jQEAQ5s7mPqMBgC2mziYcI0GANaboZiPjQEA
    0JpJl8+NAQCFmsmXYI4BAM6a95epjgYAM5vslmmOAQB3mzGXpY4GANSb05b9jgYAGJuMlwCPBgAu
    m6qYSI4BAJOaQJjrjgEAR5s/mGaOBgCHnKKYRY4BALibOpjejgYAWJ74k/uJAQBYnrKUtYoBAO6d
    R5XdiQYA7p3QlNOKBgBYnmWV+4kBAFeeHpa0igEA7p08ltKKBgCKnJmUNYwGAFie+JNpiwEA7p1H
    lUqLBgDundCUQIwGAFiespQijAEAjZwPli+MBgBYnmWVaIsBAFeeHpYhjAEA7p08lkCMBgCSneuX
    V4oGAO6ds5bciQYAO55cl3mKAQBans2W9okBAO+dlZe3igYAL57Zl/aKAQCnnDiYG4oGABqdOpiT
    igYAN52kmLGKAQDRnTWYHIoBAJmd55fIiwYA7p2zlkmLBgBansyWYosBAD+eU5fmiwEA9Z2OlyOM
    BgA4ntCXZIwBAGecOJhKiwYAgJykmGOLAQBBnUKYJIwGAAWdi5joiwEAg52EmGWMAQDanS6YiosB
    AI+cjZWxjAYAj5yLlLONBgBYnviT1owBAO6dR5W4jAYA7p3QlK6NBgBYnrKUkI0BAI+cDJagjQYA
    WJ5lldaMAQBXnh6Wj40BAO6dPZatjQYAj5yMlR6OBgCOnIqUIo8GAO6dR5UljgYA7p3QlBuPBgBY
    nviTQ44BAFiespT9jgEAkJwMlg2PBgBYnmWVQ44BAFeeHpb8jgEA7p09lhqPBgCbneaXNo0GAO6d
    s5a2jAYAWp7MltCMAQBBnlKXVo0BAPadjZeSjQYAaJw3mLWMBgCBnKOYzowBAASdiZhTjQEAQZ1B
    mJGNBgDfnSqY+4wBAJKd65ehjgYA7p2zliSOBgA2ntCX1I0BADyeXZfDjgEAWZ7Nlj+OAQDvnZWX
    AI8GAKacOZhkjgYAgp2GmNCNAQAZnTyY3I4GANWdM5hpjgEA/5c3lNyQAQCil8+UPZEBAGCYR5Ut
    kQYA6JcKlYCRBgB3mTmU3JABAO6Yu5S9kAEA1pjSlCqRBgCPmYaVKpEGAD6YZZXEkAEAnZc2lkKR
    AQDil3eWgpEGAP2YGJa/kAEAZpimltKQAQAZmf2VKpEGAJKbO5QokAEAJJxxlaCPAQBGnOqUKZAB
    AI+bkpY7jwEA7Js4ltGPAQAvnHuWEJAGAG+aqpS9kAEArZlolcGQAQCMmoqUJpEGAMSbv5QkkQYA
    QptAlSeRBgAim1uVvZABAGGaHJbBkAEARZo9liqRBgDtm4aVgpABADCcxZXFkAYAN5s5loKQAQB5
    m3qWxZAGAOmXJJf2kAEAM5jdlieRBgD+l86XmZEBALGZzpa/kAEAJplol9KQAQComOSX95ABAM+Z
    tJYqkQYA75ialyiRBgBUmeuXg5EGAJKZM5hEkQEAzppMlzqPAQCFmsqXy48BAM+a95cUkAYANJvt
    ltOPAQB4mzGXD5AGAC+bq5i0jwEAl5pAmFaQAQDZm6KY/o4BAIaco5ixjwEASJtAmNOPBgCCmvOW
    f5ABAMKaMpfEkAYAJJrLl96QAQBmmoqXIJEGAB6bopghkQEAuJs7mEyQBgDam6OYbJABAIaco5gf
    kQEAPJs4mD+RBgArl/mT15EBAJWXSJX4kQYAk5fRlGySBgAol7eUh5IBACyXZZXXkQEAKJciloiS
    AQCUlz2WbZIGAEaXM5QYkwEAVpcilZSTAQCTl2OVTpMGALKXkZTukwEA8ZdVlKWTBgBomIeV9JMG
    ANyYkpTykwYAz5mHlfGTBgBFl6CVGJMBAC6X2JZEkwEAr5cFluiTAQDwl8SVpJMGANuY/5XykwYA
    RpqRlPGTBgCzm5CU8ZMGADybh5XxkwYARpr+lfGTBgCzm/6V8ZMGACmX0pbckQEAkpe0lvqRBgBC
    mIqX15EGAJeXa5etkgYALpeKl5GSAQBimDWYrZIGAEKYn5iRkgEAGJk6mPuRBgD6mKSY3ZEBAI+Z
    OZhukgYAmJf1liSTBgDql+OX65IGAOuXMZeckwYAY5j0lvCTBgCnl3CX35MBAM2Z8ZbykwYAm5jh
    l5yTBgDZmGmX8JMGAKaXJpgqkwEAXJglmN+TAQDYmDWYJJMGAPSYnphEkwEAhJo4mPWRBgBmmqGY
    15EBAKuZpJiIkgEAs5s4mLWRBgDRm6KY05EBAPqaOJhskgYAFJujmIaSAQCEnKKYi5IBAAia3Zek
    kwYARZpkl/STBgA6m/GW8pMGAHeb25elkwYAs5tjl/WTBgAtmoiYF5MBAGmaOZhOkwYAqpp3mJST
    AQDHmR2Y6JMBAJabgpgUkwEA1Zs5mE6TBgASnHyYkZMBADubGpjvkwEAkJyNlYqPBgBYnviTsI8B
    AFiespRqkAEA7p1HlZKPBgBYnmWVsI8BAFeeHpZpkAEAi5ytlGuQBgDundCUiJAGAFie+JMekQEA
    7p1Hlf+QBgDunT2WiJAGAFieZZUekQEAkJ3slw2QBgAtntqXQY8BAO6ds5aRjwYAO55fly+QAQBZ
    ns2WrI8BADadppj6jgEAppw6mNCPBgDPnTaY0Y8BAJCd7Jd6kQYA7p2Wl2yQBgAsntuXrZABAO6d
    s5b+kAYAPJ5hl56RAQBZns6WGZEBABidPZhJkAYANZ2mmGeQAQCmnDqYPpEGAM+dNpg/kQEA7p3P
    lPWRBgBXnrGU1pEBAFqe85OGkgEA7p1GlWuSBgBYnh+W15EBAO6dPZb1kQYAWZ5hlYaSAQCQnVWU
    pZMGABidkZT1kwYAppyFlfKTBgA7nneUF5MBAO6dtJRPkwYALJ71lJOTAQCQncKVpZMGABid/pX1
    kwYAPJ7llRiTAQDunSKWT5MGACqeZJaUkwEAz52Gle6TAQDunZeX2pEGACqe3ZcdkgEA7p20lmyS
    BgBYntGWipIBABidPZi2kQYANZ2nmNWRAQCknDmYqpIGAM6dN5i0kgEAjJ3tl+ySBgCknPGW8pMG
    AIydMpemkwYA3Jzjl5+TBgATnWqX9ZMGAD2ed5cwkwEA3p2kl12TBgABnvCXqpMBAM+d+pbvkwEA
    Ep07mCWTBgAunaWYRZMBAJ6cI5jmkwEA+5i/gFyUAQBKmHCBXJQBAGeawYBflAEA05u+gF2UAQCv
    mW+BWpQBAGiaJYJalAEAHZtxgVuUAQDTmyWCWpQBAEyY3IJflAEA+pgkglqUAQCwmd2CWpQBAEyY
    SYRflAEA/JiSg1uUAQCxmUmEW5QBABub2IJalAEA1JuSg1mUAQBjmpCDWpQBAB2bSoRalAEABJ13
    gEGUAQCCnfaAPZQBAIKcaYFdlAEAB53rgUOUAQCEnWmCO5QBAICc04JdlAEABp1Xg0OUAQCDndaD
    PJQBAIGcP4RclAEABJ3EhEGUAQBMmLaFX5QBAPyY/4RblAEAsZm3hVuUAQBKmCWHXpQBAPyYbYZb
    lAEAsZkkh1uUAQBkmv2EW5QBAB2bt4VblAEA0Jv9hFqUAQCGnLWFWpQBAGSaaoZblAEAHZskh1uU
    AQDRm2qGW5QBAIacIYdblAEARZiSiFmUAQD7mNqHW5QBALCZkYhblAEATZj+iV+UAQD4mESJW5QB
    ALCZ/olblAEAZJrXh1uUAQAdm5GIW5QBANGb14dblAEAhZyPiFuUAQBkmkWJW5QBAB2b/olblAEA
    0ZtFiVuUAQCFnPyJW5QBAIKdQIU+lAEANp1rhl6UAQA1ndiHX5QBADWdRYlflAEA/Ji0iluUAQBM
    mGuLX5QBALGZbItblAEA/JgijFuUAQBkmrKKW5QBANGbsopblAEAHZtsi1uUAQBkmh+MW5QBAIWc
    aYtblAEA0ZsfjFuUAQBMmNmMX5QBALGZ2YxblAEA/JiPjVuUAQBMmEaOX5QBALGZRo5blAEAHZvZ
    jFuUAQBkmoyNW5QBAIWc14xblAEA0ZuMjVuUAQAdm0aOW5QBAIWcRI5blAEANZ2yil+UAQA1nR+M
    X5QBADWdjY1flAEASpi0j16UAQD8mPyOW5QBALGZs49blAEARZghkVmUAQD7mGmQW5QBALCZIZFb
    lAEAZJr6jluUAQAdm7OPW5QBANGb+o5blAEAhZyxj1uUAQBkmmeQW5QBAB2bIZFblAEA0ZtnkFuU
    AQCFnB6RW5QBAE2YjpJflAEA+JjUkVuUAQCwmY6SW5QBAEyY+5NflAEA/JhEk1uUAQCxmfuTW5QB
    AGSa1JFblAEAHZuOkluUAQDRm9SRW5QBAIWcjJJblAEAZJpBk1uUAQAdm/uTW5QBANGbQZNblAEA
    hZz5k1uUAQA1nfqOX5QBADWdZ5BflAEANZ3UkV+UAQA1nUKTX5QBAEqYaZVelAEA/JixlFuUAQCx
    mWmVW5QBAEOY1pZZlAEA+5gelluUAQCumdGWW5QBAGSar5RblAEAHZtolVuUAQDRm6+UW5QBAIWc
    ZpVblAEAZJoclluUAQAbm9CWW5QBANGbHJZblAEAhJzRlluUAQD2mImXWZQBAGOagpdelAEA0ZuA
    l1+UAQA1na+UX5QBADWdHJZflAEALp2Jl1+UAQA=
    """
}
